C
C  Internal Data for PLOTPAK
C
      COMMON /ZZZPLT/
     X  XPGMIN , YPGMIN , XPGMAX , YPGMAX ,
     X  XCLBOT , YCLBOT , XCLTOP , YCLTOP ,
     X  XBOT   , YBOT   , XTOP   , YTOP   ,
     X  XMIN   , YMIN   , XMAX   , YMAX   , IXCOOR , IYCOOR ,
     X  ALPHXX , BETAXX , ALPHYY , BETAYY ,
     X  TMAJX  , TMINX  , TMAJY  , TMINY  ,
     X  MAJRX  , MINRX  , MAJRY  , MINRY  , ISIZX  , ISIZY  ,
     X  XPHOLD , YPHOLD
      CHARACTER*64 CFILE
      COMMON / ZZPLTR /
     X
     X  XPHMAX , YPHMAX , IXPMAX , IYPMAX , XPSCAL , YPSCAL ,
     X  IFLIP  , NPLOTR , CFILE
