FROM ubuntu:bionic-20180526@sha256:c8c275751219dadad8fa56b3ac41ca6cb22219ff117ca98fe82b42f24e1ba64e
USER root
RUN apt-get update -y ; apt-get upgrade -y

ARG DEBIAN_FRONTEND=noninteractive

RUN apt-get install -y \
      python-qt4 git tcsh vim libxmu-dev libxt-dev libmotif-dev libxpm-dev \
      libxi-dev libxmhtml-dev libglw1-mesa-dev libglu1-mesa-dev libglib2.0-dev \
      libgsl-dev r-base m4
RUN apt-get install -yq --no-install-recommends g++ gcc
RUN apt-get install -y python3-pip \
    && pip3 install --no-cache-dir pytest pytest-cov codecov

#######################################
# this copies source code from the host
# into the image and invalidates the cache
WORKDIR /usr/afni_build_dir
COPY . .

ENV PATH=$PATH:/usr/afni_build_dir/src/afni_src/abin
ARG VERSION
# RUN git checkout "${VERSION}"
WORKDIR /usr/afni_build_dir/src

# make changes to add coverage flags to makefile
RUN sed -i 's/# CPROF = /CPROF =  -coverage /' Makefile.linux_ubuntu_16_64

# o files are ignored by the repo but will
# cause the build to fail.
RUN make -f  Makefile.linux_ubuntu_16_64  afni_src.tgz \
    && tar zxvf afni_src.tgz \
    && cd afni_src \
    && cp Makefile.linux_ubuntu_16_64 Makefile
WORKDIR /usr/afni_build_dir/src/afni_src
# RUN make libmri.so
RUN make itall && mv linux_ubuntu_16_64 /opt/abin
ENV PATH="/opt/abin:${PATH}"

WORKDIR /opt/abin
