name: template_making
channels:
  - defaults
  - conda-forge
  - leej3
dependencies:
  - afni
  - bokeh
  - cloudpickle
  - cython
  - dask
  - distributed
  - dask-jobqueue
  - graphviz
  - pip
  - python-graphviz
  - tcsh
  - pip:
    - -e ..
    - -e .

