/*****
* Automatically generated file.
* *** DO NOT EDIT THIS FILE ***
*****/
/*****
* File created at Thu Sep 24 20:45:45 CEST 1998 by newt
*****/

#ifndef _xpmtags_h_
#define _xpmtags_h_

#include <pixmaps/tags/DOCTYPE.xpm>
#include <pixmaps/tags/A.xpm>
#include <pixmaps/tags/ADDRESS.xpm>
#include <pixmaps/tags/APPLET.xpm>
#include <pixmaps/tags/AREA.xpm>
#include <pixmaps/tags/B.xpm>
#include <pixmaps/tags/BASE.xpm>
#include <pixmaps/tags/BASEFONT.xpm>
#include <pixmaps/tags/BIG.xpm>
#include <pixmaps/tags/BLOCKQUOTE.xpm>
#include <pixmaps/tags/BODY.xpm>
#include <pixmaps/tags/BR.xpm>
#include <pixmaps/tags/CAPTION.xpm>
#include <pixmaps/tags/CENTER.xpm>
#include <pixmaps/tags/CITE.xpm>
#include <pixmaps/tags/CODE.xpm>
#include <pixmaps/tags/DD.xpm>
#include <pixmaps/tags/DFN.xpm>
#include <pixmaps/tags/DIR.xpm>
#include <pixmaps/tags/DIV.xpm>
#include <pixmaps/tags/DL.xpm>
#include <pixmaps/tags/DT.xpm>
#include <pixmaps/tags/EM.xpm>
#include <pixmaps/tags/FONT.xpm>
#include <pixmaps/tags/FORM.xpm>
#include <pixmaps/tags/FRAME.xpm>
#include <pixmaps/tags/FRAMESET.xpm>
#include <pixmaps/tags/H1.xpm>
#include <pixmaps/tags/H2.xpm>
#include <pixmaps/tags/H3.xpm>
#include <pixmaps/tags/H4.xpm>
#include <pixmaps/tags/H5.xpm>
#include <pixmaps/tags/H6.xpm>
#include <pixmaps/tags/HEAD.xpm>
#include <pixmaps/tags/HR.xpm>
#include <pixmaps/tags/HTML.xpm>
#include <pixmaps/tags/I.xpm>
#include <pixmaps/tags/IMG.xpm>
#include <pixmaps/tags/INPUT.xpm>
#include <pixmaps/tags/ISINDEX.xpm>
#include <pixmaps/tags/KBD.xpm>
#include <pixmaps/tags/LI.xpm>
#include <pixmaps/tags/LINK.xpm>
#include <pixmaps/tags/MAP.xpm>
#include <pixmaps/tags/MENU.xpm>
#include <pixmaps/tags/META.xpm>
#include <pixmaps/tags/NOFRAMES.xpm>
#include <pixmaps/tags/OL.xpm>
#include <pixmaps/tags/OPTION.xpm>
#include <pixmaps/tags/P.xpm>
#include <pixmaps/tags/PAGE.xpm>
#include <pixmaps/tags/PARAM.xpm>
#include <pixmaps/tags/PRE.xpm>
#include <pixmaps/tags/SAMP.xpm>
#include <pixmaps/tags/SCRIPT.xpm>
#include <pixmaps/tags/SELECT.xpm>
#include <pixmaps/tags/SMALL.xpm>
#include <pixmaps/tags/STRIKE.xpm>
#include <pixmaps/tags/STRONG.xpm>
#include <pixmaps/tags/STYLE.xpm>
#include <pixmaps/tags/SUB.xpm>
#include <pixmaps/tags/SUP.xpm>
#include <pixmaps/tags/TAB.xpm>
#include <pixmaps/tags/TABLE.xpm>
#include <pixmaps/tags/TD.xpm>
#include <pixmaps/tags/TEXTAREA.xpm>
#include <pixmaps/tags/TH.xpm>
#include <pixmaps/tags/TITLE.xpm>
#include <pixmaps/tags/TR.xpm>
#include <pixmaps/tags/TT.xpm>
#include <pixmaps/tags/U.xpm>
#include <pixmaps/tags/UL.xpm>
#include <pixmaps/tags/VAR.xpm>
#include <pixmaps/tags/ZTEXT.xpm>

#define NUM_TAG_ICONS	74

/*****
* List of all HTML tags and their corresponding icons
*****/

IconEntity _XmHTMLTagIcons[NUM_TAG_ICONS] = {
	{"DOCTYPE", DOCTYPE_xpm, NULL, 7},
	{"A", A_xpm, NULL, 1},
	{"ADDRESS", ADDRESS_xpm, NULL, 7},
	{"APPLET", APPLET_xpm, NULL, 6},
	{"AREA", AREA_xpm, NULL, 4},
	{"B", B_xpm, NULL, 1},
	{"BASE", BASE_xpm, NULL, 4},
	{"BASEFONT", BASEFONT_xpm, NULL, 8},
	{"BIG", BIG_xpm, NULL, 3},
	{"BLOCKQUOTE", BLOCKQUOTE_xpm, NULL, 10},
	{"BODY", BODY_xpm, NULL, 4},
	{"BR", BR_xpm, NULL, 2},
	{"CAPTION", CAPTION_xpm, NULL, 7},
	{"CENTER", CENTER_xpm, NULL, 6},
	{"CITE", CITE_xpm, NULL, 4},
	{"CODE", CODE_xpm, NULL, 4},
	{"DD", DD_xpm, NULL, 2},
	{"DFN", DFN_xpm, NULL, 3},
	{"DIR", DIR_xpm, NULL, 3},
	{"DIV", DIV_xpm, NULL, 3},
	{"DL", DL_xpm, NULL, 2},
	{"DT", DT_xpm, NULL, 2},
	{"EM", EM_xpm, NULL, 2},
	{"FONT", FONT_xpm, NULL, 4},
	{"FORM", FORM_xpm, NULL, 4},
	{"FRAME", FRAME_xpm, NULL, 5},
	{"FRAMESET", FRAMESET_xpm, NULL, 8},
	{"H1", H1_xpm, NULL, 2},
	{"H2", H2_xpm, NULL, 2},
	{"H3", H3_xpm, NULL, 2},
	{"H4", H4_xpm, NULL, 2},
	{"H5", H5_xpm, NULL, 2},
	{"H6", H6_xpm, NULL, 2},
	{"HEAD", HEAD_xpm, NULL, 4},
	{"HR", HR_xpm, NULL, 2},
	{"HTML", HTML_xpm, NULL, 4},
	{"I", I_xpm, NULL, 1},
	{"IMG", IMG_xpm, NULL, 3},
	{"INPUT", INPUT_xpm, NULL, 5},
	{"ISINDEX", ISINDEX_xpm, NULL, 7},
	{"KBD", KBD_xpm, NULL, 3},
	{"LI", LI_xpm, NULL, 2},
	{"LINK", LINK_xpm, NULL, 4},
	{"MAP", MAP_xpm, NULL, 3},
	{"MENU", MENU_xpm, NULL, 4},
	{"META", META_xpm, NULL, 4},
	{"NOFRAMES", NOFRAMES_xpm, NULL, 8},
	{"OL", OL_xpm, NULL, 2},
	{"OPTION", OPTION_xpm, NULL, 6},
	{"P", P_xpm, NULL, 1},
	{"PAGE", PAGE_xpm, NULL, 4},
	{"PARAM", PARAM_xpm, NULL, 5},
	{"PRE", PRE_xpm, NULL, 3},
	{"SAMP", SAMP_xpm, NULL, 4},
	{"SCRIPT", SCRIPT_xpm, NULL, 6},
	{"SELECT", SELECT_xpm, NULL, 6},
	{"SMALL", SMALL_xpm, NULL, 5},
	{"STRIKE", STRIKE_xpm, NULL, 6},
	{"STRONG", STRONG_xpm, NULL, 6},
	{"STYLE", STYLE_xpm, NULL, 5},
	{"SUB", SUB_xpm, NULL, 3},
	{"SUP", SUP_xpm, NULL, 3},
	{"TAB", TAB_xpm, NULL, 3},
	{"TABLE", TABLE_xpm, NULL, 5},
	{"TD", TD_xpm, NULL, 2},
	{"TEXTAREA", TEXTAREA_xpm, NULL, 8},
	{"TH", TH_xpm, NULL, 2},
	{"TITLE", TITLE_xpm, NULL, 5},
	{"TR", TR_xpm, NULL, 2},
	{"TT", TT_xpm, NULL, 2},
	{"U", U_xpm, NULL, 1},
	{"UL", UL_xpm, NULL, 2},
	{"VAR", VAR_xpm, NULL, 3},
	{"ZTEXT", ZTEXT_xpm, NULL, 5},
	{NULL, NULL, NULL, 0}
};

/* Don't add anything after this endif! */
#endif /* _xpmtags_h_ */

