from setuptools import setup

ENTRY_POINTS={'console_scripts':
    [
    '1d_tool.py=afni_python.1d_tool:main',
    '1dplot.py=afni_python.1dplot:main',
    # '@DoPerRoi.py=afni_python.@DoPerRoi:main',
    # '@djunct_calc_mont_dims.py=afni_python.@djunct_calc_mont_dims:main',
    # '@djunct_combine_str.py=afni_python.@djunct_combine_str:main',
    # '@djunct_select_str.py=afni_python.@djunct_select_str:main',
    'BayesianGroupAna.py=afni_python.BayesianGroupAna:main',
    'abids_json_info.py=afni_python.abids_json_info:main',
    'abids_json_tool.py=afni_python.abids_json_tool:main',
    'abids_lib.py=afni_python.abids_lib:main',
    'abids_tool.py=afni_python.abids_tool:main',
    'afni_base.py=afni_python.afni_base:main',
    'afni_proc.py=afni_python.afni_proc:main',
    'afni_restproc.py=afni_python.afni_restproc:main',
    'afni_skeleton.py=afni_python.afni_skeleton:main',
    'afni_system_check.py=afni_python.afni_system_check:main',
    'afni_util.py=afni_python.afni_util:main',
    'afni_xmat.py=afni_python.afni_xmat:main',
    'align_epi_anat.py=afni_python.align_epi_anat:main',
    'apqc_make_html.py=afni_python.apqc_make_html:main',
    'apqc_make_tcsh.py=afni_python.apqc_make_tcsh:main',
    'ask_me.py=afni_python.ask_me:main',
    'auto_warp.py=afni_python.auto_warp:main',
    'construct_template_graph.py=afni_python.construct_template_graph:main',
    'dask_job_wrapper.py=afni_python.dask_job_wrapper:main',
    'db_mod.py=afni_python.db_mod:main',
    'eg_main_chrono.py=afni_python.eg_main_chrono:main',
    'fat_lat_csv.py=afni_python.fat_lat_csv:main',
    'fat_mat_sel.py=afni_python.fat_mat_sel:main',
    'fat_mvm_gridconv.py=afni_python.fat_mvm_gridconv:main',
    'fat_mvm_prep.py=afni_python.fat_mvm_prep:main',
    'fat_mvm_review.py=afni_python.fat_mvm_review:main',
    'fat_mvm_scripter.py=afni_python.fat_mvm_scripter:main',
    'fat_roi_row.py=afni_python.fat_roi_row:main',
    'gen_epi_review.py=afni_python.gen_epi_review:main',
    'gen_group_command.py=afni_python.gen_group_command:main',
    'gen_ss_review_scripts.py=afni_python.gen_ss_review_scripts:main',
    'gen_ss_review_table.py=afni_python.gen_ss_review_table:main',
    'gui_uber_align_test.py=afni_python.gui_uber_align_test:main',
    'gui_uber_skel.py=afni_python.gui_uber_skel:main',
    'gui_uber_subj.py=afni_python.gui_uber_subj:main',
    'gui_uber_ttest.py=afni_python.gui_uber_ttest:main',
    'gui_xmat.py=afni_python.gui_xmat:main',
    'lpc_align.py=afni_python.lpc_align:main',
    'make_pq_script.py=afni_python.make_pq_script:main',
    'make_random_timing.py=afni_python.make_random_timing:main',
    'make_stim_times.py=afni_python.make_stim_times:main',
    'make_template_dask.py=afni_python.make_template_dask:main',
    'module_test_lib.py=afni_python.module_test_lib:main',
    'neuro_deconvolve.py=afni_python.neuro_deconvolve:main',
    'option_list.py=afni_python.option_list:main',
    'parse_fs_lt_log.py=afni_python.parse_fs_lt_log:main',
    'python_module_test.py=afni_python.python_module_test:main',
    'quick.alpha.vals.py=afni_python.quick.alpha.vals:main',
    'read_matlab_files.py=afni_python.read_matlab_files:main',
    'realtime_receiver.py=afni_python.realtime_receiver:main',
    'regwrap.py=afni_python.regwrap:main',
    'slow_surf_clustsim.py=afni_python.slow_surf_clustsim:main',
    'tedana_wrapper.py=afni_python.tedana_wrapper:main',
    'timing_tool.py=afni_python.timing_tool:main',
    'uber_align_test.py=afni_python.uber_align_test:main',
    'uber_proc.py=afni_python.uber_proc:main',
    'uber_skel.py=afni_python.uber_skel:main',
    'uber_subject.py=afni_python.uber_subject:main',
    'uber_ttest.py=afni_python.uber_ttest:main',
    'ui_xmat.py=afni_python.ui_xmat:main',
    'unWarpEPI.py=afni_python.unWarpEPI:main',
    'xmat_tool.py=afni_python.xmat_tool:main'
    ]}


setup(name='afni_python',
      version='0.0.1',
      description='AFNI python packages',
      url='git+https://github.com/leej3/template_making.git',
      author='AFNI team',
      author_email='afni.bootcamp@gmail.com',
      license='Public Domain',
      packages=['afni_python'],
      install_requires=[
          'numpy'
      ],
      entry_points=ENTRY_POINTS,
      zip_safe=False)
