
.. _AfniCont:




                    * 98 *
From you have I been absent in the spring,
When proud-pied April dress'd in all his trim
Hath put a spirit of youth in every thing,
That heavy Saturn laugh'd and leap'd with him.
Yet nor the lays of birds nor the sweet smell
Of different flowers in odour and in hue
Could make me any summer's story tell,
Or from their proud lap pluck them where they grew;
Nor did I wonder at the lily's white,
Nor praise the deep vermilion in the rose;
They were but sweet, but figures of delight,
Drawn after you, you pattern of all those.
  Yet seem'd it winter still, and, you away,
  As with your shadow I with these did play:


.. _AfniCont->ProgCont:

rowcol to hold all program controls stuff
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Here is where the help would go.

Hiding things that only the Sphinx sees.

   .. figure:: media/william-shakespeare.jpg
      :align: center
      :figwidth: 50%
      :name: Bill
      :target: http://www.poetryfoundation.org/bio/william-shakespeare

      :ref:`Frequent contributor<Bill>`




   .. _AfniCont->ProgCont->done:

:ref:`done<AfniCont->ProgCont->done>`: Click twice to close window


     Press (twice) to
     close this AFNI
     control window.
   
   N.B.: when the last
     control window is
     closed, AFNI will
     quit.
   
   Pressing this button
   with the Shift or Ctrl
   keys, or with the other
   mouse buttons also down,
   will also make AFNI quit.
