
.. _AfniCont->ProgCont:

rowcol to hold all program controls stuff
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Wish to write something here?

   .. _AfniCont->ProgCont->done:

:ref:`done<AfniCont->ProgCont->done>`: Click twice to close window


     Press (twice) to
     close this AFNI
     control window.
   
   N.B.: when the last
     control window is
     closed, AFNI will
     quit.
   
   Pressing this button
   with the Shift or Ctrl
   keys, or with the other
   mouse buttons also down,
   will also make AFNI quit.
