
.. _AfniCont:




************************************************
* GPL AFNI: Analysis of Functional NeuroImages *
*           Version AFNI_16.2.00               *
*                                              *
* Major portions are Copyright 1994-2000,      *
*   Medical College of Wisconsin               *
*   Milwaukee, WI 53226-0509                   *
* See file README.copyright for information,   *
* or the Datamode->Misc->License menu item.    *
*                                              *
* Released to the public by MCW under the GNU  *
* General Public License (version 2), Dec 2000 *
*                                              *
* Author:  Robert W Cox, PhD                   *
************************************************

   .. figure:: media/AfniCont.auto.jpg
      :name: media/AfniCont.auto.jpg
      :align: center

      :ref: `(link)<media/AfniCont.auto.jpg>`



.. _AfniCont->ProgCont:

rowcol to hold all program controls stuff
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

Here is where the help would go.

Although this image is in the string used by BHelp, it only seen by the Sphinx.

   .. figure:: media/william-shakespeare.jpg
      :align: center
      :figwidth: 50%
      :name: Bill
      :target: http://www.poetryfoundation.org/bio/william-shakespeare

      :ref:`Frequent contributor<Bill>`




   .. _AfniCont->ProgCont->done:

:ref:`done<AfniCont->ProgCont->done>`: Click twice to close window


     Press (twice) to
     close this AFNI
     control window.
   
   N.B.: when the last
     control window is
     closed, AFNI will
     quit.
   
   Pressing this button
   with the Shift or Ctrl
   keys, or with the other
   mouse buttons also down,
   will also make AFNI quit.
