# Makefile for znzlib

# This file is released to the public domain

# specify the path to the include files for zlib on this system
# if it is not in the standard include paths for the compiler
#   e.g. -I/usr/unusual/include
LIBZINC=

all:
	gcc ${LIBZINC} -c -o znzlib.o znzlib.c

clean:
	rm *.o

