#!/bin/tcsh -f

if ("$1" == "-h" || "$1" == "-help") then
   echo "`basename $0`  : Returns path where afni executable resides."
   goto END
endif

set l = `which afni`
if ($status) then
   echo NO_afni_FOUND
else
   echo $l:h
endif

END:
