#!/bin/tcsh -f
set min = 0
set max = 0
set mean = 0
if ("$1" == '-min') then
   set dset=$2
   set min = 1
else if ("$1" == '-max') then
   set dset=$2
   set max = 1
else if ("$1" == '-mean') then
   set dset=$2
   set mean = 1
else if ("$1" == '-help' || "$1" == '-h' || "$1" == "") then
   echo "`basename $0` [-min|-max|-mean] dset"
   echo "Return the voxel resolution of dset"
   echo ""
   goto END
else
   set dset = $1
endif

set d1 = `3dAttribute -name DELTA $dset`
set dx = `ccalc -eval "abs($d1[3])"`
set dy = `ccalc -eval "abs($d1[4])"`
set dz = `ccalc -eval "abs($d1[5])"`
if ($mean) then
   echo `ccalc -expr "($dx+$dy+$dz)/3"`
else if ($min) then
   echo `ccalc -expr "min($dx,min($dy,$dz))"`
else if ($max) then
   echo `ccalc -expr "max($dx,max($dy,$dz))"`
else
   echo $dx $dy $dz
endif

END:
