.. _Colormap_Keyboard_Controls:

Colormap Keyboard Controls:
---------------------------

With the cursor over the colormap, the following keyboard initiated actions
are available.

     
.. _CM_LC_f:

:kbd:`f`: flip color map
        See also Up/Down keys.

     
.. _CM_LC_Ctrl+h:

:kbd:`Ctrl+h`: this help message

     
.. _CM_LC_r:

:kbd:`r`: record image of colormap.

     
.. _CM_LC_w:

:kbd:`w`: write colormap to ascii file.

     
.. _CM_UC_Z:

:kbd:`Z`: Zoom in.
        Maximum zoom in shows 2 colors in the map
     
.. _CM_LC_z:

:kbd:`z`: Zoom out.
        Minimum zoom in shows all colors in the map

     
.. _CM_U-D_arrows:

:kbd:`U-D arrows` arrows: rotate colormap up/down by fraction of
                     number of colors in color map. Fraction
                     a number between 0 and 0.5 and set via
                     the environment variable
                     SUMA_ColorMapRotationFraction.
                     See suma -environment for complete list
                     of variables.

     
.. _CM_Ctrl+U-D_arrows:

:kbd:`Ctrl+U-D arrows`: rotate colormap up/down by one color
     
.. _CM_Shift+U-D_arrows:

:kbd:`Shift+U-D arrows`: move colormap up/down

     
.. _CM_HOME:

:kbd:`HOME`: Reset zoom, translation and rotation parameters


