#!/bin/tcsh -f

echo ""
echo "$*"
printf "    Hit Enter twice when ready..."
set jnk = $<
if ("$jnk" == 'q' || "$jnk" == 'Q') then
   exit 1
endif
printf "       again ('q' to quit)"
set jnk = $<
echo ""
if ("$jnk" == 'q' || "$jnk" == 'Q') then
   exit 1
else
   exit 0
endif
