#!/bin/tcsh -f
#Example commands for running DriveSuma
#Creates a temporary directory called tmp_suma
#You're better off cutting and pasting individual commands.
#Otherwise script will run too fast.

mkdir tmp_suma
cd tmp_suma

#show_surf action
        CreateIcosahedron -rd 4
        suma -niml &
        echo 'Wait until suma is ready then proceed.'
        set l = $<
        echo '                  one more time.'
        set l = $<
        DriveSuma -com show_surf -label icoco \
                       -i_fs CreateIco.asc

#node_xyz action
        ConvertSurface -i_fs CreateIco.asc \
                       -o_1D radcoord radcoord \
                       -radial_to_sphere 100
        DriveSuma -com node_xyz -label icoco \
                       -xyz_1D radcoord.1D.coord'[0,1,2]'
        1deval -a radcoord.1D.coord'[0]' -expr 'sin(a)*100' \
            > xmess.1D ;1dcat xmess.1D radcoord.1D.coord'[1,2]' \
            > somecoord.1D.coord ; rm xmess.1D
        DriveSuma -com node_xyz -label icoco \
                       -xyz_1D somecoord.1D.coord
        
        echo 'Hit Enter to proceed to viewer control actions.'
        set l = $<

#viewer_cont action
       DriveSuma -com  viewer_cont -key R -key ctrl+right
       DriveSuma -com  viewer_cont -key:r3:s0.3 up  \
                       -key:r2:p left -key:r5:d right \
                       -key:r5 left
       DriveSuma -com  viewer_cont -key m -key down \
                 -com  sleep 2s -com viewer_cont -key m \
                       -key ctrl+right
       DriveSuma -com  viewer_cont -key m -key right \
                 -com  pause press enter to stop this misery \
                 -com  viewer_cont -key m 

        echo 'Hit Enter to proceed to recorder control actions.'
        echo 'If you have recorded too many images, saving'
        echo 'a movie of all of them will take a while.'
        set l = $<

#recorder_cont action
       DriveSuma -com  recorder_cont -save_as allanimgif.agif \
                 -com  recorder_cont -save_as lastone.jpg \
                 -com  recorder_cont -save_as three.jpg -save_index 3\
                 -com  recorder_cont -save_as some.png -save_range 3 6

        echo 'Hit Enter to proceed to surface control actions.'
        set l = $<

#surf_cont action
       echo 1 0 0 > bbr.1D.cmap; echo 1 1 1 >> bbr.1D.cmap; \
       echo 0 0  1 >> bbr.1D.cmap
       IsoSurface -shape 4 128 -o_ply blooby.ply
       quickspec -spec blooby.spec -tn ply blooby.ply
       SurfaceMetrics -curv -spec blooby.spec \
                      -surf_A blooby -prefix blooby      
       DriveSuma -com show_surf -surf_label blooby \
                      -i_ply blooby.ply -surf_winding cw \
                      -surf_state la_blooby
       DriveSuma -com surf_cont -load_dset blooby.curv.1D.dset \
                      -surf_label blooby -view_surf_cont y
       DriveSuma -com surf_cont -I_sb 7 -T_sb 8 -T_val 0.0
       DriveSuma -com surf_cont -I_range 0.05 -T_sb -1
       DriveSuma -com surf_cont -I_sb 8 -I_range -0.1 0.1 \
                      -T_val 0.02
       DriveSuma -com surf_cont -B_sb 7 -B_range 0.1 \
                      -B_scale 0.1 0.9 
       DriveSuma -com surf_cont -switch_dset Convexity -1_only y
       DriveSuma -com surf_cont -switch_cmap roi64 -1_only n
       DriveSuma -com surf_cont -view_dset n
       DriveSuma -com surf_cont -switch_dset blooby.curv.1D.dset \
                      -view_surf_cont n -I_range -0.05 0.14
       DriveSuma -com surf_cont -load_cmap bbr.1D.cmap

       echo 'Hit Enter to quit'
       set l = $<

      
#Adieu
      DriveSuma -com kill_suma
       
       

END:

