#!/bin/tcsh -f
set noglob
set estat = 0

if ("$1" == '' || "$1" == '-h' || "$1" == '-help') then
	goto USAGE
else if ("$1" == "-av") then
   set spc = `3dAttribute  TEMPLATE_SPACE $2`
   set spc = `echo $spc | sed 's/\~$//'`
   if ($spc == "ORIG") then
      echo "+orig"
   else if ($spc == "ACPC") then
      echo "+acpc"
   else if ($spc == "TLRC") then
      echo "+tlrc"   
   else
      echo "No -av equivalent for $spc"
      goto BEND
   endif
else
   set spc = `3dAttribute  TEMPLATE_SPACE $1`
   echo $spc | sed 's/\~$//'
endif



goto ENDALL

USAGE:
	echo "Usage: `basename $0` [-av] <Name> ....."
	echo "example: `basename $0` /Data/stuff/Hello+orig.HEAD"
	echo "returns the dataset's space for header field: TEMPLATE_SPACE" 
	echo ""
   echo "With -av you can get the corresponding AFNI file format"
   echo "extension."
   echo ""
	goto ENDALL

BEND:
   set estat = 1
   
ENDALL:
unset noglob
exit $estat
