#!/bin/tcsh

# input = skull stripped dataset in 1mm^3 MNI space

set inset = askull

3dAllineate -base MNI111+tlrc -source ${inset}+tlrc -prefix ${inset}_bilin \
            -nwarp bilinear -fineblur 2 -hel -VERB

gwarp MNI111+tlrc ${inset}_bilin+tlrc

3drename gwarp+tlrc ${inset}_gwarp
3dTcat -prefix ${inset}_iter zziter*.HEAD
rm -f zziter* zzbase*
