#!/bin/tcsh -fe

set stat = 0
set sdir = $PWD


goto PARSE
RET_PARSE:

if ( -d ./PTaylor_TractDemo) then
echo ""
echo "ERROR:"
echo "   Directory ./PTaylor_TractDemo exists already"
echo "   If you want to recreate it, remove it with:"
echo "\rm -rf ./PTaylor_TractDemo"
echo "   then run `basename $0` $argv[*] again."
echo ""
echo "Otherwise to run demos, see content of ./PTaylor_TractDemo/README.txt"
echo ""
goto END
   endif

which curl
if ($status) then
   wget http://afni.nimh.nih.gov/pub/dist/tgz/PTaylor_TractDemo.tgz
else
   curl -O http://afni.nimh.nih.gov/pub/dist/tgz/PTaylor_TractDemo.tgz
endif
tar xvzf PTaylor_TractDemo.tgz
cd PTaylor_TractDemo
   echo "********************************************************"
   echo "Follow examples in ./PTaylor_TractDemo/README.txt "
   #echo "---------------------------------------------------------"
   #PT: Normally here you can consider running one or all of the"
   #scripts and quide the users to look at the results.
   #You could eventually script the whole deal to include self "
   #executing AFNI/SUMA commands to show results.
   echo "********************************************************"
cd -
goto END

PARSE:
   set Narg = $#
   set cnt = 1
   while ($cnt <= $Narg)
		set donext = 1;
      if ($donext && "$argv[$cnt]" == "-echo") then
         set echo
         set donext = 0; goto NEXT		
      endif
      if ($donext && ("$argv[$cnt]" == "-h" || "$argv[$cnt]" == "-help")) then
         goto HELP
         set donext = 0;	 goto NEXT	
      endif
      if ($donext == 1) then
         echo "Error: Option or parameter '$argv[$cnt]' not understood"
         goto END
      endif
      
      NEXT:
		@ cnt ++
	end
   
goto RET_PARSE

HELP:
   echo "Installs the demo archive for Paul Taylor's tractography tools"
   echo "After the archive is downloaded and unpacked, see its README.txt"
   echo "for details."
   goto END

BEND:
   echo "Failed"
   set stat = 1
   goto END
   
END:
   exit $stat
