#!/bin/tcsh -f

if ("$1" =~ -h*) then
   echo "Usage: `basename $0` DSET"
   echo "Returns 1 if DSET is in NIFTI format"
   echo "        0 otherwise"
   echo "Decision is based on whether or not DSET has"
   echo "the .nii or .nii.gz extension"
   echo ""
   goto END
endif
 
set isnifti = 0

set l = `@parse_afni_name "$1"`

set ff = `echo $l[2] | \grep '\.nii\.gz$'`
if ($status) then
   set ff = `echo $l[2] | \grep '\.nii$'`
   if ($status == 0) set isnifti = 1
else
   set isnifti = 1
endif

echo $isnifti

END:


