#!/bin/tcsh 

setenv AFNI_R_DIR $0:h

if ( $#argv < 2 ) then
    echo "** afni_run_R: requires at least 2 args"
    exit 1
endif

# note the second to last index
@ penult = $#argv - 1

R --no-restore --save --no-readline < $argv[1-$penult] >& $argv[$#argv]
