static char *license[] = {
   "\n" ,
   "  Major portions of this software are Copyright 1994-2000 by\n" ,
   "\n" ,
   "            Medical College of Wisconsin\n" ,
   "            8701 Watertown Plank Road\n" ,
   "            Milwaukee, WI 53226\n" ,
   "\n" ,
   "  Development of these portions was supported by MCW internal funds, and\n" ,
   "  also in part by NIH grants MH51358 (PI: JS Hyde) and NS34798 (PI: RW Cox).\n" ,
   "\n" ,
   "  *** This software was designed to be used only for research purposes. ***\n" ,
   "  *** Clinical applications are not recommended, and this software has  ***\n" ,
   "  *** NOT been evaluated by the United States FDA for any clinical use. ***\n" ,
   "  ***** There are no plans to EVER evaluate AFNI for clinical usage!! *****\n" ,
   "\n" ,
   "  Neither the Medical College of Wisconsin (MCW), the National Institutes\n" ,
   "  of Health (NIH), nor any of the authors or their institutions, make or\n" ,
   "  imply any warranty of usefulness of this software for any particular\n" ,
   "  purpose, and do not assume any liability for damages, incidental or\n" ,
   "  otherwise, caused by the installation or use of this software.  If\n" ,
   "  these conditions are not acceptable to you or your institution, or are\n" ,
   "  not enforceable by the laws of your jurisdiction, you do not have the\n" ,
   "  right use this software.\n" ,
   "\n" ,
   "  The MCW-copyrighted part of this software is released to the public\n" ,
   "  under the GNU General Public License, Version 2 (or any later version).\n" ,
   "  A copy of this License (GPL v2, that is to say) is appended.\n" ,
   "\n" ,
   "  The final reference copy of the software that was fully derived from\n" ,
   "  MCW code is in the tar/gzip archive file afni98_lastmcw.tgz.  (This does\n" ,
   "  NOT mean that later code is not copyrighted by MCW - that depends on the\n" ,
   "  source file involved.  It simply means that some code developed later comes\n" ,
   "  from the NIH, and is not copyrighted.  Other parts developed or contributed\n" ,
   "  later are from MCW or other institutions that still maintain their copyright,\n" ,
   "  but who release the code under the GPL.)\n" ,
   "\n" ,
   "  The MCW-copyrighted part of the documentation is released to the public\n" ,
   "  under the Open Content License (OCL).  A copy of this license is appended.\n" ,
   "\n" ,
   "  These licensing conditions supersede any other conditions on licensing\n" ,
   "  or distribution that may be found in the files or documents distributed\n" ,
   "  with this software package.\n" ,
   "\n" ,
   "  Other Components\n" ,
   "  ----------------\n" ,
   "  Components of this software and its documentation developed at the US\n" ,
   "  National Institutes of Health (after 15 Jan 2001) are not copyrighted.\n" ,
   "  Components of the software and documentation contributed by people at\n" ,
   "  other institutions are released under the GPL and OCL (respectively),\n" ,
   "  but copyright may be retained by them or their institutions.\n" ,
   "\n" ,
   "  The Talairach Daemon data are incorporated with permission from\n" ,
   "  the Research Imaging Center at the University of Texas Health Sciences\n" ,
   "  Center at San Antonio.  Thanks go to Drs. Jack Lancaster and Peter Fox\n" ,
   "  for sharing this database.\n" ,
   "\n" ,
   "  The netCDF functions included are from the netCDF library from\n" ,
   "  the Unidata Program at the University Corporation for Atmospheric\n" ,
   "  Research (http://www.unidata.ucar.edu/) and distributed in accordance\n" ,
   "  with their Copyright notice (which of course disavows any liability\n" ,
   "  for anything).\n" ,
   "\n" ,
   "  The CDF library routines were developed at the University of Texas\n" ,
   "  M.D. Anderson Cancer Center, and have been placed into the public domain.\n" ,
   "  See the file \"cdflib.txt\" for more details.\n" ,
   "\n" ,
   "  The eis_*.c functions are C translations of the EISPACK library,\n" ,
   "  distributed by Netlib: http://www.netlib.org\n" ,
   "\n" ,
   "  Some of the routines in \"mri_stats.c\" are from the StatLib repository at\n" ,
   "  Carnegie Mellon: http://lib.stat.cmu.edu\n" ,
   "\n" ,
   "  Some of the routines in \"mcw_glob.c\" are derived from the Berkeley Unix\n" ,
   "  distribution.  See that file for their copyright declaration.\n" ,
   "\n" ,
   "  The popup hint functions in \"LiteClue.c\" are from Computer Generation, Inc.\n" ,
   "  See that file for their copyright declaration.\n" ,
   "\n" ,
   "  The volume rendering library \"volpack\" is by Phil Lacroute, and is copy-\n" ,
   "  righted by The Board of Trustees of The Leland Stanford Junior University.\n" ,
   "  See file \"volpack.h\" for their copyright declaration.\n" ,
   "\n" ,
   "  The MD5 routines in thd_md5.c are adapted from the functions in RFC1321\n" ,
   "  by R Rivest, and so are derived from the RSA Data Security, Inc MD5\n" ,
   "  Message-Digest Algorithm.  See file \"thd_md5.c\" for the RSA Copyright\n" ,
   "  notice.\n" ,
   "\n" ,
   "  The SVM-light software included is by Thorsten Joachims of Cornell\n" ,
   "  University, and is redistributed in the AFNI package by permission.\n" ,
   "  If you use this software, please cite the paper\n" ,
   "      T. Joachims, Making large-Scale SVM Learning Practical.\n" ,
   "        Advances in Kernel Methods - Support Vector Learning,\n" ,
   "        B. Scholkopf and C. Burges and A. Smola (ed.), MIT-Press, 1999. \n" ,
   "  The SVM-light software is free ONLY for non-commercial use. It must not be\n" ,
   "  distributed without prior permission of the author. The author is not\n" ,
   "  responsible for implications from the use of this software.\n" ,
   "\n" ,
   "  The sonnets of William Shakespeare are not copyrighted.  At that time --\n" ,
   "  the most creative literary period in history -- there was no copyright.\n" ,
   "  Whoever says that copyright is NECESSARY to ensure artistic and/or\n" ,
   "  intellectual creativity should explain this historical fact.\n" ,
   "\n" ,
   "  ============================================================================\n" ,
   "\n" ,
   "                         GNU GENERAL PUBLIC LICENSE\n" ,
   "                            Version 2, June 1991\n" ,
   "\n" ,
   "  Copyright (C) 1989, 1991 Free Software Foundation, Inc. 675 Mass\n" ,
   "  Ave, Cambridge, MA 02139, USA. Everyone is permitted to copy and\n" ,
   "  distribute verbatim copies of this license document, but changing it\n" ,
   "  is not allowed.\n" ,
   "\n" ,
   "                                Preamble\n" ,
   "\n" ,
   "  The licenses for most software are designed to take away your\n" ,
   "  freedom to share and change it. By contrast, the GNU General Public\n" ,
   "  License is intended to guarantee your freedom to share and change\n" ,
   "  free software--to make sure the software is free for all its users.\n" ,
   "  This General Public License applies to most of the Free Software\n" ,
   "  Foundation's software and to any other program whose authors commit\n" ,
   "  to using it. (Some other Free Software Foundation software is\n" ,
   "  covered by the GNU Library General Public License instead.) You can\n" ,
   "  apply it to your programs, too.\n" ,
   "\n" ,
   "  When we speak of free software, we are referring to freedom, not\n" ,
   "  price. Our General Public Licenses are designed to make sure that\n" ,
   "  you have the freedom to distribute copies of free software (and\n" ,
   "  charge for this service if you wish), that you receive source code\n" ,
   "  or can get it if you want it, that you can change the software or\n" ,
   "  use pieces of it in new free programs; and that you know you can do\n" ,
   "  these things.\n" ,
   "\n" ,
   "  To protect your rights, we need to make restrictions that forbid\n" ,
   "  anyone to deny you these rights or to ask you to surrender the\n" ,
   "  rights. These restrictions translate to certain responsibilities for\n" ,
   "  you if you distribute copies of the software, or if you modify it.\n" ,
   "\n" ,
   "  For example, if you distribute copies of such a program, whether\n" ,
   "  gratis or for a fee, you must give the recipients all the rights\n" ,
   "  that you have. You must make sure that they, too, receive or can get\n" ,
   "  the source code. And you must show them these terms so they know\n" ,
   "  their rights.\n" ,
   "\n" ,
   "  We protect your rights with two steps: (1) copyright the software,\n" ,
   "  and (2) offer you this license which gives you legal permission to\n" ,
   "  copy, distribute and/or modify the software.\n" ,
   "\n" ,
   "  Also, for each author's protection and ours, we want to make certain\n" ,
   "  that everyone understands that there is no warranty for this free\n" ,
   "  software. If the software is modified by someone else and passed on,\n" ,
   "  we want its recipients to know that what they have is not the\n" ,
   "  original, so that any problems introduced by others will not reflect\n" ,
   "  on the original authors' reputations.\n" ,
   "\n" ,
   "  Finally, any free program is threatened constantly by software\n" ,
   "  patents. We wish to avoid the danger that redistributors of a free\n" ,
   "  program will individually obtain patent licenses, in effect making\n" ,
   "  the program proprietary. To prevent this, we have made it clear that\n" ,
   "  any patent must be licensed for everyone's free use or not licensed\n" ,
   "  at all.\n" ,
   "\n" ,
   "  The precise terms and conditions for copying, distribution and\n" ,
   "  modification follow.\n" ,
   "\n" ,
   "                       GNU GENERAL PUBLIC LICENSE\n" ,
   "    TERMS AND CONDITIONS FOR COPYING, DISTRIBUTION AND MODIFICATION\n" ,
   "\n" ,
   "  0. This License applies to any program or other work which contains\n" ,
   "  a notice placed by the copyright holder saying it may be distributed\n" ,
   "  under the terms of this General Public License. The \"Program\",\n" ,
   "  below, refers to any such program or work, and a \"work based on the\n" ,
   "  Program\" means either the Program or any derivative work under\n" ,
   "  copyright law: that is to say, a work containing the Program or a\n" ,
   "  portion of it, either verbatim or with modifications and/or\n" ,
   "  translated into another language. (Hereinafter, translation is\n" ,
   "  included without limitation in the term \"modification\".) Each\n" ,
   "  licensee is addressed as \"you\".\n" ,
   "\n" ,
   "  Activities other than copying, distribution and modification are not\n" ,
   "  covered by this License; they are outside its scope. The act of\n" ,
   "  running the Program is not restricted, and the output from the\n" ,
   "  Program is covered only if its contents constitute a work based on\n" ,
   "  the Program (independent of having been made by running the\n" ,
   "  Program). Whether that is true depends on what the Program does.\n" ,
   "\n" ,
   "  1. You may copy and distribute verbatim copies of the Program's\n" ,
   "  source code as you receive it, in any medium, provided that you\n" ,
   "  conspicuously and appropriately publish on each copy an appropriate\n" ,
   "  copyright notice and disclaimer of warranty; keep intact all the\n" ,
   "  notices that refer to this License and to the absence of any\n" ,
   "  warranty; and give any other recipients of the Program a copy of\n" ,
   "  this License along with the Program.\n" ,
   "\n" ,
   "  You may charge a fee for the physical act of transferring a copy,\n" ,
   "  and you may at your option offer warranty protection in exchange for\n" ,
   "  a fee.\n" ,
   "\n" ,
   "  2. You may modify your copy or copies of the Program or any portion\n" ,
   "  of it, thus forming a work based on the Program, and copy and\n" ,
   "  distribute such modifications or work under the terms of Section 1\n" ,
   "  above, provided that you also meet all of these conditions:\n" ,
   "\n" ,
   "  a) You must cause the modified files to carry prominent notices\n" ,
   "  stating that you changed the files and the date of any change.\n" ,
   "\n" ,
   "  b) You must cause any work that you distribute or publish, that in\n" ,
   "  whole or in part contains or is derived from the Program or any part\n" ,
   "  thereof, to be licensed as a whole at no charge to all third parties\n" ,
   "  under the terms of this License.\n" ,
   "\n" ,
   "  c) If the modified program normally reads commands interactively\n" ,
   "  when run, you must cause it, when started running for such\n" ,
   "  interactive use in the most ordinary way, to print or display an\n" ,
   "  announcement including an appropriate copyright notice and a notice\n" ,
   "  that there is no warranty (or else, saying that you provide a\n" ,
   "  warranty) and that users may redistribute the program under these\n" ,
   "  conditions, and telling the user how to view a copy of this License.\n" ,
   "  (Exception: if the Program itself is interactive but does not\n" ,
   "  normally print such an announcement, your work based on the Program\n" ,
   "  is not required to print an announcement.)\n" ,
   "\n" ,
   "  These requirements apply to the modified work as a whole. If\n" ,
   "  identifiable sections of that work are not derived from the Program,\n" ,
   "  and can be reasonably considered independent and separate works in\n" ,
   "  themselves, then this License, and its terms, do not apply to those\n" ,
   "  sections when you distribute them as separate works. But when you\n" ,
   "  distribute the same sections as part of a whole which is a work\n" ,
   "  based on the Program, the distribution of the whole must be on the\n" ,
   "  terms of this License, whose permissions for other licensees extend\n" ,
   "  to the entire whole, and thus to each and every part regardless of\n" ,
   "  who wrote it.\n" ,
   "\n" ,
   "  Thus, it is not the intent of this section to claim rights or\n" ,
   "  contest your rights to work written entirely by you; rather, the\n" ,
   "  intent is to exercise the right to control the distribution of\n" ,
   "  derivative or collective works based on the Program.\n" ,
   "\n" ,
   "  In addition, mere aggregation of another work not based on the\n" ,
   "  Program with the Program (or with a work based on the Program) on a\n" ,
   "  volume of a storage or distribution medium does not bring the other\n" ,
   "  work under the scope of this License.\n" ,
   "\n" ,
   "  3. You may copy and distribute the Program (or a work based on it,\n" ,
   "  under Section 2) in object code or executable form under the terms\n" ,
   "  of Sections 1 and 2 above provided that you also do one of the\n" ,
   "  following:\n" ,
   "\n" ,
   "  a) Accompany it with the complete corresponding machine-readable\n" ,
   "  source code, which must be distributed under the terms of Sections 1\n" ,
   "  and 2 above on a medium customarily used for software interchange;\n" ,
   "  or,\n" ,
   "\n" ,
   "  b) Accompany it with a written offer, valid for at least three\n" ,
   "  years, to give any third party, for a charge no more than your cost\n" ,
   "  of physically performing source distribution, a complete\n" ,
   "  machine-readable copy of the corresponding source code, to be\n" ,
   "  distributed under the terms of Sections 1 and 2 above on a medium\n" ,
   "  customarily used for software interchange; or,\n" ,
   "\n" ,
   "  c) Accompany it with the information you received as to the offer to\n" ,
   "  distribute corresponding source code. (This alternative is allowed\n" ,
   "  only for noncommercial distribution and only if you received the\n" ,
   "  program in object code or executable form with such an offer, in\n" ,
   "  accord with Subsection b above.)\n" ,
   "\n" ,
   "  The source code for a work means the preferred form of the work for\n" ,
   "  making modifications to it. For an executable work, complete source\n" ,
   "  code means all the source code for all modules it contains, plus any\n" ,
   "  associated interface definition files, plus the scripts used to\n" ,
   "  control compilation and installation of the executable. However, as\n" ,
   "  a special exception, the source code distributed need not include\n" ,
   "  anything that is normally distributed (in either source or binary\n" ,
   "  form) with the major components (compiler, kernel, and so on) of the\n" ,
   "  operating system on which the executable runs, unless that component\n" ,
   "  itself accompanies the executable.\n" ,
   "\n" ,
   "  If distribution of executable or object code is made by offering\n" ,
   "  access to copy from a designated place, then offering equivalent\n" ,
   "  access to copy the source code from the same place counts as\n" ,
   "  distribution of the source code, even though third parties are not\n" ,
   "  compelled to copy the source along with the object code.\n" ,
   "\n" ,
   "  4. You may not copy, modify, sublicense, or distribute the Program\n" ,
   "  except as expressly provided under this License. Any attempt\n" ,
   "  otherwise to copy, modify, sublicense or distribute the Program is\n" ,
   "  void, and will automatically terminate your rights under this\n" ,
   "  License. However, parties who have received copies, or rights, from\n" ,
   "  you under this License will not have their licenses terminated so\n" ,
   "  long as such parties remain in full compliance.\n" ,
   "\n" ,
   "  5. You are not required to accept this License, since you have not\n" ,
   "  signed it. However, nothing else grants you permission to modify or\n" ,
   "  distribute the Program or its derivative works. These actions are\n" ,
   "  prohibited by law if you do not accept this License. Therefore, by\n" ,
   "  modifying or distributing the Program (or any work based on the\n" ,
   "  Program), you indicate your acceptance of this License to do so, and\n" ,
   "  all its terms and conditions for copying, distributing or modifying\n" ,
   "  the Program or works based on it.\n" ,
   "\n" ,
   "  6. Each time you redistribute the Program (or any work based on the\n" ,
   "  Program), the recipient automatically receives a license from the\n" ,
   "  original licensor to copy, distribute or modify the Program subject\n" ,
   "  to these terms and conditions. You may not impose any further\n" ,
   "  restrictions on the recipients' exercise of the rights granted\n" ,
   "  herein. You are not responsible for enforcing compliance by third\n" ,
   "  parties to this License.\n" ,
   "\n" ,
   "  7. If, as a consequence of a court judgment or allegation of patent\n" ,
   "  infringement or for any other reason (not limited to patent issues),\n" ,
   "  conditions are imposed on you (whether by court order, agreement or\n" ,
   "  otherwise) that contradict the conditions of this License, they do\n" ,
   "  not excuse you from the conditions of this License. If you cannot\n" ,
   "  distribute so as to satisfy simultaneously your obligations under\n" ,
   "  this License and any other pertinent obligations, then as a\n" ,
   "  consequence you may not distribute the Program at all. For example,\n" ,
   "  if a patent license would not permit royalty-free redistribution of\n" ,
   "  the Program by all those who receive copies directly or indirectly\n" ,
   "  through you, then the only way you could satisfy both it and this\n" ,
   "  License would be to refrain entirely from distribution of the\n" ,
   "  Program.\n" ,
   "\n" ,
   "  If any portion of this section is held invalid or unenforceable\n" ,
   "  under any particular circumstance, the balance of the section is\n" ,
   "  intended to apply and the section as a whole is intended to apply in\n" ,
   "  other circumstances.\n" ,
   "\n" ,
   "  It is not the purpose of this section to induce you to infringe any\n" ,
   "  patents or other property right claims or to contest validity of any\n" ,
   "  such claims; this section has the sole purpose of protecting the\n" ,
   "  integrity of the free software distribution system, which is\n" ,
   "  implemented by public license practices. Many people have made\n" ,
   "  generous contributions to the wide range of software distributed\n" ,
   "  through that system in reliance on consistent application of that\n" ,
   "  system; it is up to the author/donor to decide if he or she is\n" ,
   "  willing to distribute software through any other system and a\n" ,
   "  licensee cannot impose that choice.\n" ,
   "\n" ,
   "  This section is intended to make thoroughly clear what is believed\n" ,
   "  to be a consequence of the rest of this License.\n" ,
   "\n" ,
   "  8. If the distribution and/or use of the Program is restricted in\n" ,
   "  certain countries either by patents or by copyrighted interfaces,\n" ,
   "  the original copyright holder who places the Program under this\n" ,
   "  License may add an explicit geographical distribution limitation\n" ,
   "  excluding those countries, so that distribution is permitted only in\n" ,
   "  or among countries not thus excluded. In such case, this License\n" ,
   "  incorporates the limitation as if written in the body of this\n" ,
   "  License.\n" ,
   "\n" ,
   "  9. The Free Software Foundation may publish revised and/or new\n" ,
   "  versions of the General Public License from time to time. Such new\n" ,
   "  versions will be similar in spirit to the present version, but may\n" ,
   "  differ in detail to address new problems or concerns.\n" ,
   "\n" ,
   "  Each version is given a distinguishing version number. If the\n" ,
   "  Program specifies a version number of this License which applies to\n" ,
   "  it and \"any later version\", you have the option of following the\n" ,
   "  terms and conditions either of that version or of any later version\n" ,
   "  published by the Free Software Foundation. If the Program does not\n" ,
   "  specify a version number of this License, you may choose any version\n" ,
   "  ever published by the Free Software Foundation.\n" ,
   "\n" ,
   "  10. If you wish to incorporate parts of the Program into other free\n" ,
   "  programs whose distribution conditions are different, write to the\n" ,
   "  author to ask for permission. For software which is copyrighted by\n" ,
   "  the Free Software Foundation, write to the Free Software Foundation;\n" ,
   "  we sometimes make exceptions for this. Our decision will be guided\n" ,
   "  by the two goals of preserving the free status of all derivatives of\n" ,
   "  our free software and of promoting the sharing and reuse of software\n" ,
   "  generally.\n" ,
   "\n" ,
   "                              NO WARRANTY\n" ,
   "\n" ,
   "  11. BECAUSE THE PROGRAM IS LICENSED FREE OF CHARGE, THERE IS NO\n" ,
   "  WARRANTY FOR THE PROGRAM, TO THE EXTENT PERMITTED BY APPLICABLE LAW.\n" ,
   "  EXCEPT WHEN OTHERWISE STATED IN WRITING THE COPYRIGHT HOLDERS AND/OR\n" ,
   "  OTHER PARTIES PROVIDE THE PROGRAM \"AS IS\" WITHOUT WARRANTY OF ANY\n" ,
   "  KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO,\n" ,
   "  THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A\n" ,
   "  PARTICULAR PURPOSE. THE ENTIRE RISK AS TO THE QUALITY AND\n" ,
   "  PERFORMANCE OF THE PROGRAM IS WITH YOU. SHOULD THE PROGRAM PROVE\n" ,
   "  DEFECTIVE, YOU ASSUME THE COST OF ALL NECESSARY SERVICING, REPAIR OR\n" ,
   "  CORRECTION.\n" ,
   "\n" ,
   "  12. IN NO EVENT UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO IN\n" ,
   "  WRITING WILL ANY COPYRIGHT HOLDER, OR ANY OTHER PARTY WHO MAY MODIFY\n" ,
   "  AND/OR REDISTRIBUTE THE PROGRAM AS PERMITTED ABOVE, BE LIABLE TO YOU\n" ,
   "  FOR DAMAGES, INCLUDING ANY GENERAL, SPECIAL, INCIDENTAL OR\n" ,
   "  CONSEQUENTIAL DAMAGES ARISING OUT OF THE USE OR INABILITY TO USE THE\n" ,
   "  PROGRAM (INCLUDING BUT NOT LIMITED TO LOSS OF DATA OR DATA BEING\n" ,
   "  RENDERED INACCURATE OR LOSSES SUSTAINED BY YOU OR THIRD PARTIES OR A\n" ,
   "  FAILURE OF THE PROGRAM TO OPERATE WITH ANY OTHER PROGRAMS), EVEN IF\n" ,
   "  SUCH HOLDER OR OTHER PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF\n" ,
   "  SUCH DAMAGES.\n" ,
   "\n" ,
   "                      END OF TERMS AND CONDITIONS\n" ,
   "\n" ,
   "  ============================================================================\n" ,
   "\n" ,
   "                           OpenContent License (OPL)\n" ,
   "                           Version 1.0, July 14, 1998.\n" ,
   "\n" ,
   "     This document outlines the principles underlying the OpenContent\n" ,
   "     (OC) movement and may be redistributed provided it remains\n" ,
   "     unaltered. For legal purposes, this document is the license under\n" ,
   "     which OpenContent is made available for use.\n" ,
   "\n" ,
   "     The original version of this document may be found at\n" ,
   "     http://opencontent.org/opl.shtml\n" ,
   "\n" ,
   "     LICENSE\n" ,
   "\n" ,
   "     Terms and Conditions for Copying, Distributing, and Modifying\n" ,
   "\n" ,
   "     Items other than copying, distributing, and modifying the Content\n" ,
   "     with which this license was distributed (such as using, etc.) are\n" ,
   "     outside the scope of this license.\n" ,
   "\n" ,
   "     1. You may copy and distribute exact replicas of the OpenContent\n" ,
   "     (OC) as you receive it, in any medium, provided that you\n" ,
   "     conspicuously and appropriately publish on each copy an appropriate\n" ,
   "     copyright notice and disclaimer of warranty; keep intact all the\n" ,
   "     notices that refer to this License and to the absence of any\n" ,
   "     warranty; and give any other recipients of the OC a copy of this\n" ,
   "     License along with the OC. You may at your option charge a fee for\n" ,
   "     the media and/or handling involved in creating a unique copy of the\n" ,
   "     OC for use offline, you may at your option offer instructional\n" ,
   "     support for the OC in exchange for a fee, or you may at your option\n" ,
   "     offer warranty in exchange for a fee. You may not charge a fee for\n" ,
   "     the OC itself. You may not charge a fee for the sole service of\n" ,
   "     providing access to and/or use of the OC via a network (e.g. the\n" ,
   "     Internet), whether it be via the world wide web, FTP, or any other\n" ,
   "     method.\n" ,
   "\n" ,
   "     2. You may modify your copy or copies of the OpenContent or any\n" ,
   "     portion of it, thus forming works based on the Content, and\n" ,
   "     distribute such modifications or work under the terms of Section 1\n" ,
   "     above, provided that you also meet all of these conditions:\n" ,
   "\n" ,
   "     a) You must cause the modified content to carry prominent notices\n" ,
   "     stating that you changed it, the exact nature and content of the\n" ,
   "     changes, and the date of any change.\n" ,
   "\n" ,
   "     b) You must cause any work that you distribute or publish, that in\n" ,
   "     whole or in part contains or is derived from the OC or any part\n" ,
   "     thereof, to be licensed as a whole at no charge to all third\n" ,
   "     parties under the terms of this License, unless otherwise permitted\n" ,
   "     under applicable Fair Use law.\n" ,
   "\n" ,
   "     These requirements apply to the modified work as a whole. If\n" ,
   "     identifiable sections of that work are not derived from the OC, and\n" ,
   "     can be reasonably considered independent and separate works in\n" ,
   "     themselves, then this License, and its terms, do not apply to those\n" ,
   "     sections when you distribute them as separate works. But when you\n" ,
   "     distribute the same sections as part of a whole which is a work\n" ,
   "     based on the OC, the distribution of the whole must be on the terms\n" ,
   "     of this License, whose permissions for other licensees extend to\n" ,
   "     the entire whole, and thus to each and every part regardless of who\n" ,
   "     wrote it. Exceptions are made to this requirement to release\n" ,
   "     modified works free of charge under this license only in compliance\n" ,
   "     with Fair Use law where applicable.\n" ,
   "\n" ,
   "     3. You are not required to accept this License, since you have not\n" ,
   "     signed it. However, nothing else grants you permission to copy,\n" ,
   "     distribute or modify the OC. These actions are prohibited by law if\n" ,
   "     you do not accept this License. Therefore, by distributing or\n" ,
   "     translating the OC, or by deriving works herefrom, you indicate\n" ,
   "     your acceptance of this License to do so, and all its terms and\n" ,
   "     conditions for copying, distributing or translating the OC.\n" ,
   "\n" ,
   "     NO WARRANTY\n" ,
   "\n" ,
   "     4. BECAUSE THE OPENCONTENT (OC) IS LICENSED FREE OF CHARGE, THERE\n" ,
   "     IS NO WARRANTY FOR THE OC, TO THE EXTENT PERMITTED BY APPLICABLE\n" ,
   "     LAW. EXCEPT WHEN OTHERWISE STATED IN WRITING THE COPYRIGHT HOLDERS\n" ,
   "     AND/OR OTHER PARTIES PROVIDE THE OC \"AS IS\" WITHOUT WARRANTY OF ANY\n" ,
   "     KIND, EITHER EXPRESSED OR IMPLIED, INCLUDING, BUT NOT LIMITED TO,\n" ,
   "     THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A\n" ,
   "     PARTICULAR PURPOSE. THE ENTIRE RISK OF USE OF THE OC IS WITH YOU.\n" ,
   "     SHOULD THE OC PROVE FAULTY, INACCURATE, OR OTHERWISE UNACCEPTABLE\n" ,
   "     YOU ASSUME THE COST OF ALL NECESSARY REPAIR OR CORRECTION.\n" ,
   "\n" ,
   "     5. IN NO EVENT UNLESS REQUIRED BY APPLICABLE LAW OR AGREED TO IN\n" ,
   "     WRITING WILL ANY COPYRIGHT HOLDER, OR ANY OTHER PARTY WHO MAY\n" ,
   "     MIRROR AND/OR REDISTRIBUTE THE OC AS PERMITTED ABOVE, BE LIABLE TO\n" ,
   "     YOU FOR DAMAGES, INCLUDING ANY GENERAL, SPECIAL, INCIDENTAL OR\n" ,
   "     CONSEQUENTIAL DAMAGES ARISING OUT OF THE USE OR INABILITY TO USE\n" ,
   "     THE OC, EVEN IF SUCH HOLDER OR OTHER PARTY HAS BEEN ADVISED OF THE\n" ,
   "     POSSIBILITY OF SUCH DAMAGES.\n" ,
   "\n" ,
   NULL } ;
