static char * newstuff[] = {
   "\n" ,
   "   *****************************************************************\n" ,
   "   * Changes to the AFNI package that are not in the manuals (yet) *\n" ,
   "   *****************************************************************\n" ,
   "\n" ,
   "--------------------------------------------------------------------------\n" ,
   "16 Nov 1998:\n" ,
   "   3D (volumetric) registration is now available in the '3dvolreg' program\n" ,
   "     and the corresponding '3D Registration' plugin.\n" ,
   "   The dataset 'Lock' feature now allows you to lock the time indexes\n" ,
   "     of datasets together, as well as the 3D spatial coordinates.\n" ,
   "   Program 'cdf' allows you to do various statistical conversions from\n" ,
   "     the probability distributions known to AFNI.\n" ,
   "   Program '3dTcat' allows you to catenate 3D+time datasets together to\n" ,
   "     form really BIG data files, if you are so inclined.\n" ,
   "   You can set the Unix environment variable 'AFNI_LEFT_IS_LEFT' so that\n" ,
   "     axial and coronal images display with the subject's left on the\n" ,
   "     left of the screen, instead of the default radiological convention.\n" ,
   "--------------------------------------------------------------------------\n" ,
   "14 Sep 1998:\n" ,
   "   The new '3dDeconvolve' program is available to perform multiple linear\n" ,
   "     regression and linear deconvolution on 3D+time datasets.  See the\n" ,
   "     file 3dDeconvolve.ps for documentation and examples.\n" ,
   "--------------------------------------------------------------------------\n" ,
   "22 Aug 1998:\n" ,
   "   Experimental support for X11 TrueColor visuals has been implemented.\n" ,
   "     In this context, 'experimental' means that if it becomes too much\n" ,
   "     of a bother to make work right, this feature will be axed.\n" ,
   "--------------------------------------------------------------------------\n" ,
   "17 Aug 1998:\n" ,
   "   The 'Plot' feature in the timeseries chooser has finally been\n" ,
   "     implemented (after a wait of about 2 years).  Break out the\n" ,
   "     pumpernickel bagels!\n" ,
   "--------------------------------------------------------------------------\n" ,
   "08 Aug 1998:\n" ,
   "   Added ability to plot Points+Lines together in the graphing windows.\n" ,
   "   Modified 3dmaskave and plug_maskave to allow user to choose a sub-brick\n" ,
   "     of the mask dataset.  The plugin also now allows you to save an\n" ,
   "     average time series to the internal AFNI 'library', where it can be\n" ,
   "     used as the ideal waveform for FIM.\n" ,
   "   Added nonlinear fit model 'model_convgamma', that models the data\n" ,
   "     time series as a gamma variate impulse response convolved with a\n" ,
   "     reference time series.\n" ,
   "   Nonlinear fit programs 3dNLfim and plug_nlfit have a new option to allow\n" ,
   "     the time step of the model function to be set to the time step of the\n" ,
   "     input dataset (default is to set delta-t=1.0, regardless of true TR).\n" ,
   "--------------------------------------------------------------------------\n" ,
   "14 July 1998:\n" ,
   "   3dmerge now has options (-1erode and -1dilate) to apply erosion and\n" ,
   "     dilation to a dataset when clustering it, so as to cut off small\n" ,
   "     'necks' that connect larger blobs.  See the new file 3dmerge.ps\n" ,
   "     for more documentation.\n" ,
   "--------------------------------------------------------------------------\n" ,
   "15 June 1998:\n" ,
   "   3dmerge now has an option (-1clust_order) to assign distinct index\n" ,
   "     values to each cluster.  This can be used to create masks, or simply\n" ,
   "     to be able to visually distinguish separate clusters.\n" ,
   "--------------------------------------------------------------------------\n" ,
   "30 April 1998:\n" ,
   "   3dcalc can now correctly operate on 3D bucket and other multi-brick\n" ,
   "     non-time-dependent datasets.\n" ,
   "   3drefit can convert a 3D+time dataset to a 3D bucket dataset (but\n" ,
   "     not vice-versa).\n" ,
   "--------------------------------------------------------------------------\n" ,
   "25 April 1998:\n" ,
   "   AFNI now can store the byte order for short-valued datasets in the\n" ,
   "     .HEAD file.  It will then compare that order to the CPU order,\n" ,
   "     and if necessary, swap the bytes as it read the .BRIK file into\n" ,
   "     memory.  This is intended to make it simpler to use AFNI datasets\n" ,
   "     in a clustered enviroment with different types of computers.\n" ,
   "   Plugin 'ROI Average' does pretty much the same thing as program\n" ,
   "     3dmaskave, so that you can now get ROI statistics interactively.\n" ,
   "   Program '3dcalc' can now take as input a time series file '*.1D'\n" ,
   "     in place of a dataset.  This is treated as a 3D+time dataset with\n" ,
   "     all the voxel values at a given time being identical.  See the\n" ,
   "     output of '3dcalc -help' for more details.\n" ,
   "--------------------------------------------------------------------------\n" ,
   "20 March 1998:\n" ,
   "   Program '3dmaskave' can produce statistics of a VOI from within a\n" ,
   "     dataset, using a mask dataset created by the Draw Dataset plugin.\n" ,
   "   Program '3dbuc2fim' can create fim, fico, etc., datasets from a\n" ,
   "     bucket dataset.  This can be used with programs (such as 3dmerge)\n" ,
   "     that don't support bucket dataset inputs at this time.\n" ,
   "   Program 2dImReg has been modified to allow printout of the estimated\n" ,
   "     motion parameters.\n" ,
   "--------------------------------------------------------------------------\n" ,
   "16 March 1998:\n" ,
   "   'afni -im' will now perform internal globbing of filenames -- that is,\n" ,
   "     it can do wildcard expansion itself.  For example:\n" ,
   "        afni -im '3D:-1:0:256:256:1:I.*'\n" ,
   "     will use the 3D: format to read a bunch of 256x256 images from files\n" ,
   "     named I.001, I.002, etc.  See the output of \"to3d -help\" for more\n" ,
   "     details about the globbing feature.\n" ,
   "   Bucket type \"follower\" datasets created applying the Talairach warp\n" ,
   "     of an anatomical parent to a dataset will now properly keep their\n" ,
   "     data parent's sub-brick labels, etc.\n" ,
   "--------------------------------------------------------------------------\n" ,
   "13 February 1998:\n" ,
   "   The new plugin \"Draw Dataset\" offers a way to interactively edit the\n" ,
   "     values inside a dataset.  It is intended to allow the creation of\n" ,
   "     Volume-of-Interest (VOI) mask datasets.  The only documentation is\n" ,
   "     the 'Help' button within the plugin.  Yet to come -- tools to use\n" ,
   "     VOIs in conjunction with other datasets.  See README.roi for more\n" ,
   "     information.\n" ,
   "   The new 'bucket' type of dataset allows an arbitrary number of\n" ,
   "     sub-bricks to be attached to a 3D dataset.  AFNI allows you to\n" ,
   "     display any given sub-brick from a bucket dataset.  The 3D dataset\n" ,
   "     statistics programs (3dANOVA, etc.) have been modified to output\n" ,
   "     their results into bucket datasets, so that the results of complex\n" ,
   "     analyses can be encapsulated into a single convenient package.\n" ,
   "   The new FIM+ option within AFNI allows computation of a bucket dataset\n" ,
   "     output from the correlation analysis, with percent change included\n" ,
   "     as a new sub-brick.\n" ,
   "   The 'plugout' facility has been extended somewhat, and a couple of\n" ,
   "     new sample plugout programs are included with AFNI 2.20.\n" ,
   "--------------------------------------------------------------------------\n" ,
   "11 February 1998:\n" ,
   "   AFNI (and other programs) will now also write compressed .BRIK files.\n" ,
   "     This is controlled by the environment variable AFNI_COMPRESSOR.\n" ,
   "     The output compression mode can also be set using the new\n" ,
   "     \"BRIK Compressor\" plugin. See README.compression for the details.\n" ,
   "--------------------------------------------------------------------------\n" ,
   "04 February 1998:\n" ,
   "   AFNI will now select a scale for graphs when it first opens a graph\n" ,
   "     window.  It didn't used to do this, which made things confusing.\n" ,
   "     Also, you can have the auto-scaling redone at any time by using\n" ,
   "     a new button on the Opt->Scale menu, or by typing 'a' in the graph.\n" ,
   "   Sub-graphs can now be spaced apart into separate boxes.  The size\n" ,
   "     of the gap is chosen from the Opt->Colors menu.\n" ,
   "   Graphs can be drawn in symbols, also chosen from the Opt->Colors menu.\n" ,
   "   Graphs can have the x-axis be chosen to be proportional to an arbitrary\n" ,
   "     time series, rather than always be proportional to the time index.\n" ,
   "     This can be used to make a scatterplot of all voxels vs. a given\n" ,
   "     voxel, for example.\n" ,
   "   Graph windows now show the (x,y,z) voxel indices in the same convention\n" ,
   "     that the AFNI controller window uses if the \"Voxel Coords?\" button\n" ,
   "     is toggled on the \"Misc\" menu.  [Per the request of MS Beauchamp.]\n" ,
   "   If AFNI is compiled with the -DUSE_TRACING option, then the program\n" ,
   "     will keep track of the routines as they are called.  If a crash\n" ,
   "     occurs, AFNI will attempt to print out the location at which it died.\n" ,
   "   The FIM menu now has an option to allow computation of the percent\n" ,
   "     signal change.\n" ,
   "--------------------------------------------------------------------------\n" ,
   "05 January 1998:\n" ,
   "   AFNI will now read compressed .BRIK files.  Programs gzip, compress, or\n" ,
   "     bzip2 can be used for the compressor.  AFNI will not write out such\n" ,
   "     compressed files -- you have to do this manually.  See the file\n" ,
   "     README.compression for the details.\n" ,
   "   AFNI can now read/write colors and palettes for the functional\n" ,
   "     overlay \"pbar\" from setup files.  The file $(HOME)/.afnirc will\n" ,
   "     be read on startup, if it exists.  (This file can be used to do most\n" ,
   "     of what is described under \".Xdefaults\" far below.)  A popup menu is\n" ,
   "     hidden under the label on top of the color pbar.  See the file\n" ,
   "     README.setup for the details.\n" ,
   "--------------------------------------------------------------------------\n" ,
   "18 December 1997:\n" ,
   "   Added -noqual option to AFNI to make it skip quality checks when doing\n" ,
   "      marker transformations.\n" ,
   "   Added -view option to 3drefit to let it change coordinate systems.\n" ,
   "--------------------------------------------------------------------------\n" ,
   "09 December 1997:\n" ,
   "   Added a new chooser to let user pick interpolation method for threshold\n" ,
   "      (statistical) sub-bricks.\n" ,
   "   Removed FIM menu from Define Function control panel.\n" ,
   "--------------------------------------------------------------------------\n" ,
   "21 November 1997:\n" ,
   "   In to3d, added the ability to specify brick dimensions on the command\n" ,
   "     line using either form \"120A\" or \"A120\".  This is to make to3d\n" ,
   "     consistent with the way that some scanners print slice locations\n" ,
   "     on film.\n" ,
   "--------------------------------------------------------------------------\n" ,
   "06 November 1997:\n" ,
   "   Added program 3dRegAna to perform linear regression analysis on\n" ,
   "     voxels across multiple 3D datasets.  This could be used to detect\n" ,
   "     trends in activation data with some stimulus parameter, for example.\n" ,
   "     See the file 3dRegAna.ps (in doc.tgz) for more information.\n" ,
   "   [By BD Ward of MCW.]\n" ,
   "--------------------------------------------------------------------------\n" ,
   "30 October 1997:\n" ,
   "   Added popup \"hints\" to AFNI controls.  See the file README.environment\n" ,
   "     for information on how to turn them on and off.  These may also\n" ,
   "     be attached to plugins -- see plug_stats.c for an example.\n" ,
   "--------------------------------------------------------------------------\n" ,
   "06 October 1997:\n" ,
   "   Fixed a bug in the registration code that produced somewhat less than\n" ,
   "     optimal fits.  This affects imreg, fim2, and plug_imreg.\n" ,
   "   [Modified by BD Ward of MCW.]\n" ,
   "--------------------------------------------------------------------------\n" ,
   "04 September 1997:\n" ,
   "   Some Sun workstations don't have the standard library routine \"rand\"\n" ,
   "     working properly, it seems.  All the programs that use \"rand\" have\n" ,
   "     had that replaced with the \"rand48\" series of routines.\n" ,
   "   [Modified by BD Ward and RW Cox of MCW.]\n" ,
   "--------------------------------------------------------------------------\n" ,
   "22 August 1997:\n" ,
   "   3dcalc has been modified to allow processing of 3D+time datasets.\n" ,
   "     Also, it has been made more efficient (2-4 times as fast, in some\n" ,
   "     quick tests here at MCW).\n" ,
   "   [Modified by Raoquiong Tong of MCW.]\n" ,
   "--------------------------------------------------------------------------\n" ,
   "01 August 1997:\n" ,
   "   A label showing the values of the Anatomy, Function, and Threshold\n" ,
   "     at the crosshair point was added at the bottom of the rightmost\n" ,
   "     column in the \"Define Function\" control panel.  This label is\n" ,
   "     only active when all three viewing windows are open at once.\n" ,
   "     (This is due to the way that AFNI accesses data bricks.)\n" ,
   "\n" ,
   "   The number of levels of filename displayed in the \"Switch Session\"\n" ,
   "     chooser is now controllable with the new AFNI_SESSTRAIL environment\n" ,
   "     variable.  See the file README.environment for details.\n" ,
   "     [Both changes per the request of Paul Reber of UCSD.]\n" ,
   "--------------------------------------------------------------------------\n" ,
   "29 July 1997:\n" ,
   "   The new command-line program \"3drefit\" allows you to change some of\n" ,
   "     the values stored inside a 3D dataset's .HEAD file.  This makes it\n" ,
   "     easier to fix up mistakes made with to3d, or simply to experiment.\n" ,
   "     Type \"3drefit -help\" to get the list of command line options.\n" ,
   "     [Per the request of Sandy Kindermann at UCSD.]\n" ,
   "\n" ,
   "   AFNI now allows you to control the order in which coordinates are\n" ,
   "     displayed in the main control window (upper left) and in the\n" ,
   "     output of 3dclust.  This is done with the new \"-orient\" option,\n" ,
   "     or can be set with the Unix environment variable AFNI_ORIENT.\n" ,
   "     The new file \"README.environment\" documents how to use this feature.\n" ,
   "     Several other Unix environment variables that can affect AFNI are\n" ,
   "     also described therein.\n" ,
   "\n" ,
   "   The new programs \"3dFriedman\", \"3dKruskalWallis\", \"3dMannWhitney\", and\n" ,
   "     \"3dWilcoxon\" have been added to the package by Doug Ward.  PostScript\n" ,
   "     documentation is in the file \"Nonparametric.ps\".  These programs\n" ,
   "     perform voxelwise nonparametric statistics on collections of 3D\n" ,
   "     datasets.  They are intended to complement and provide alternatives\n" ,
   "     to the existing parametric programs 3dttest and 3dANOVA*.\n" ,
   "------------------------------------------------------------------------\n" ,
   "25 June 1997:\n" ,
   "   The color \"pbar\" used to control the mapping from function value to\n" ,
   "     color overlay has been extended to allow up to 20 different colors\n" ,
   "     to be used at once.\n" ,
   "\n" ,
   "   A large number of AFNI defaults can be controlled from the '.Xdefaults'\n" ,
   "     file in your home directory.  The file 'AFNI.Xdefaults' is a sample\n" ,
   "     version of this.  In particular, it is possible to add colors to\n" ,
   "     the color chooser menus.  Here are the lines from my .Xdefaults:\n" ,
   "        Line                    Meaning\n" ,
   "        ---------------------   ------------------------------------------\n" ,
   "        AFNI*ncolovr: 22        Add 2 colors to the menu (20 are built in)\n" ,
   "        AFNI*ovdef21: brown     Definition of color number 21\n" ,
   "        AFNI*ovlab21: brown     Menu label for color number 21\n" ,
   "        AFNI*ovdef22: #ffdd00   Definition of color number 22\n" ,
   "        AFNI*ovlab22: golden    Menu label for color number 22\n" ,
   "     Note that the color definitions (ovdef) can be names from the X11\n" ,
   "     color database (typically stored in /usr/lib/X11/rgb.txt), or can be\n" ,
   "     raw hexadecimal values -- pairs of hex digits, giving the intensity\n" ,
   "     of Red, Green, and Blue from 00 to ff (0 to 255).  Note also that\n" ,
   "     the labels (ovlab) are separate from the definitions.  A maximum\n" ,
   "     of 99 colors can be defined in this way (that is, the largest\n" ,
   "     legitimate value for AFNI*ncolovr is 99).\n" ,
   "\n" ,
   "   Many other things can be controlled from .Xdefaults, including the\n" ,
   "     colors and line thicknesses used for graphs.\n" ,
   "\n" ,
   "   A new \"plugout\" facility is under development.  This is a protocol\n" ,
   "     that external programs can use to exchange information with AFNI.\n" ,
   "     At present, the only type of information so available is the\n" ,
   "     Talairach coordinates of the current AFNI viewpoint.  If you are\n" ,
   "     interested in the further development and application of this\n" ,
   "     facility, I'd like to hear from you.  The source code \"plugout_tt.c\"\n" ,
   "     contains a simple plugout that will be informed any time the\n" ,
   "     user changes Talairach coordinates within AFNI.\n" ,
   "\n" ,
   "   The program 3dfim can now compute percent signal change in a voxel.\n" ,
   "\n" ,
   "   The new programs 3dNLfim, 3dTSgen, AlphaSim, and 3dFWHM have been\n" ,
   "     added to the package by Doug Ward of MCW.  PostScript documentation\n" ,
   "     files are available for these programs.  Briefly:\n" ,
   "\n" ,
   "   3dNLfim computes the fit of a nonlinear time series model to each voxel\n" ,
   "     separately.  The output is a group of AFNI datasets that contain the\n" ,
   "     estimated fit parameters, with F (or t) statistics indicating\n" ,
   "     significance.  The new plugin 'NLfit & NLerr' can do the nonlinear\n" ,
   "     fitting interactively and display the graphs of the fitted curves\n" ,
   "     on top of the data curves.\n" ,
   "\n" ,
   "   3dTSgen can generate random AFNI datasets from a nonlinear time series\n" ,
   "     model.  This is used to test the efficacy of detection and estimation\n" ,
   "     schemes (such as 3dNLfim).\n" ,
   "\n" ,
   "   AlphaSim is used to estimate the significance of clusters of above-\n" ,
   "     threshold voxels, which is an alternative to single voxel detection.\n" ,
   "     3dFWHM is a utility to estimate the spatial correlation of an AFNI\n" ,
   "     dataset, which is an input parameter to AlphaSim.\n" ,
   "\n" ,
   "   New PostScript documentation files are:\n" ,
   "     - 3dNLfim.ps:       for 3dNLfim and its plugin, and 3dTSgen\n" ,
   "     - 3dfim.ps:         for changes to 3dfim\n" ,
   "     - 3dhisto.ps:       for changes to 3dhistog\n" ,
   "     - AlphaSim.ps:      for AlphaSim and 3dFWHM programs\n" ,
   "     - AlphaSim_fig.ps:  figures for AlphaSim.ps\n" ,
   "     - afni_aux.ps:      for all the auxiliary programs, updated to\n" ,
   "                           include the changes to 3dfim and 3dhistog\n" ,
   "--------------------------------------------------------------------------\n" ,
   "19 June 1997:\n" ,
   "   The graphing windows \"Opt\" menu now has items to allow you to save\n" ,
   "     the graph window to a PNM format image file, and to control the\n" ,
   "     colors used for graphing.\n" ,
   "   The new plugin '3D Edit' allows interactive editing of datasets\n" ,
   "     using all the \"-1option\" functions of program 3dmerge (e.g.,\n" ,
   "     blurring, clustering, ...).\n" ,
   "--------------------------------------------------------------------------\n" ,
   "04 April 1997:\n" ,
   "   The program \"imcalc\" is available to do pixel-by-pixel calculations\n" ,
   "     on 2D images, providing capabilities similar to those that 3dcalc\n" ,
   "     supplies for 3D datasets.  Type \"imcalc -help\" for usage info.\n" ,
   "--------------------------------------------------------------------------\n" ,
   "05 March 1997:\n" ,
   "   Added two \"Read\" buttons on the \"Define Datamode\" control panel.\n" ,
   "     \"Sess\" will read in an entirely new session, unlike the \"Rescan\"\n" ,
   "     buttons, which will just re-read already input sessions.  \"1D\"\n" ,
   "     will read in a new time series file.\n" ,
   "   You can now start afni without any data being present, and then read\n" ,
   "     datasets and time series in with the new buttons.  Note that the\n" ,
   "     program will create a dummy dataset that will be viewable until\n" ,
   "     a real session is input.\n" ,
   "\n" ,
   "   Afni has been reported to crash on startup at a couple of sites.\n" ,
   "     This seems to be the result of the plugin startup code, which scans\n" ,
   "     all the directories in the environment variable PATH for plugins.\n" ,
   "     This scan, and the resulting problems, can be avoided by defining\n" ,
   "     the environment variable AFNI_PLUGINPATH to point to the desired\n" ,
   "     directory where the plugins are stored.  In the C shell:\n" ,
   "        setenv AFNI_PLUGINPATH /plugin/directory\n" ,
   "     In the Bourne or Korn shells\n" ,
   "        AFNI_PLUGINPATH=/plugin/directory\n" ,
   "        export AFNI_PLUGINPATH\n" ,
   "     Logically, these go best in your startup files (e.g., .cshrc).\n" ,
   "   If you wish to avoid trying to load plugins altogther, the new\n" ,
   "     switch \"-noplugins\" can be used on the afni command line.\n" ,
   "     You may also set the environment variable AFNI_NOPLUGINS; this\n" ,
   "     will also prevent the plugin startup code from being executed.\n" ,
   "\n" ,
   "   Afni has also been reported to crash on Sun workstations when\n" ,
   "     a graph window gets closed.  Since this error does not occur\n" ,
   "     on the SGI, HP, and Linux workstations to which I have access,\n" ,
   "     I can't debug this problem.  The same remark applies to the\n" ,
   "     plugin startup code problem.\n" ,
   "\n" ,
   "   It is now possible to create 3D+time \"fim\" datasets using to3d.\n" ,
   "     These can be displayed within afni as the color overlay, and\n" ,
   "     the time \"Index\" button can be used to select which one is\n" ,
   "     displayed.  No other program in the AFNI package can deal with\n" ,
   "     such time-dependent functional datasets.\n" ,
   "--------------------------------------------------------------------------\n" ,
   "23 February 1997:\n" ,
   "   Added the '2D Registration' plugin, which does image registration on\n" ,
   "     3D+time datasets, using the same routines as programs imreg and fim2.\n" ,
   "--------------------------------------------------------------------------\n" ,
   "18 February 1997:\n" ,
   "   Fixed a bug in the graphing windows that caused AFNI to crash on\n" ,
   "     some computer systems.\n" ,
   "   Added some \"logical\" functions to 3dcalc to make it easier to perform\n" ,
   "     masking operations on datasets.  Also added a \"-session\" option to\n" ,
   "     all the output directory to be specified on the command line.\n" ,
   "   The machdep.h file now has a #define that allows the \"frivolous\"\n" ,
   "     features of afni to be avoided.  (If you don't know that they\n" ,
   "     are, don't ask.)\n" ,
   "--------------------------------------------------------------------------\n" ,
   "05 February 1997:\n" ,
   "   The program 3dANOVA3 is provided to perform 3-way ANOVA, voxel-by-voxel,\n" ,
   "     on collections of AFNI datasets.  This program is documented in\n" ,
   "     3dANOVA3.ps (which is also included in the new afni_aux.ps).\n" ,
   "   [Per the request of lots of neuroscientists at MCW.]\n" ,
   "--------------------------------------------------------------------------\n" ,
   "30 January 1997:\n" ,
   "   The program \"3dcalc\" is provided to perform voxel-by-voxel arithmetic\n" ,
   "     on collections of AFNI datasets.  See \"3dcalc -help\" for details.\n" ,
   "--------------------------------------------------------------------------\n" ,
   "21 January 1997:\n" ,
   "   The \"Slice\", \"Matrix\", and \"Ignore\" menus on the graphing windows\n" ,
   "     have had the \"Choose\" item replaced with an option menu that\n" ,
   "     lets you directly select the desired values, rather than have\n" ,
   "     to go through a popup chooser dialog.\n" ,
   "   The \"Scale\" menu \"Choose\" item now accepts floating point scale\n" ,
   "     factors, which allows for finer control of the scale of a graph.\n" ,
   "     Previously, it only accepted integer inputs.\n" ,
   "--------------------------------------------------------------------------\n" ,
   "20 January 1997:\n" ,
   "   A Makefile for DEC Alpha OSF/1 is included.  This was devised on a\n" ,
   "     system at University of Maryland.\n" ,
   "   The script file \"gmovie\" can be used to create GIF animations from\n" ,
   "     a sequence of PNM files, as might be output from the \"Save:pnm\"\n" ,
   "     button in AFNI.  This is intended mostly as a prototype of how\n" ,
   "     to make animated GIFs (using the program whirlgif).\n" ,
   "--------------------------------------------------------------------------\n" ,
   "10 January 1997:\n" ,
   "   The distribution is now split into \"afni96.tgz\" (source code)\n" ,
   "     and \"doc.tgz\" (PostScript documentation).  This is because\n" ,
   "     I've included a couple of new PostScript files in the\n" ,
   "     documentations set, and it's getting pretty damn big.\n" ,
   "   Also, added a Makefile.sgi5k for the R5000 O2 systems (now that\n" ,
   "     Marquette Biomedical Engineering has one I can play with).\n" ,
   "--------------------------------------------------------------------------\n" ,
   "03 January 1997:\n" ,
   "   Added the new program \"waver\".  This will generate an ideal waveform\n" ,
   "     vector with adjustable parameters (such as rise and fall times).\n" ,
   "     At present, the only documentation is \"waver -help\".\n" ,
   "   [Per the request of Peter Bandettini of MCW Biophysics.]\n" ,
   "--------------------------------------------------------------------------\n" ,
   "02 January 1997:\n" ,
   "   Added the filename \"globbing\" ability to FD2.  This program still\n" ,
   "     requires 1 image per file (3D: can only be used to specify the\n" ,
   "     offset and shape of the images), but now wildcards can be escaped\n" ,
   "     using the \"\\*\", \"\\?\", and \"\\[\\]\" constructions of the C shell.\n" ,
   "     This allows input of more files than the C shell may allow to\n" ,
   "     appear on the command line (in particular, on SGI systems).\n" ,
   "   [Per the request of Kathleen Donahue of MCW Biophysics.]\n" ,
   "--------------------------------------------------------------------------\n" ,
   "01 January 1997:\n" ,
   "   Added a toggle button labeled \"X+\" next to the \"Xhairs\" button\n" ,
   "     in the first column of each AFNI controller window.  This is\n" ,
   "     there to allow the display of the crosshairs in all slices of\n" ,
   "     an AFNI montage, not just the slice containing the viewpoint.\n" ,
   "     The main use for this seems to be when applying \"Save:one\", so\n" ,
   "     that the captured image has the crosshairs in each slice as a\n" ,
   "     common reference.  For this application, closing the gap in the\n" ,
   "     crosshairs will probably look best.\n" ,
   "   N.B.: When \"X+\" is turned on, there is no visual cue in the\n" ,
   "         montage to tell you which slice contains the viewpoint.\n" ,
   "   [Per the request of Jeffrey Binder of MCW Neurology.]\n" ,
   "--------------------------------------------------------------------------\n" ,
   "01 January 1997:\n" ,
   "   Added the switch \"-in:1\" to to3d.  This is to aid in the reading\n" ,
   "     of huge \"3D:\" files, and will prevent the duplication in memory\n" ,
   "     of entire data files while the dataset brick is being assembled.\n" ,
   "     With this switch, only one slice at a time will be read from\n" ,
   "     disk, so very large \"3D:\" files (e.g., containing all the data\n" ,
   "     from an FMRI run) can be imported.  The penalty for this is\n" ,
   "     somewhat more I/O overhead.  On the other hand, if the lower\n" ,
   "     memory requirements reduce paging to disk, the effective input\n" ,
   "     rate may actually be faster than without this switch.\n" ,
   "   [Per the request of Anders Andersen of the University of Kentucky.]\n" ,
   "--------------------------------------------------------------------------\n" ,
   "27 December 1996:\n" ,
   "   The new auxiliary program \"3dnewid\" is mentioned in the AFNI user's\n" ,
   "     manual, but not in the auxiliary programs manual.  This program will\n" ,
   "     assign a new identifier (ID) code to a dataset.  This is necessary if\n" ,
   "     you use \"cp\" to copy a dataset's files: the new copy should have\n" ,
   "     \"3dnewid\" run on it.  Without a new ID code, afni may get confused if\n" ,
   "     both datasets are read into the program at once, since it uses ID\n" ,
   "     codes to keep track of datasets internally.\n" ,
   "--------------------------------------------------------------------------\n" ,
   "\n" ,
   "   *******************************************************************\n" ,
   "   **    And remember -- whatever you do, DON'T click mouse button  **\n" ,
   "   **       #1 in the blank area right of the \"done\" button!        **\n" ,
   "   *******************************************************************\n" ,
   NULL } ;
#define NUM_newstuff 455
