#ifndef PROG_OPTS_INCLUDED
#define PROG_OPTS_INCLUDED

/* 
   ***********    Manual Edits Can Get CLOBBERED!    ***********
   *************** File created automatically ******************

   This file was initially created by function progopt_C_array(), 
   via program apsearch with:
        apsearch -C_all_prog_opt_array > prog_opts.c

   To update entry for just one program (PROG) best use:
        apsearch -C_all_prog_opt_array PROG > prog_opts.c


You'll need to also touch thd_getpathprogs.c before rebuilding 
libmri.a, etc.
*/

#if 0
static PROG_OPTS poptslist[] = {
   {NULL, NULL, 0}
}
#else
static PROG_OPTS poptslist[] = {
{ "1dAstrip", "", 0},
{ "1dBandpass", "-dt; -nodetrend; -norm; -ort; ", 4},
{ "1dBport", "-TR; -band; -concat; -input; -input1D; -invert; -noconst; -nodata; -nozero; -quad; ", 10},
{ "1dCorrelate", "-Ktaub; -Pearson; -Quadrant; -Spearman; -alpha; -blk; -block; -nboot; ", 8},
{ "1dDW_Grad_o_Mat", "-bmax_ref; -dwi_comp_fac; -flip_x; -flip_y; -flip_z; -in_bmatA_cols; -in_bmatT_cols; -in_bvals; -in_gmatA_cols; -in_gmatT_cols; -in_grad_cols; -in_grad_rows; -keep_b0s; -out_bmatA_cols; -out_bmatT_cols; -out_bval_col; -out_gmatA_cols; -out_gmatT_cols; -out_grad_cols; -out_grad_rows; -pref_dset; -proc_dset; -put_zeros_top; ", 23},
{ "1dFlagMotion", "-MaxRot; -MaxTrans; ", 2},
{ "1dMarry", "-divorce; -sep; ", 2},
{ "1dRplot", "-TR; -addavg; -col.color; -col.grp; -col.line.type; -col.name; -col.name.show; -col.nozeros; -col.plot.char; -col.plot.type; -col.text.lym; -col.text.rym; -col.ystack; -grid.show; -grp.label; -help; -i; -input; -input_delta; -input_type; -leg.fontsize; -leg.line.color; -leg.line.type; -leg.names; -leg.ncol; -leg.plot.char; -leg.position; -leg.show; -load.Rdat; -mat; -matplot; -msg.trace; -multi; -multiplot; -nozeros; -one; -oneplot; -prefix; -row.name; -rowcol.name; -run_examples; -save; -save.Rdat; -save.size; -show_allowed_options; -title; -verb; -x; -xax.label; -xax.lim; -xax.tic.text; -yax.label; -yax.lim; -yax.tic.text; -zeros; ", 55},
{ "1dSEM", "-C; -DF; -calccost; -forest_growth; -grow_all; -leafpicker; -limits; -max_iter; -max_paths; -model_search; -nrand; -psi; -stop_cost; -theta; -tree_growth; -verbose; ", 16},
{ "1dTsort", "-col; -dec; -flip; -imode; -inc; ", 5},
{ "1dUpsample", "", 0},
{ "1d_tool.py", "-1; -LIMIT,LIMIT; -add_cols; -backward_diff; -censor; -censor_fill; -censor_fill_parent; -censor_first_trs; -censor_infile; -censor_motion; -censor_next_TR; -censor_prev_TR; -collapse_cols; -cormat_cutoff; -demean; -derivative; -extreme_mask; -forward_diff; -help; -hist; -index_to_run_tr; -infile; -label_prefix_drop; -label_prefix_keep; -looks_like_1D; -looks_like_AM; -looks_like_global_times; -looks_like_local_times; -looks_like_test_all; -moderate_mask; -overwrite; -pad_into_many_runs; -quick_censor_count; -randomize_trs; -rank; -rank_style; -reverse; -reverse_rank; -seed; -select_cols; -select_groups; -select_rows; -set_nruns; -set_run_lengths; -set_tr; -show_argmin; -show_censor_count; -show_cormat; -show_cormat_warnings; -show_gcor; -show_gcor_all; -show_gcor_doc; -show_group_labels; -show_indices_baseline; -show_indices_interest; -show_indices_motion; -show_label_ordering; -show_labels; -show_max_displace; -show_mmms; -show_num_runs; -show_rows_cols; -show_tr_run_counts; -show_trs_censored; -show_trs_run; -show_trs_to_zero; -show_trs_uncensored; -show_valid_opts; -sort; -split_into_pad_runs; -transpose; -transpose_write; -ver; -verb; -verb.; -volreg2allineate; -weight_vec; -write; -write_CENSORTR; -write_censor; ", 80},
{ "1dcat", "-form; -nonconst; -nonfixed; -sel; -stack; ", 5},
{ "1ddot", "-cov; -dem; -inn; -okzero=; -one; -rank; -terse=; ", 7},
{ "1deval", "-1D; -a; -del; -index; -num; -start; ", 6},
{ "1dfft", "-fromcx; -hilbert; -ignore; -nfft; -nodetrend; -tocx; -use; ", 7},
{ "1dgenARMA11", "-CORcut; -a; -b; -lam; -len; -norm; -num; -nvec; -seed; -sig; ", 10},
{ "1dgrayplot", "-flip; -ignore; -install; -ps; -sep; -use; ", 6},
{ "1dmatcalc", "", 0},
{ "1dnorm", "-demean; -demed; -norm1; -normx; ", 4},
{ "1dplot", "-CENSORTR; -Dname=val; -NOLINE; -THICK; -a; -box; -censor; -censor_RGB; -concat; -dashed; -dx; -hist; -ignore; -install; -jpeg; -jpegs; -jpg; -jpgs; -noline; -nopush; -norm1; -norm2; -normx; -one; -plabel; -png; -pngs; -ps; -sep; -sepscl; -stdin; -thick; -title; -use; -volreg; -wintitle; -x; -xaxis; -xl10; -xlabel; -xmulti; -xtran; -xzero; -yaxis; -ylabel; -ynames; -ytran; ", 47},
{ "1dsum", "-ignore; -use; ", 2},
{ "1dsvd", "-1Dleft; -asort; -cond; -nev; -nosort; -one; -sing; -sort; -vmean; -vnorm; ", 10},
{ "1dtranspose", "", 0},
{ "24swap", "-pattern; -q; ", 2},
{ "2dImReg", "-base; -basefile; -debug; -dmm; -dprefix; -fine; -input; -nofine; -prefix; -rprefix; ", 10},
{ "2perm", "-comma; -prefix; ", 2},
{ "2swap", "", 0},
{ "3dABoverlap", "-no_automask; -quiet; -verb; ", 3},
{ "3dAFNIto3D", "-bin; -prefix; -txt; ", 3},
{ "3dAFNItoANALYZE", "-4D; -orient; -x; -y; -z; ", 5},
{ "3dAFNItoMINC", "-floatize; -prefix; -swap; ", 3},
{ "3dAFNItoNIFTI", "-denote; -float; -newid; -oldid; -prefix; -pure; -verb; ", 7},
{ "3dAFNItoNIML", "-ascii; -data; -tcp:host:port; ", 3},
{ "3dAFNItoRaw", "-datum; -output; ", 2},
{ "3dANALYZEtoAFNI", "-TR; -abuc; -fbuc; -geomparent; -orient; -prefix; -view; -zorigin; ", 8},
{ "3dANOVA", "-OK; -assume_sph; -bucket; -contr; -debug; -diff; -diskspace; -dset; -ftr; -levels; -mask; -mean; -old_method; -voxel; ", 14},
{ "3dANOVA2", "-OK; -acontr; -adiff; -alevels; -amean; -assume_sph; -bcontr; -bdiff; -blevels; -bmean; -bucket; -diskspace; -dset; -fa; -fab; -fb; -ftr; -mask; -old_method; -type; -voxel; -xcontr; -xdiff; -xmean; ", 24},
{ "3dANOVA3", "-Abcontr; -Abdiff; -OK; -aBcontr; -aBdiff; -abmean; -acontr; -adiff; -alevels; -amean; -assume_sph; -bcontr; -bdiff; -blevels; -bmean; -bucket; -ccontr; -cdiff; -clevels; -cmean; -diskspace; -dset; -fa; -fab; -fabc; -fac; -fb; -fbc; -fc; -mask; -old_method; -type; -voxel; -xdiff; -xmean; ", 35},
{ "3dAcost", "", 0},
{ "3dAllineate", "--; -1Dmatrix_apply; -1Dmatrix_save; -1Dparam_apply; -1Dparam_save; -DSU; -EPI; -SDU; -Slower; -Supper; -USD; -ashift; -autobox; -automask; -autoweight; -base; -bshift; -check; -cmass; -conv; -cost; -emask; -final; -fineblur; -float; -floatize; -input; -interp; -mast_dxyz; -master; -maxrot; -maxscl; -maxshf; -maxshr; -newgrid; -nmatch; -nmi; -nocmass; -nomask; -nopad; -nousetemp; -onepass; -out; -parang; -parfix; -parini; -prefix; -quiet; -replacebase; -replacemeth; -source; -source_automask; -source_mask; -twobest; -twoblur; -twofirst; -twopass; -usetemp; -verb; -warp; -warpfreeze; -weight; -wtprefix; -zclip; ", 64},
{ "3dAnatNudge", "-anat; -epi; -prefix; -step; -verb; -x; -y; -z; ", 8},
{ "3dAnhist", "-2; -F; -fname; -h; -label; -q; -w; ", 7},
{ "3dAttribute", "-all; -center; -name; -quote; -sprep; -ssep; ", 6},
{ "3dAutoTcorrelate", "-autoclip; -automask; -eta2; -mask; -mask_only_targets; -mask_source; -mmap; -out1D; -pearson; -polort; -prefix; -spearman; -time; ", 13},
{ "3dAutobox", "-input; -noclust; -npad; -prefix; ", 4},
{ "3dAutomask", "-SI; -apply_prefix; -clfrac; -depth; -dilate; -eclip; -erode; -nbhrs; -nograd; -peels; -prefix; -q; ", 12},
{ "3dBRAIN_VOYAGERtoAFNI", "", 0},
{ "3dBandpass", "-automask; -band; -blur; -despike; -dsort; -dt; -input; -localPV; -mask; -nfft; -nodetrend; -norm; -nosat; -notrans; -ort; -prefix; -quiet; ", 17},
{ "3dBlurInMask", "-FWHM; -Mmask; -automask; -float; -input; -mask; -prefix; -preserve; -quiet; ", 9},
{ "3dBlurToFWHM", "-FHWM; -FWHM; -FWHMxy; -automask; -blurmaster; -bmall; -bsave; -detin; -detrend; -input; -mask; -maxite; -nbhd; -nodetrend; -prefix; -quiet; -rate; -temper; -unif; ", 19},
{ "3dBrickStat", "-absolute; -automask; -count; -help; -mask; -max; -mean; -median; -min; -mrange; -mvalue; -nan; -negative; -non-negative; -non-positive; -non-zero; -nonan; -percentile; -positive; -quick; -slow; -stdev; -sum; -var; -ver; -volume; -zero; ", 27},
{ "3dCM", "-all_rois; -automask; -mask; -roi_vals; -set; ", 5},
{ "3dCRUISEtoAFNI", "", 0},
{ "3dClipLevel", "-doall; -grad; -mfrac; ", 3},
{ "3dClustCount", "-final; -prefix; -quiet; ", 3},
{ "3dClustSim", "-BALL; -LOTS; -OKsmallmask; -athr; -both; -dxyz; -fwhm; -fwhmxyz; -iter; -mask; -niml; -nodec; -nxyz; -prefix; -pthr; -quiet; -seed; -ssave:TYPE; ", 18},
{ "3dConformist", "", 0},
{ "3dConvolve", "-base_file; -censor; -concat; -errts; -input; -input1D; -iresp; -mask; -nfirst; -nlast; -num_stimts; -output; -polort; -seed; -sigma; -stim_file; -stim_maxlag; -stim_minlag; -stim_nptr; -xout; ", 20},
{ "3dCountSpikes", "", 0},
{ "3dDFT", "-abs; -detrend; -inverse; -nfft; -taper; ", 5},
{ "3dDTeig", "-datum; -prefix; -sep_dsets; -uddata; ", 4},
{ "3dDTtoDWI", "-automask; -datum; -help; -prefix; ", 4},
{ "3dDTtoNoisyDWI", "-S0; -bval; -dt_in; -grads; -mask; -noise_B0; -noise_DWI; -prefix; ", 8},
{ "3dDWItoDT", "-automask; -bmatrix_NZ; -bmatrix_Z; -csf_fa; -csf_val; -cumulative_wts; -debug_briks; -drive_afni; -eigs; -linear; -mask; -max_iter; -max_iter_rw; -mean_b0; -nonlinear; -opt; -prefix; -reweight; -sep_dsets; -verbose; ", 20},
{ "3dDWUncert", "-bmatr; -csf_fa; -grads; -input; -input_list; -inset; -iters; -mask; -prefix; ", 9},
{ "3dDeconvolve", "--; -CENSORTR; -DAFNI_WRITE_1D_AS_PREFIX=YES; -Dname=val; -GOFORIT; -STATmask; -TR_1D; -TR_times; -allzero_OK; -automask; -basis_normall; -bout; -bucket; -cbucket; -censor; -concat; -dmbase; -errts; -fdisp; -fitts; -float; -force_TR; -fout; -full_first; -global_times; -glt; -glt_label; -gltsym; -help; -input; -input1D; -iresp; -jobs; -legendre; -local_times; -mask; -nfirst; -nlast; -noFDR; -noblock; -nobout; -nobucket; -nocond; -nocout; -nodata; -nodmbase; -nofull_first; -nofullf_atall; -nolegendre; -nosvd; -nox1D; -noxsave; -num_glt; -num_stimts; -ortvec; -polort; -progress; -quiet; -rmsmin; -rout; -sat; -short; -singvals; -sresp; -stim_base; -stim_file; -stim_label; -stim_maxlag; -stim_minlag; -stim_nptr; -stim_times; -stim_times_AM1; -stim_times_AM2; -stim_times_FSL; -stim_times_IM; -stim_times_millisec; -stim_times_subtract; -svd; -tout; -tshift; -virtvec; -vout; -x1D; -x1D_stop; -x1D_uncensored; -xjpeg; -xout; -xrestore; -xsave; ", 89},
{ "3dDeconvolve_f", "", 0},
{ "3dDespike", "-NEW; -corder; -cut; -dilate; -ignore; -localedit; -nomask; -prefix; -q[uiet; -ssave; ", 10},
{ "3dDetrend", "-byslice; -del; -expr; -normalize; -polort; -prefix; -replace; -session; -vector; -verb; ", 10},
{ "3dEigsToDT", "-; -eig_vals; -eig_vecs; -flip_x; -flip_y; -flip_z; -mask; -prefix; -scale_eigs; ", 9},
{ "3dEmpty", "-nt; -nxyz; -prefix; ", 3},
{ "3dEntropy", "", 0},
{ "3dErrtsCormat", "-concat; -input; -mask; -maxlag; -polort; ", 5},
{ "3dExtrema", "-average; -closure; -data_thr; -interior; -mask_file; -mask_thr; -maxima; -minima; -output; -partial; -prefix; -quiet; -remove; -sep_dist; -session; -slice; -strict; -volume; -weight; ", 19},
{ "3dFDR", "-cdep; -cind; -float; -force; -input; -input1D; -list; -mask; -mask_file; -mask_thr; -new; -nopmask; -old; -output; -pmask; -prefix; -quiet; -qval; ", 18},
{ "3dFFT", "-Lx; -Ly; -Lz; -abs; -altIN; -altOUT; -complex; -input; -inverse; -phase; -prefix; ", 11},
{ "3dFWHM", "-compat; -dset; -mask; -out; -quiet; ", 5},
{ "3dFWHMx", "-arith; -automask; -combine; -compat; -demed; -detprefix; -detrend; -dset; -geom; -input; -mask; -out; -unif; ", 13},
{ "3dFourier", "-highpass; -ignore; -lowpass; -prefix; -retrend; ", 5},
{ "3dFriedman", "-dset; -levels; -out; -voxel; -workmem; ", 5},
{ "3dGenFeatureDist", "-ShowTheseHists; -classes; -debug; -features; -hspec; -labeltable; -overwrite; -prefix; -samp; -sig; ", 10},
{ "3dGenPriors", "-ShowThisDist; -classes; -cmask; -cprefix; -cset; -debug; -do; -fast; -featgroups; -features; -labeltable; -mask; -mrange; -no_tmp; -pgprefix; -pprefix; -prefix; -pset; -regroup_classes; -sig; -slow; -tdist; -uid; -use_tmp; -vox_debug; -vox_debug_file; ", 26},
{ "3dGetrow", "-input; -output; -xrow; -yrow; -zrow; ", 5},
{ "3dGroupInCorr", "-; --; -Apair; -NOshm; -VERB; -ah; -batch; -batchGRID; -batchRAND; -center; -clust; -covariates; -debug; -donocov; -dospcov; -labelA; -labelB; -max_port_bloc; -max_port_bloc_quiet; -nosix; -np; -npb; -npq; -num_assigned_ports; -num_assigned_ports_quiet; -paired; -pooled; -quiet; -scale; -sdset_TYPE; -sdset_niml; -seedrad; -sendall; -setA; -setB; -suma; -unpooled; -verb; ", 38},
{ "3dHist", "-at; -binwidth; -cmask; -dind; -equalized; -get; -ignore_out; -input; -mask; -mask_range; -max; -min; -nbin; -prefix; -quiet; -rhist; -showhist; -thishist; -val_at; -voxvol; ", 20},
{ "3dIntracranial", "-anat; -mask; -max_conn; -max_val; -min_conn; -min_val; -nosmooth; -prefix; -quiet; ", 9},
{ "3dInvFMRI", "-1; -alpha; -base; -data; -fir5; -input; -map; -mapwt; -mask; -median5; -method; -out; -polort; ", 13},
{ "3dKruskalWallis", "-dset; -levels; -out; -voxel; -workmem; ", 5},
{ "3dLME", "-ICC; -LOGIT; -Rio; -SS_type; -cio; -corStr; -cutoff; -dataTable; -glfCode; -glfCode.; -glfLabel; -gltCode; -gltCode.; -gltLabel; -help; -jobs; -mask; -model; -num_glf; -num_glt; -prefix; -qVarCenters; -qVars; -ranEff; -show_allowed_options; -vVarCenters; -vVars; ", 27},
{ "3dLRflip", "-LR; -X; -prefix; ", 3},
{ "3dLSS", "-automask; -input; -mask; -matrix; -nodata; -prefix; -save1D; -stim_times_IM; -verb; ", 9},
{ "3dLocalBistat", "-automask; -hclip1; -hclip2; -histbin; -histpow; -mask; -nbhd; -prefix; -stat; -weight; ", 10},
{ "3dLocalHistog", "-excNONLAB; -exclude; -hsave; -lab_file; -mincount; -nbhd; -prefix; -prob; -quiet; ", 9},
{ "3dLocalPV", "-automask; -despike; -evprefix; -input; -mask; -nbhd; -polort; -prefix; -vnorm; -vproj; ", 10},
{ "3dLocalSVD", "-automask; -input; -mask; -nbhd; -polort; -prefix; -vnorm; -vproj; ", 8},
{ "3dLocalstat", "-automask; -datum; -grid_rmode; -label_ext; -mask; -nbhd; -prefix; -proceed_small_N; -quiet; -reduce_grid; -reduce_max_vox; -reduce_restore_grid; -stat; -use_nonmask; -verb; ", 15},
{ "3dMEMA", "-HKtest; -Rio; -cio; -contrast_name; -covariates; -covariates_center; -covariates_model; -covariates_name; -covariates_name.; -equal_variance; -groups; -help; -jobs; -mask; -max_zeros; -missing_data; -model_outliers; -n_nonzero; -no_HKtest; -no_model_outliers; -no_residual_Z; -prefix; -residual_Z; -set; -unequal_variance; -verb; ", 26},
{ "3dMINCtoAFNI", "", 0},
{ "3dMVM", "-Rio; -SC; -SS_type; -bsVars; -cio; -dataTable; -glfCode; -glfCode.; -glfLabel; -gltCode; -gltCode.; -gltLabel; -help; -jobs; -mVar; -mask; -model; -num_glf; -num_glt; -prefix; -qVarCenters; -qVars; -show_allowed_options; -vVarCenters; -vVars; -wsE2; -wsMVT; -wsVars; ", 28},
{ "3dMannWhitney", "-dset; -out; -voxel; -workmem; ", 4},
{ "3dMaskToASCII", "-tobin; ", 1},
{ "3dMatch", "-in_max; -in_min; -inset; -mask; -only_dice_thr; -prefix; -ref_max; -ref_min; -refset; ", 9},
{ "3dMax", "-absolute; -automask; -count; -help; -mask; -max; -mean; -median; -min; -mrange; -mvalue; -nan; -negative; -non-negative; -non-positive; -non-zero; -nonan; -percentile; -positive; -quick; -slow; -stdev; -sum; -var; -ver; -volume; -zero; ", 27},
{ "3dMean", "-count; -datum; -fscale; -gscale; -mask_inter; -mask_union; -non_zero; -nscale; -prefix; -sd; -sqr; -stdev; -sum; -verbose; ", 14},
{ "3dMedianFilter", "-automask; -irad; -iter; -prefix; -verb; ", 5},
{ "3dNLfim", "-BOTH; -POWELL; -SIMPLEX; -TR; -brick; -bucket; -farea; -fdisp; -fncoef; -fparea; -fpsmax; -freg; -frsqr; -fscoef; -fsmax; -ftmax; -ignore; -inTR; -input; -jobs; -mask; -nabs; -nbest; -nconstr; -noFDR; -noise; -nrand; -progress; -rmsmin; -sconstr; -sfit; -signal; -snfit; -time; -tncoef; -tscoef; -voxel_count; ", 37},
{ "3dNetCorr", "-fish_z; -ignore_LT; -in_rois; -inset; -mask; -nifti; -part_corr; -prefix; -ts_indiv; -ts_label; -ts_out; -ts_wb_Z; -ts_wb_corr; ", 13},
{ "3dNormalityTest", "-input; -noexp; -prefix; -pval; ", 4},
{ "3dNotes", "-HH; -a; -d; -h; -help; -ses; ", 6},
{ "3dNwarpAdjust", "-nwarp; -prefix; -source; ", 3},
{ "3dNwarpApply", "--; -->+; -affter; -ainterp; -dxyz; -interp; -iwarp; -master; -newgrid; -nwarp; -prefix; -quiet; -short; -source; -suffix; -verb; ", 16},
{ "3dNwarpCalc", "-ainterp; -interp; -verb; ", 3},
{ "3dNwarpCat", "-expad; -interp; -iwarp; -prefix; -space; -verb; -warp1; -warp2; ", 8},
{ "3dNwarpFuncs", "-bulk; -nwarp; -prefix; -shear; -vorticity; ", 5},
{ "3dNwarpXYZ", "-iwarp; ", 1},
{ "3dOverlap", "-save; ", 1},
{ "3dPAR2AFNI.pl", "-2; -4; -a; -g; -h; -n; -o; -s; -v; ", 9},
{ "3dPeriodogram", "-nfft; -prefix; -taper; ", 3},
{ "3dPolyfit", "-automask; -base; -blur; -mask; -mclip; -meth; -mone; -mrad; -nord; -prefix; -resid; -verb; ", 12},
{ "3dProbTrackID", "", 0},
{ "3dQwarp", "--; -allin; -allineate; -allineate_opts; -allinfast; -allopt; -allsave; -base; -blur; -duplo; -emask; -expad; -gridlist; -inilev; -iniwarp; -iwarp; -maxlev; -minpatch; -noXdis; -noYdis; -noZdis; -nodset; -noneg; -nopad; -nopadWARP; -nopblur; -nopenalty; -nowarp; -noweight; -patchmin; -pblur; -pear; -penfac; -plusminus; -pmNAMES; -prefix; -quiet; -resample; -source; -useweight; -verb; -weight; -workhard; -workhard:4:7; ", 44},
{ "3dREMLfit", "-ABfile; -CORcut; -GOFORIT; -Grid; -MAXa; -MAXb; -Mfilt; -NEGcor; -Obeta; -Obuck; -Oerrts; -Ofitts; -Oglt; -Ovar; -POScor; -Rbeta; -Rbuck; -Rerrts; -Rfitts; -Rglt; -Rvar; -Rwherr; -STATmask; -addbase; -automask; -fout; -gltsym; -input; -mask; -matrix; -noFDR; -nobout; -nodmbase; -quiet; -rout; -slibase; -slibase_sm; -tout; -usetemp; -verb; ", 40},
{ "3dROIMaker", "-csf_skel; -dump_no_labtab; -inflate; -inset; -mask; -neigh_face_edge; -neigh_face_only; -neigh_upto_vert; -nifti; -only_conn_top; -only_some_top; -prefix; -preinfl_inflate; -preinfl_inset; -refset; -skel_stop; -skel_thr; -thresh; -trim_off_wm; -volthr; -wm_skel; ", 21},
{ "3dROIstats", "-1DRformat; -1Dformat; -debug; -mask[n; -mask_f2short; -median; -minmax; -mode; -nobriklab; -nomeanout; -numROI; -nzmean; -nzmedian; -nzminmax; -nzmode; -nzsigma; -nzsum; -nzvoxels; -quiet; -roisel; -sigma; -summary; -zerofill; ", 23},
{ "3dRSFC", "-automask; -band; -blur; -bp_at_end; -despike; -dsort; -dt; -input; -localPV; -mask; -nfft; -no_rs_out; -no_rsfa; -nodetrend; -norm; -nosat; -notrans; -ort; -prefix; -quiet; ", 20},
{ "3dRank", "-help; -input; -prefix; -ver; ", 4},
{ "3dRankizer", "-brank; -mask; -percentize; -percentize_mask; -prefix; ", 5},
{ "3dReHo", "-chi_sq; -in_rois; -inset; -mask; -neigh_RAD; -neigh_X; -neigh_Y; -neigh_Z; -nneigh; -prefix; ", 10},
{ "3dRegAna", "-brick; -bucket; -cols; -datum; -diskspace; -fcoef; -fdisp; -flof; -model; -rcoef; -rmsmin; -rows; -tcoef; -workmem; -xydata; ", 15},
{ "3dRetinoPhase", "-Tstim; -ccw; -clw; -con; -exp; -multi_ref_ts; -nrings; -nwedges; -ort_adjust; -phase_estimate; -pre_stim; -prefix; -ref_ts; -spectra; -sum_adjust; ", 15},
{ "3dRowFillin", "-binary; -dir; -maxgap; -prefix; ", 4},
{ "3dRprogDemo", "-h_aspx; -h_raw; -h_spx; -h_txt; -help; -input; -mask; -prefix; -scale; -show_allowed_options; -verb; ", 11},
{ "3dSeg", "-Bmrf; -anat; -bias_classes; -bias_fwhm; -blur_meth; -classes; -cset; -debug; -gold; -gold_bias; -labeltable; -main_N; -mask; -mixfrac; -overwrite; -prefix; -vox_debug; -vox_debug_file; ", 18},
{ "3dSetupGroupInCorr", "-DELETE; -LRpairs; -byte; -labels; -mask; -prefix; -prep; -short; ", 8},
{ "3dSignatures", "", 0},
{ "3dSkullStrip", "", 0},
{ "3dSpatNorm", "-bottom_cuts; -human; -marmost; -monkey; -orig_space; -prefix; -rat; -verb; ", 8},
{ "3dStatClust", "-dist_cor; -dist_euc; -dist_ind; -nclust; -output; -prefix; -session; -thresh; -verb; ", 9},
{ "3dSurf2Vol", "-cmask; -data_expr; -datum; -debug; -dnode; -dvoxel; -f_index; -f_p1_fr; -f_p1_mm; -f_pn_XX; -f_pn_fr; -f_pn_mm; -f_steps; -grid_parent; -help; -hist; -map_func; -noscale; -prefix; -sdata; -sdata_1D; -spec; -surf_A; -surf_B; -surf_xyz_1D; -sv; -sxyz_orient_as_gpar; -version; ", 28},
{ "3dSurfMask", "-anatomical; -fill_method; -flip_orientation; -grid_parent; -i; -i_TYPE; -mask_only; -no_dist; -onestate; -prefix; -spec; -surf_A; -sv; -tn; -tsn; ", 15},
{ "3dSynthesize", "-TR; -cbucket; -cenfill; -dry; -matrix; -prefix; -select; -stim_label; ", 8},
{ "3dTORTOISEtoHere", "-; -dt_tort; -flip_x; -flip_y; -flip_z; -prefix; -scale_fac; ", 7},
{ "3dTRfix", "-TIMElist; -TRlist; -TRout; -input; -prefix; ", 5},
{ "3dTSgen", "-brick; -bucket; -inTR; -input; -ncoef; -nconstr; -noise; -output; -scoef; -sconstr; -sigma; -signal; -voxel; ", 13},
{ "3dTagalign", "-NN; -affine; -cubic; -dummy; -linear; -master; -matvec; -nokeeptags; -prefix; -quintic; -rotate; -rotscl; -verb; ", 13},
{ "3dTcat", "-DAFNI_GLOB_SELECTORS=YES; -dry; -glueto; -prefix; -relabel; -rlt; -session; -tpattern; -tr; -verb; ", 10},
{ "3dTcorr1D", "-float; -ktaub; -mask; -pearson; -prefix; -quadrant; -short; -spearman; ", 8},
{ "3dTcorrMap", "-Aexpr; -Cexpr; -CorrMap; -CorrMask; -Gblur; -Hist; -Mean; -Mseed; -Pmean; -Qmean; -Sexpr; -Thresh; -VarThresh; -VarThreshN; -Zmean; -automask; -bpass; -input; -mask; -ort; -polort; -seed; ", 22},
{ "3dTcorrelate", "-autoclip; -automask; -covariance; -ktaub; -ort; -pearson; -polort; -prefix; -quadrant; -spearman; -ycoef; ", 11},
{ "3dTfitter", "-->>++; -FALTUNG; -LHS; -RHS; -consFAL; -consign; -errsum; -fitts; -l1fit; -l2lasso; -l2sqrtlasso; -label; -lsqfit; -mask; -polort; -prefix; -quiet; -vthr; ", 18},
{ "3dThreetoRGB", "-anat; -fim; -mask; -prefix; -scale; ", 5},
{ "3dTnorm", "-L1fit; -norm1; -norm2; -normR; -normx; -polort; -prefix; ", 7},
{ "3dToutcount", "-autoclip; -automask; -fraction; -legendre; -mask; -polort; -qthr; -range; -save; ", 9},
{ "3dToyProg", "-HELP; -all_opts; -datum; -h; -h_aspx; -h_find; -h_raw; -h_spx; -h_view; -h_web; -hview; -hweb; -help; -h|-help; -input; -mask; -prefix; ", 15},
{ "3dTproject", "-CENSORTR; -automask; -blur; -cenmode; -censor; -concat; -dsort; -dt; -input; -mask; -noblock; -norm; -ort; -passband; -polort; -prefix; -quiet; -stopband; -verb; ", 19},
{ "3dTqual", "-autoclip; -automask; -clip; -mask; -quadrant; -range; -spearman; ", 7},
{ "3dTrackID", "-; ---; -alg_Nmonte; -alg_Nseed_Vox; -alg_Nseed_X; -alg_Nseed_Y; -alg_Nseed_Z; -alg_Thresh_ANG; -alg_Thresh_FA; -alg_Thresh_Frac; -alg_Thresh_Len; -algopt; -bundle_thr; -do_trk_out; -dti_extra; -dti_in; -dti_list; -dti_search_NO; -dump_lab_consec; -dump_no_labtab; -dump_rois; -extra_tr_par; -hardi_dirs; -hardi_gfa; -hardi_pars; -logic; -mask; -mini_num; -mode; -netrois; -nifti; -no_indipair_out; -pair_out_power; -posteriori; -prefix; -rec_orig; -thru_mask; -unc_min_FA; -unc_min_V; -uncert; -uncut_at_rois; -verb; -write_opts; -write_rois; ", 44},
{ "3dTshift", "-Fourier; -TR; -cubic; -heptic; -ignore; -linear; -no_detrend; -prefix; -quintic; -rlt; -rlt+; -slice; -tpattern; -tzero; -verbose; -voxshift; ", 16},
{ "3dTsmooth", "-3lin; -EXTEND; -TREND; -ZERO; -adaptive; -blackman; -custom; -datum; -hamming; -lin; -med; -osf; -prefix; ", 13},
{ "3dTsort", "-datum; -dec; -inc; -ind; -prefix; -rank; -val; ", 7},
{ "3dTstat", "-DW; -MAD; -absmax; -abssum; -accumulate; -argabsmax; -argabsmax1=; -argmax; -argmax1; -argmin; -argmin1; -autocorr; -autoreg; -basepercent; -bmv; -centduration; -centroid; -centromean; -cmask; -cvar; -cvarinv=; -datum; -duration; -l2norm; -mask; -max; -mean; -median; -min; -mrange; -nscale; -nzcount; -nzmean; -nzmedian; -offset; -onset; -prefix; -signed_absmax; -slope; -sos; -stdev; -stdevNOD; -sum; -tdiff; -zcount; ", 45},
{ "3dTwotoComplex", "-MP; -RI; -mask; -prefix; ", 4},
{ "3dUndump", "-ROImask; -datum; -dimen; -dval; -fval; -head_only; -ijk; -mask; -master; -orient; -prefix; -srad; -xyz; ", 13},
{ "3dUnifize", "-GM; -T2; -T2up; -Urad; -clfrac; -input; -prefix; -quiet; -rbt; -ssave; ", 10},
{ "3dUniformize", "-anat; -auto_clip; -clip_high; -clip_low; -niter; -prefix; -quiet; ", 7},
{ "3dUpsample", "-1; -datum; -input; -n; -prefix; -verb; ", 6},
{ "3dVol2Surf", "-cmask; -debug; -dnode; -f_index; -f_keep_surf_order; -f_p1_fr; -f_p1_mm; -f_pn_fr; -f_pn_mm; -f_steps; -first_node; -gp_index; -grid_parent; -help; -hist; -keep_norm_dir; -last_node; -map_func; -no_headers; -norm_len; -oob_index; -oob_value; -oom_value; -out_1D; -out_niml; -outcols_1_result; -outcols_NSD_format; -outcols_afni_NSD; -outcols_results; -reverse_norm_dir; -save_seg_coords; -skip_col_1dindex; -skip_col_i; -skip_col_j; -skip_col_k; -skip_col_nodes; -skip_col_vals; -spec; -surf_A; -surf_B; -sv; -use_norms; -v2s_hist; -version; ", 44},
{ "3dWarp", "-NN; -card2oblique; -cubic; -deoblique; -fsl_matvec; -gridset; -linear; -matparent; -matvec_in2out; -matvec_out2in; -mni2tta; -newgrid; -oblique2card; -oblique_parent; -prefix; -quintic; -tta2mni; -verb; -zpad; ", 19},
{ "3dWarpDrive", "-1Dfile; -1Dmatrix_save; -DSU; -NN; -SDU; -Slower; -Supper; -USD; -affine_general; -ashift; -base; -bilinear_general; -bshift; -coarserot; -cubic; -delta; -final; -float; -input; -linear; -maxite; -parfix; -prefix; -quintic; -shift_only; -shift_rotate; -shift_rotate_scale; -summ; -thresh; -twopass; -verb; -weight; ", 32},
{ "3dWavelets", "-bucket; -coefts; -cout; -datum; -errts; -fdisp; -filt_base; -filt_sgnl; -filt_stop; -fitts; -fout; -input; -input1D; -mask; -nfirst; -nlast; -rout; -sgnlts; -stat_first; -type; -vout; ", 21},
{ "3dWilcoxon", "-dset; -out; -voxel; -workmem; ", 4},
{ "3dWinsor", "-cbot; -clip; -ctop; -irad; -keepzero; -mask; -nrep; -prefix; ", 8},
{ "3dXYZcat", "-dir; -prefix; -verb; ", 3},
{ "3dZcat", "-datum; -frugal; -fscale; -nscale; -prefix; -verb; ", 6},
{ "3dZcutup", "-keep; -prefix; ", 2},
{ "3dZeropad", "-A; -AP; -I; -IS; -L; -P; -R; -RL; -S; -master; -mm; -prefix; -z; ", 13},
{ "3dZregrid", "-dz; -nsize; -nz; -prefix; -verb; -zsize; ", 6},
{ "3danisosmooth", "-2D; -3D; -automask; -datum; -deltat; -edgefraction; -help; -iters; -mask; -matchorig; -noneg; -nosmooth; -phiding; -phiexp; -prefix; -save_temp_with_diff_measures; -savetempdata; -setneg; -sigma1; -sigma2; -viewer; ", 21},
{ "3daxialize", "-axial; -coronal; -frugal; -orient; -prefix; -sagittal; -verb; ", 7},
{ "3dbuc2fim", "-or-; -prefix; -session; -verb; ", 4},
{ "3dbucket", "-abuc; -aglueto; -dry; -fbuc; -glueto; -prefix; -session; -verb; ", 8},
{ "3dcalc", "-LPI; -RAI; -SORT; -SPM; -TR; -a; -b; -byte; -c; -cx2r; -datum; -dicom; -dt; -expr; -float; -fscale; -gscale; -help; -nscale; -prefix; -rgbfac; -session; -short; -sort; -taxis; -usetemp; -verbose; ", 27},
{ "3dclust", "-0.3.; -1tindex; ", 2},
{ "3dcopy", "", 0},
{ "3ddelay", "-T; -asc; -ascts; -bias; -co; -dsamp; -fs; -ideal_file; -input; -mask; -nfirst; -nlast; -nobias; -nodsamp; -nodtrnd; -nophzwrp; -phzreverse; -phzscale; -phzwrp; -polort; -prefix; -uS; -uD; -uR; ", 24},
{ "3ddot", "-1D; -NIML; -demean; -docoef; -docor; -dodot; -doeta2; -dosums; -full; -mask; -mrange; -show_labels; -upper; ", 13},
{ "3ddup", "-'type'; -prefix; -session; ", 3},
{ "3dedge3", "-datum; -fscale; -gscale; -input; -nscale; -prefix; -scale_floats; -verbose; ", 8},
{ "3dfim", "-ideal; -im1; -input; -ort; -percent; -prefix; ", 6},
{ "3dfim+", "-bucket; -cdisp; -fim_thr; -ideal_file; -input; -input1D; -mask; -nfirst; -nlast; -ort_file; -out; -polort; ", 12},
{ "3dfractionize", "-clip; -input; -prefix; -preserve; -template; -vote; -warp; ", 7},
{ "3dhistog", "-dind; -doall; -float; -igfac; -int; -log10; -mask; -max; -min; -nbin; -notitle; -omit; -pdf; -prefix; -roi_mask; -unq; ", 16},
{ "3dinfill", "-Niter; -blend; -cmask; -ed; -input; -mask; -mask_range; -minhits; -prefix; ", 9},
{ "3dinfo", "-HELP; -NA_flag; -VERB; -ad3; -adi; -adj; -adk; -all_names; -all_opts; -atlas_points; -atr_delim; -av_space; -brick_name; -d3; -datum; -di; -dj; -dk; -dmax; -dmaxus; -dmin; -dminus; -exists; -fac; -gen_space; -h; -h_aspx; -h_find; -h_raw; -h_spx; -h_view; -h_web; -hview; -hweb; -handedness; -hdr; -header_line; -header_name; -help; -history; -id; -iname; -is_atlas; -is_nifti; -is_oblique; -label; -labeltable; -labeltable_as_atlas_points; -max; -max_node; -maxus; -min; -minus; -monog_pairs; -n4; -n[i|j|k; -nijk; -nt; -nti; -ntimes; -nv; -nvi; -o3; -obliquity; -oi; -oj; -ok; -orient; -prefix; -prefix_noext; -same_all_grid; -same_center; -same_delta; -same_dim; -same_grid; -same_obl; -same_orient; -sb_delim; -short; -slice_timing; -smode; -space; -sval_diff; -tr; -val_diff; -verb; -voxvol; ", 85},
{ "3dkmeans", "-clabels; -clust_init; -cmask; -f; -g; -input; -k; -labeltable; -mask; -mrange; -prefix; -r; -remap; -rsigs; -seed; -u; -v; -verb; -voxdbg; -write_dists; ", 20},
{ "3dmaskSVD", "-automask; -bpass; -input; -mask; -ort; -polort; -sval; -vnorm; ", 8},
{ "3dmask_tool", "-count; -datum; -dilate_inputs; -dilate_result; -fill_dirs; -fill_holes; -frac; -help; -hist; -inputs; -inter; -prefix; -quiet; -union; -ver; -verb; ", 16},
{ "3dmaskave", "-dball; -dbox; -dindex; -drange; -dump; -enorm; -ibox; -indump; -mask; -max; -median; -min; -mindex; -mrange; -nball; -nbox; -q; -quiet; -sigma; -slices; -sum; -sumsq; -udump; -xball; -xbox; ", 25},
{ "3dmaskdump", "-cmask; -dball; -dbox; -dbox.; -ibox; -index; -mask; -mrange; -n_rand; -n_randseed; -nball; -nbox; -niml; -noijk; -nozero; -o; -quiet; -xball; -xbox; -xyz; ", 20},
{ "3dmatcalc", "-input; -mask; -matrix; -prefix; ", 4},
{ "3dmatmult", "-datum; -help; -hist; -inputA; -inputB; -prefix; -ver; -verb; ", 8},
{ "3dmaxima", "-coords_only; -debug; -dset_coords; -help; -hist; -input; -min_dist; -n_style_sort; -n_style_weight_ave; -neg_ext; -no_text; -out_rad; -prefix; -spheres_1; -spheres_1toN; -spheres_Nto1; -thresh; -true_max; -ver; ", 19},
{ "3dmerge", "-1abs; -1blur_fwhm; -1blur_rms; -1blur_sigma; -1clip; -1clust; -1clust_amax; -1clust_depth; -1clust_max; -1clust_mean; -1clust_order; -1clust_size; -1clust_smax; -1dilate; -1dindex; -1erode; -1filter_amax; -1filter_aver; -1filter_blur; -1filter_expr; -1filter_max; -1filter_mean; -1filter_nzmean; -1filter_smax; -1filter_winsor; -1fmask; -1mult; -1noneg; -1rank; -1thresh; -1thtoin; -1tindex; -1uclip; -1zscore; -1zvol; -2clip; -2thresh; -2thtoin; -2uclip; -datum; -doall; -dxyz=1; -gamax; -gclust; -gcount; -gfisher; -ghits; -gmax; -gmean; -gnzmean; -gorder; -gsmax; -isomerge; -isovalue; -keepthr; -nscale; -prefix; -quiet; -session; -t1blur_fwhm; -t1blur_rms; -t1blur_sigma; -t1filter_amax; -t1filter_aver; -t1filter_max; -t1filter_mean; -t1filter_nzmean; -t1filter_smax; -tgfisher; ", 69},
{ "3dnewid", "", 0},
{ "3dnoise", "-blast; -nl; -snr; ", 3},
{ "3dnvals", "", 0},
{ "3dpc", "-1ddum; -dmean; -eigonly; -float; -mask; -normalize; -nscale; -pcsave; -prefix; -quiet; -reduce; -verbose; -vmean; -vnorm; ", 14},
{ "3dproject", "-ALL; -AP; -IS; -RL; -amax; -first; -max; -mirror; -nsize; -output; -smax; -sum; -sum|-max|-amax|-smax; ", 13},
{ "3drefit", "-'type'; -FDRmask; -STATmask; -TR; -Torg; -addFDR; -apar; -appkey; -atrcopy; -atrfloat; -atrint; -atrstring; -byteorder; -checkaxes; -clear_bstat; -cmap; -copyaux; -copytables; -denote; -deoblique; -duporigin; -dxorigin; -dxtag; -dyorigin; -dytag; -dzorigin; -dztag; -empkey; -keepcen; -label2; -labeltable; -markers; -newid; -nosaveatr; -notoff; -nowarp; -oblique_origin; -orient; -redo_bstat; -relabel_all; -relabel_all_str; -repkey; -saveatr; -shift_tags; -space; -statpar; -subappkey; -subempkey; -sublabel; -sublabel_prefix; -sublabel_suffix; -subrepkey; -substatpar; -unFDR; -view; -vr_center_base; -vr_center_old; -vr_mat; -vr_mat_ind; -wpar; -xdel; -xorigin; -xorigin_raw; -xyzscale; -ydel; -yorigin; -yorigin_raw; -zdel; -zorigin; -zorigin_raw; ", 70},
{ "3drename", "", 0},
{ "3dresample", "-bound_type; -debug; -dxyz; -dxyz.; -help; -hist; -inset; -master; -orient; -prefix; -rmode; -version; ", 12},
{ "3dretroicor", "-card; -cardphase; -help; -ignore; -order; -prefix; -resp; -respphase; -threshold; ", 9},
{ "3drotate", "-Fourier; -Fourier_nopad; -NN; -ashift; -bshift; -clipit; -cubic; -dfile; -gridparent; -heptic; -linear; -matvec_dicom; -matvec_dset; -matvec_order; -noclip; -origin; -points; -prefix; -quintic; -rotate; -rotparent; -verbose; -zpad; ", 23},
{ "3dsvm", "-; -a; -alpha; -b; -bucket; -c; -censor; -classout; -d; -e; -f; -g; -h; -help; -i; -j; -k; -kernel; -l; -m; -mask; -max_iterations; -model; -multiclass; -n; -nodetrend; -nomodelmask; -nopredcensord; -o; -p; -predictions; -q; -r; -s; -t; -testlabels; -testvol; -trainlabels; -trainvol; -type; -u; -v; -version; -w; -wout; -x; -z; ", 47},
{ "3dttest", "-base1; -base1_dset; -datum; -dof_prefix; -paired; -prefix; -sdn1; -session; -set1; -set2; -unpooled; -voxel; ", 12},
{ "3dttest++", "-->>++; -brickwise; -center; -cmeth; -covariates; -debug; -labelA; -labelB; -mask; -no1sam; -nomeans; -notests; -paired; -prefix; -rankize; -setA; -setB; -toz; -unpooled; -zskip; ", 20},
{ "3dvolreg", "--; -1Dfile; -1Dmatrix_save; -Fourier; -base; -clipit; -coarse; -coarserot; -cubic; -delta; -dfile; -edging; -final; -float; -gridparent; -heptic; -maxdisp; -maxdisp1D; -maxite; -noclip; -nocoarserot; -nomaxdisp; -prefix; -quintic; -rot_thresh; -rotate; -rotcom; -rotparent; -savedisp; -sinit; -tshift; -twoblur; -twodup; -twopass; -verbose; -weight; -wtinp; -x_thresh; -zpad; ", 39},
{ "4swap", "", 0},
{ "@1dDiffMag", "", 0},
{ "@2dwarper", "", 0},
{ "@2dwarper.Allin", "-mask; -prefix; ", 2},
{ "@4Daverage", "", 0},
{ "@ANATICOR", "-Rsq_WMe; -aseg; -coverage; -dirty; -echo; -motion; -no_ventricles; -nuisance; -polort; -prefix; -radius; -ts; -verb; -view; ", 14},
{ "@AddEdge", "-auto; -auto_record; -ax_geom; -ax_mont; -edge_percentile; -examinelist; -help; -keep_temp; -layout; -no_auto; -no_deoblique; -no_layout; -opa; -sag_geom; -single_edge; ", 15},
{ "@AfniEnv", "-all_opts; -get; -h_find; -h_view; -h_web; -hview; -hweb; -help; -set; -unset; ", 8},
{ "@AfniOrient2RAImap", "", 0},
{ "@AfniOrientSign", "", 0},
{ "@Align_Centers", "-1Dmat_only; -1Dmat_only_nodset; -base; -child; -cm; -dset; -echo; -grid; -no_cp; -overwrite; ", 10},
{ "@Atlasize", "-all_opts; -atlas_description; -atlas_name; -atlas_type; -auto_backup; -centers; -dset; -h_find; -h_view; -h_web; -hview; -hweb; -lab_file; -lab_file_delim; -space; ", 13},
{ "@Center_Distance", "", 0},
{ "@CheckForAfniDset", "", 0},
{ "@CommandGlobb", "", 0},
{ "@DO.examples", "-auto_test; ", 1},
{ "@DTI_studio_reposition", "", 0},
{ "@DeblankFileNames", "-demo_set; -dry_run; -echo; -help; -move; -nobrac; ", 6},
{ "@DiceMetric", "-base; -do_not_mask_by_base; -dsets; -echo; -forceoutput; -ignore_bad; -keep_tmp; -labeltable; -mask_by_base; -max_N_roi; -prefix; -save_diff; -save_match; ", 13},
{ "DoPerRoi.py", "", 0},
{ "@DriveAfni", "", 0},
{ "@DriveSuma", "-all_opts; -h_aspx; -h_find; -h_raw; -h_spx; -h_txt; -h_view; -h_web; -hview; -hweb; ", 8},
{ "@ElectroGrid", "-coords; -echo; -grid; -prefix; -strip; -with_markers; ", 6},
{ "@ExamineGenFeatDists", "-all_opts; -echo; -exclass; -exfeat; -fdir; -fwild; -h_find; -h_view; -h_web; -hview; -hweb; -help; -nx; -odir; -suffix; ", 13},
{ "@FS_roi_label", "", 0},
{ "@FSlabel2dset", "-echo; -fs; -help; -keep_tmp; -val; ", 5},
{ "@FindAfniDsetPath", "-help; ", 1},
{ "@FromRAI", "", 0},
{ "@FullPath", "", 0},
{ "@GetAfniBin", "", 0},
{ "@GetAfniDims", "", 0},
{ "@GetAfniID", "", 0},
{ "@GetAfniOrient", "", 0},
{ "@GetAfniPrefix", "", 0},
{ "@GetAfniRes", "", 0},
{ "@GetAfniView", "", 0},
{ "@Install_AfniRetinoDemo", "", 0},
{ "@Install_ClustScat_Demo", "", 0},
{ "@Install_FATCAT_DEMO", "-curl; -wget; ", 2},
{ "@Install_FATMVM_DEMO", "", 0},
{ "@Install_InstaCorr_Demo", "-curl; -full; -mini; -wget; ", 4},
{ "@Install_MEICA_Demo", "", 0},
{ "@Install_RSFMRI_Motion_Group_Demo", "-; ", 1},
{ "@Install_TSrestMovieDemo", "", 0},
{ "@IsoMasks", "", 0},
{ "@MakeLabelTable", "-LT_to_atlas_PL; -add_atlas_dset; -all_keys; -all_labels; -all_opts; -atlas_description; -atlas_file; -atlas_name; -atlas_pointlist; -atlasize_labeled_dset; -centers; -dset; -dset_LT_to_atlas_PL; -h_find; -h_view; -h_web; -hview; -hweb; -klabel; -lab_file; -lab_file_delim; -lab_r; -lab_v; -labeltable; -labeltable_of_dset; -lkeys; -match_label; -quiet_death; -replace; -rkeys; -word_label_match; ", 29},
{ "@NoExt", "", 0},
{ "@NoPound", "", 0},
{ "@NoisySkullStrip", "-3dSkullStrip_opts; -all_opts; -h_find; -h_view; -h_web; -hview; -hweb; -input; -keep_tmp; ", 7},
{ "@Purify_1D", "-sub; -suf; ", 2},
{ "@Quiet_Talkers", "-all_opts; -h_find; -h_view; -h_web; -hview; -hweb; -list; -no_npb; -npb_range; -npb_val; -pif; -prog; -quiet; -sudo; ", 12},
{ "@ROI_Corr_Mat", "-dirty; -echo; -keep_tmp; -mat; -prefix; -roi; -roisel; -ts; -verb; -zval; ", 10},
{ "@R_funclist", "", 0},
{ "@RenamePanga", "-i; -kp; -oc; -od; -sp; ", 5},
{ "@Reorder", "-help; -input; -mapfile; -offset; -prefix; -save_work; -test; ", 7},
{ "@RetinoProc", "-A2E_opts; -AEA_opts; -TR; -anat_vol; -anat_vol@epi; -ccw; -ccw_orts; -clw; -clw_orts; -con; -con_orts; -delay; -dorts; -echo; -echo_edu; -epi_anat_ref; -epi_ref; -exp; -exp_orts; -fetch_demo; -fwhm_ecc; -fwhm_pol; -gm; -ignore; -install_demo; -layer; -lh_ccw; -lh_clw; -lh_con; -lh_exp; -midlayer; -noVR; -no_tshift; -no_volreg; -nrings; -nwedges; -on_ecc; -on_pol; -out_dir; -period_ecc; -period_pol; -phase; -pial; -pre_ecc; -pre_pol; -sid; -spec_left; -spec_right; -surf_vol; -surf_vol@epi; -var_on_ecc; -var_on_pol; -wm; ", 53},
{ "@SUMA_AlignToExperiment", "-EA_clip_below; -al; -al_opt; -align_centers; -all_opts; -atlas_followers; -dxyz; -echo; -exp_anat; -followers_interp; -h_find; -h_view; -h_web; -hview; -hweb; -init_xform; -keep_tmp; -ok_change_view; -out_dxyz; -overwrite_resp; -prefix; -skull_strip_opt; -strip_skull; -surf_anat; -surf_anat_followers; -wd; ", 24},
{ "@SUMA_FSvolToBRIK", "", 0},
{ "@SUMA_Make_Spec_Caret", "-debug; -echo; -help; -sfpath; -sid; -side_labels_style; ", 6},
{ "@SUMA_Make_Spec_FS", "-GIFTI; -GNIFTI:Produce; -IFTI; -NIFTI; -debug; -fspath; -help; -inflate; -ld; -ldpref; -neuro; -no_ld; -nocor; -set_space; -sid; -use_mgz; ", 16},
{ "@SUMA_Make_Spec_SF", "-debug; -help; -sfpath; -sid; ", 4},
{ "@ScaleVolume", "-all_opts; -feat_norm; -feat_znorm; -h_find; -h_view; -h_web; -hview; -hweb; -input; -mask; -norm; -perc_clip; -prefix; -scale_by_mean; -scale_by_median; -val_clip; ", 14},
{ "@ScriptCheck", "-clean; -suffix; ", 2},
{ "@Shift_Volume", "-MNI_Anat_to_MNI; -MNI_to_MNI_Anat; -dset; -no_cp; -prefix; -rai_shift; ", 6},
{ "@ShowDynamicRange", "", 0},
{ "@Spharm.examples", "-all_opts; -h_find; -h_view; -h_web; -hview; -hweb; ", 4},
{ "@SurfSmooth.HEAT_07.examples", "", 0},
{ "@T1scale", "-PD; -T1; -align; -all_opts; -echo; -h_find; -h_view; -h_web; -hview; -hweb; -head_mask; -help; -mask; -masked_uni; -odir; -unmasked_uni; ", 14},
{ "@TimeDiff", "", 0},
{ "@ToRAI", "", 0},
{ "@UpdateAfni", "", 0},
{ "@VolCenter", "-or; ", 1},
{ "@afni.run.me", "-curl; -go; -help; ", 3},
{ "@align_partial_oblique", "-base; -clean; -dx; -dxyz; -dy; -dz; -input; -keep_tmp; -suffix; ", 9},
{ "@auto_align", "", 0},
{ "@auto_tlrc", "-OK_maxite; -all_opts; -apar; -base; -base_copy; -base_list; -clean; -dx; -dxyz; -dy; -dz; -h_find; -h_view; -h_web; -hview; -hweb; -init_xform; -input; -inweight; -keep_tmp; -keep_view; -maxite; -ncr; -no_avoid_eyes; -no_pre; -no_ss; -onepass; -onewarp; -out_space; -overwrite; -pad_base; -pad_input; -rigid_equiv; -rmode; -suffix; -twopass; -verb; -warp_orig_vol; -xform; ", 37},
{ "@build_afni_Xlib", "-afniX; -g; -lib32; -lib64; -localinstall; ", 5},
{ "@clean_help_dir", "", 0},
{ "@clip_volume", "-above; -and; -anterior; -below; -box; -crop; -crop_allzero; -crop_greedy; -followers; -input; -left; -mask_box; -or; -posterior; -prefix; -right; -verb; ", 17},
{ "@compute_gcor", "-corr_vol; -help; -hist; -input; -mask; -nfirst; -no_demean; -savetmp; -ver; -verb; ", 10},
{ "@demo_prompt", "", 0},
{ "@escape-", "", 0},
{ "@fast_roi", "-anat; -anat_ns; -base; -drawn_roi; -help; -prefix; -region; -roi_grid; -time; -twopass; ", 10},
{ "@fix_FSsphere", "-lim; -niter; -project_first; -spec; -sphere; ", 5},
{ "@float_fix", "", 0},
{ "@global_parse", "", 0},
{ "@help.AFNI", "-less; -lynx; -match; -nedit; -noview; -vi; ", 6},
{ "@isOblique", "", 0},
{ "@make_plug_diff", "-abin; -asrc; -comments; -diff; -linux; -vtk; -xm; ", 7},
{ "@make_stim_file", "-debug; -help; -maxreps; -no_headers; -outfile; -zero_based; ", 6},
{ "@move.to.series.dirs", "-action; -dprefix; -help; -hist; -tag; -test; -ver; ", 7},
{ "@np", "", 0},
{ "@parse_afni_name", "", 0},
{ "@parse_name", "", 0},
{ "@radial_correlate", "-cthesh; -do_clust; -do_corr; -frac_limit; -help; -hist; -min_thr; -nfirst; -percentile; -rdir; -sphere_rad; -ver; ", 12},
{ "@simulate_motion", "-epi; -epi_timing; -help; -hist; -motion_file; -prefix; -save_workdir; -test; -todo; -ver; -verb; -vr_base; -warp_1D; -warp_master; -warp_method; -wsinc5; ", 16},
{ "@statauxcode", "", 0},
{ "@toMNI_Awarp", "", 0},
{ "@toMNI_Qwarpar", "", 0},
{ "@update.afni.binaries", "-apsearch; -bindir; -curl; -d; -defaults; -help; -help_sys_progs; -no_recur; -package; -prog_list; -quick; -sys_ok; -test; ", 13},
{ "AFNI_Batch_R", "", 0},
{ "AlphaSim", "-approx; -ax; -ay; -az; -dx; -dxyz; -dy; -dz; -fast; -fwhm; -fwhmx; -fwhmy; -fwhmz; -iter; -mask; -max_clust_size; -nx; -nxyz; -ny; -nz; -out; -power; -pthr; -quiet; -rmm; -seed; -sigma; -sigmax; -sigmay; -sigmaz; -zsep; ", 31},
{ "AnalyzeTrace", "", 0},
{ "BrainSkin", "", 0},
{ "CompareSurfaces", "-HELP; -TRACE; -all_opts; -h; -h_aspx; -h_find; -h_raw; -h_spx; -h_view; -h_web; -hview; -hweb; -help; -hemi; -nocons; -noderange; -nomall; -novolreg; -noxform; -onenode; -prefix; -setenv; -spec; -sv1; -sv2; -trace; -yesmall; ", 25},
{ "ConvertDset", "", 0},
{ "ConvertSurface", "", 0},
{ "ConvexHull", "", 0},
{ "CreateIcosahedron", "-ctr; -help; -ld; -min_nodes; -nums; -nums_quiet; -prefix; -rad; -rd; -tosphere; ", 10},
{ "DTIStudioFibertoSegments", "-output; -swap; ", 2},
{ "Dimon", "-GERT_Reco; -debug; -dicom_org; -drive_afni; -drive_wait; -epsilon; -fast; -file_type; -gert_create_dataset; -gert_filename; -gert_nz; -gert_outdir; -gert_quit_on_err; -gert_to3d_prefix; -gert_write_as_nifti; -help; -hist; -host; -infile_list; -infile_pattern; -infile_prefix; -max_images; -max_quiet_trs; -nice; -no_wait; -nt; -num_chan; -num_slices; -pause; -quiet; -quit; -rev_byte_order; -rev_org_dir; -rev_sort_dir; -rt; -rt_cmd; -save_details; -save_errors; -save_file_list; -show_sorted_list; -sleep_frac; -sleep_init; -sleep_vol; -sort_by_acq_time; -sort_by_num_suffix; -sort_method; -sp; -start_file; -swap; -tr; -use_imon; -use_last_elem; -use_slice_loc; -version; -zorder; ", 55},
{ "Dimon1", "-GERT_Reco; -debug; -dicom_org; -drive_afni; -drive_wait; -epsilon; -fast; -file_type; -gert_create_dataset; -gert_filename; -gert_nz; -gert_outdir; -gert_quit_on_err; -gert_to3d_prefix; -gert_write_as_nifti; -help; -hist; -host; -infile_list; -infile_pattern; -infile_prefix; -max_images; -max_quiet_trs; -nice; -no_wait; -nt; -num_chan; -num_slices; -pause; -quiet; -quit; -rev_byte_order; -rev_org_dir; -rev_sort_dir; -rt; -rt_cmd; -save_file_list; -show_sorted_list; -sleep_frac; -sleep_init; -sleep_vol; -sort_by_acq_time; -sort_by_num_suffix; -sp; -start_file; -swap; -tr; -use_imon; -use_last_elem; -use_slice_loc; -version; -zorder; ", 52},
{ "DriveSuma", "", 0},
{ "ExamineXmat", "-cprefix; -h; -help; -input; -interactive; -msg.trace; -pprefix; -prefix; -select; -show_allowed_options; -verb; ", 11},
{ "FD2", "-cf; -d; -extra; -fim_colors; -fmag; -gam; -geom; -grid; -gsize; -ideal; -im1; -nc; -num; -pcthresh; -phase; -sp; -swap; ", 17},
{ "FIRdesign", "-TR; -band; -ntap; ", 3},
{ "FSread_annot", "-FScmap; -FScmaprange; -FSversion; -cmap_1D; -col_1D; -dset; -help; -hemi; -input; -roi_1D; -show_FScmap; ", 11},
{ "HalloSuma", "", 0},
{ "Ifile", "-nt; -od; -sp; ", 3},
{ "InstaTract", "", 0},
{ "IsoSurface", "", 0},
{ "MakeColorMap", "", 0},
{ "MapIcosahedron", "-NN_dset_map; -all_surfs_spec; -check_cut_surfaces; -dset_map; -fix_cut_surfaces; -forget_cut_surface; -it; -ld; -morph; -morph_sphere_check; -no_nodemap; -prefix; -rd; -spec; -sph_check; -sph_check]:(OBSOLETE; -sphere_at_origin; -sphere_center; -sphere_radius; -sphreg_check; -use_com; -verb; -write_nodemap; ", 23},
{ "ParseName", "-app; -cwd; -out; -outsep; -pre; ", 5},
{ "ROI2dataset", "-dom_par_id; -h; -input; -keep_separate; -label_dset; -nodelist; -nodelist.nodups; -nodelist_with_ROIval; -of; -pad_label; -pad_to_node; -prefix; ", 12},
{ "ROIgrow", "", 0},
{ "RSFgen", "-markov; -nblock; -nreps; -nt; -num_stimts; -one_col; -one_file; -prefix; -pseed; -pzero; -quiet; -seed; -table; ", 13},
{ "SUMA_glxdino", "", 0},
{ "SUMA_paperplane", "", 0},
{ "SUMA_pixmap2eps", "", 0},
{ "SampBias", "", 0},
{ "ScaleToMap", "", 0},
{ "SpharmDeco", "", 0},
{ "SpharmReco", "", 0},
{ "Surf2VolCoord", "", 0},
{ "SurfClust", "", 0},
{ "SurfDist", "", 0},
{ "SurfDsetInfo", "", 0},
{ "SurfExtrema", "", 0},
{ "SurfFWHM", "", 0},
{ "SurfInfo", "", 0},
{ "SurfMeasures", "-cmask; -debug; -dnode; -func; -help; -hist; -info_all; -info_area; -info_norms; -info_thick; -info_vol; -info_volg; -nodes_1D; -out; -out_1D; -spec; -surf_A; -surf_B; -sv; -ver; ", 20},
{ "SurfMesh", "-HELP; -TRACE; -all_opts; -anatomical; -edges; -h; -h_aspx; -h_find; -h_raw; -h_spx; -h_view; -h_web; -hview; -hweb; -help; -i; -i_TYPE; -nomall; -novolreg; -noxform; -o_TYPE; -o_sf.; -onestate; -setenv; -spec; -surf_A; -sv; -tn; -trace; -tsn; -yesmall; ", 29},
{ "SurfPatch", "", 0},
{ "SurfQual", "", 0},
{ "SurfRetinoMap", "", 0},
{ "SurfSmooth", "", 0},
{ "SurfToSurf", "", 0},
{ "SurfaceMetrics", "", 0},
{ "Vecwarp", "-apar; -backward; -force; -forward; -input; -matvec; -output; -x; -y; -z; ", 10},
{ "Xphace", "", 0},
{ "abut", "-blocky; -dzin; -dzout; -linear; -root; -skip; ", 6},
{ "adwarp", "-apar; -dpar; -dxyz; -force; -func; -prefix; -resam; -thr; -verbose; ", 9},
{ "afni", "", 0},
{ "afni_history", "-author; -check_date; -dline; -help; -hist; -html; -level; -list_authors; -list_types; -min_level; -past_days; -past_entries; -past_months; -past_years; -program; -reverse; -type; -ver; -verb; ", 19},
{ "afni_open", "", 0},
{ "afni_proc.py", "--; -align_epi_ext_dset; -align_epi_strip_method; -align_opts_aea; -anat_has_skull; -anat_opts_unif; -anat_unif_GM; -anat_uniform_method; -ask_me; -bash; -blocks; -blur_filter; -blur_in_automask; -blur_in_mask; -blur_opts_B2FW; -blur_opts_BIM; -blur_opts_merge; -blur_size; -blur_to_fwhm; -check_afni_version; -check_results_dir; -check_setup_errors; -copy_anat; -copy_anat.; -copy_files; -despike_mask; -despike_opts_3dDes; -do_block; -dsets; -e; -epi_base; -execute; -f; -gen_epi_review; -giant_move; -help; -hist; -iresp; -keep_rm_files; -mask_apply; -mask_dilate; -mask_rm_segsy; -mask_segment_anat; -mask_segment_erode; -mask_segment_erode.; -mask_test_overlap; -mask_type; -move_preproc_files; -no_epi_review; -no_proc_command; -ortvec; -out_dir; -outlier_count; -outlier_legendre; -outlier_polort; -regress_3dD_stop; -regress_CS_NN; -regress_ROI; -regress_RONI; -regress_RSFC; -regress_anaticor; -regress_anaticor.; -regress_anaticor_fast; -regress_anaticor_fwhm; -regress_anaticor_radius; -regress_apply_mask; -regress_apply_mot_types; -regress_apply_ricor; -regress_bandpass; -regress_basis; -regress_basis_normall; -regress_censor_extern; -regress_censor_first_trs; -regress_censor_motion; -regress_censor_outliers; -regress_censor_prev; -regress_compute_fitts; -regress_compute_gcor; -regress_compute_tsnr; -regress_cormat_warnings; -regress_errts_prefix; -regress_est_blur_epits; -regress_est_blur_errts; -regress_extra_stim_files; -regress_extra_stim_labels; -regress_fitts_prefix; -regress_fout; -regress_global_times; -regress_iresp_prefix; -regress_local_times; -regress_make_cbucket; -regress_make_ideal_sum; -regress_mot_as_ort; -regress_motion_file; -regress_motion_per_run; -regress_no_fitts; -regress_no_ideal_sum; -regress_no_ideals; -regress_no_iresp; -regress_no_mask; -regress_no_motion; -regress_no_motion_demean; -regress_no_motion_deriv; -regress_opts_3dD; -regress_opts_CS; -regress_opts_CS.; -regress_opts_reml; -regress_polort; -regress_reml_exec; -regress_run_clustsim; -regress_skip_first_outliers; -regress_stim_files; -regress_stim_labels; -regress_stim_labels.; -regress_stim_times; -regress_stim_times_offset; -regress_stim_types; -regress_stim_types.; -regress_use_stim_files; -remove_preproc_files; -requires_afni_version; -ricor_datum; -ricor_polort; -ricor_regress_method; -ricor_regress_solver; -ricor_regs; -ricor_regs_nfirst; -ricor_regs_rm_nlast; -scale_max_val; -scale_no_max; -scr_overwrite; -script; -sep_char; -show_valid_opts; -stim_file; -stim_files; -subj_curly; -subj_id; -surf_A; -surf_B; -surf_anat; -surf_blur_fwhm; -surf_spec; -tcat_preSS_warn_limit; -tcat_remove_first_trs; -tcat_remove_last_trs; -test_for_dsets; -test_stim_files; -tlrc_NL_awpy_rm; -tlrc_NL_warp; -tlrc_anat; -tlrc_base; -tlrc_no_ss; -tlrc_opts_at; -tlrc_rmode; -tlrc_suffix; -tshift_align_to; -tshift_align_to.; -tshift_interp; -tshift_opts_ts; -ver; -verb; -volreg_align_e2a; -volreg_align_to; -volreg_base_dset; -volreg_base_dset.; -volreg_base_ind; -volreg_compute_tsnr; -volreg_interp; -volreg_motsim; -volreg_no_extent_mask; -volreg_opts_ms; -volreg_opts_vr; -volreg_regress_per_run; -volreg_tlrc_adwarp; -volreg_tlrc_warp; -volreg_warp_dxyz; -volreg_zpad; -write_3dD_prefix; -write_3dD_script; -x; ", 181},
{ "afni_restproc.py", "-Cexpr; -align; -alignbase; -anat; -anat_has_skull; -apply_censor; -aseg; -bandpass; -bpassregs; -censorleft; -censorright; -censorunion; -changelog; -corrmap; -corrmapt; -despike[on]; -off:Despike; -dest; -dreg; -dvarscensor; -dvarslimit; -epi; -epi2anat; -episize; -exec; -fdlimit; -fraclimit; -globalnorm; -globalregmask; -globalwm; -help; -includebrain; -keepuncensored; -localnorm; -localregmask; -mean; -modenorm; -motlimit; -normval; -outcensor; -polort; -polort.; -prefix; -regressor; -rvt; -script; -setbands; -smooth; -smoothfirst; -smoothrad; -smoothtogether; -snr; -tlrc; -tlrclast; -trcut; -tsnr; -uniformize; -venterode; -wmerode; -wmsize; ", 60},
{ "afni_run_R", "", 0},
{ "afni_skeleton.py", "-help; -hist; -infiles; -ver; ", 4},
{ "afni_system_check.py", "-casematch; -check_all; -data_root; -exact; -find_prog; -help; -hist; -show_valid_opts; -todo; -ver; ", 10},
{ "afni_util.py", "-eval; -float; -help; -join; -listfunc; -lprint; -print; ", 7},
{ "afni_vcheck", "", 0},
{ "aiv", "", 0},
{ "align_epi_anat.py", "-AddEdge; -Allineate_opts; -align_centers; -anat; -anat2epi; -anat_has_skull; -auto_tlrc; -big_move; -bin_mask; -box_mask; -check_cost; -child_anat; -child_dset1; -child_dset2; -child_epi; -cmass; -cost; -deoblique; -deoblique_opts; -dset1; -dset1_strip; -dset1to2; -dset2; -dset2_base; -dset2_strip; -dset2to1; -edge; -edge_erodelevel; -epi; -epi2anat; -epi_base; -epi_strip; -ex_mode; -feature_size; -giant_move; -ginormous_move; -help; -keep_rm_files; -limited_help; -mask; -master_anat; -master_anat_dxyz; -master_dset1; -master_dset1_dxyz; -master_dset2; -master_dset2_dxyz; -master_epi; -master_epi_dxyz; -master_tlrc; -master_tlrc_dxyz; -multi_cost; -option_help; -output_dir; -overwrite; -partial_axial; -partial_coronal; -partial_coverage; -partial_sagittal; -perc; -post_matrix; -pow_mask; -pre_matrix; -prep_off; -prep_only; -rat_align; -resample; -save_Al_in; -save_all; -save_epi_ns; -save_orig_skullstrip; -save_rep; -save_resample; -save_script; -save_skullstrip; -save_tsh; -save_vr; -save_xxx; -skullstrip_opts; -suffix; -tlrc_apar; -tlrc_epar; -tshift; -tshift_opts; -ver; -verb; -version; -volreg; -volreg_base; -volreg_method; -volreg_opts; ", 90},
{ "apsearch", "-; -C_all_append_prog_opt_array; -C_all_prog_opt_array; -C_prog_opt_array; -Dname=val; -HELP; -Vname=; -afni_bin_dir; -afni_custom_atlas_dir; -afni_custom_atlas_file; -afni_data_dir; -afni_help_dir; -afni_home_dir; -afni_rc_file; -afni_text_editor; -afni_web_browser; -afni_web_downloader; -all_afni_help; -all_opts; -all_popts; -apsearch_log_file; -asphinx_phelp; -bash; -ci; -cs; -doc_2_spx; -doc_2_txt; -doc_markup_sample; -echo_edu; -file; -files; -func_test; -global_help; -gopts_help; -h; -h_aspx; -h_find; -h_raw; -h_spx; -h_view; -h_web; -hview; -hweb; -hdoc_2_aspx; -hdoc_2_spx; -hdoc_2_txt; -help; -list_all_afni_P_dsets; -list_all_afni_P_progs; -list_all_afni_P_readmes; -list_all_afni_dsets; -list_all_afni_progs; -list_all_afni_readmes; -list_popts; -m; -max_hits; -min_different_hits; -ok_1D_text; -overwrite; -pad_to_node; -phelp; -pif; -popt; -popts_complete_command; -race_check; -raw_phelp; -recreate_all_afni_help; -show_score; -show_score_detail; -skip_afnirc; -sphinx_phelp; -stdin; -test_unique_str; -text; -txt_phelp; -unique_hits_only; -update_all_afni_help; -view_prog_help; -view_readme; -view_text_file; -w; -web_class_docs; -web_prog_help; -wild_all_files; -wild_files; -wild_files_ci; -wild_files_debug; -wild_files_noAext; -wild_files_noAext_noAview; -wild_files_orig_name; -word; ", 89},
{ "auto_warp.py", "-affine_dxyz; -affine_followers_xmat; -affine_input_xmat; -base; -child_anat; -ex_mode; -followers; -help; -input; -keep_rm_files; -limited_help; -option_help; -output_dir; -overwrite; -prep_only; -qblur; -qw_opts; -qworkhard; -save_script; -skip_affine; -skull_strip_base; -skull_strip_input; -smooth_anat; -smooth_base; -suffix; -unifize_input; -ver; -verb; -version; -warp_dxyz; ", 30},
{ "byteorder", "", 0},
{ "cat_matvec", "-1; -4x4; -I; -IP; -MATRIX; -ONELINE; -P; -S; ", 8},
{ "ccalc", "-eval; -form; ", 2},
{ "cdf", "", 0},
{ "cjpeg", "-baseline; -dct; -grayscale; -maxmemory; -optimize; -outfile; -progressive; -qslots; -qtables; -quality; -restart; -sample; -scans; -smooth; -targa; -verbose; ", 16},
{ "column_cat", "-line; -sep; ", 2},
{ "count", "-column; -comma; -digits; -form; -root; -scale; -seed; -sep; -skipnmodm; -sseed; -suffix; ", 11},
{ "demo.fixed.niml.do", "", 0},
{ "demo.mobile.niml.do", "", 0},
{ "dicom_hdr", "-hex; -mulfram; -no_length; -noname; -sexinfo; -slice_times; -slice_times_verb; -v; ", 8},
{ "dicom_hinfo", "-namelast; -no_name; -tag; ", 3},
{ "dicom_to_raw", "", 0},
{ "djpeg", "-bmp; -colors; -dct; -dither; -fast; -gif; -grayscale; -map; -maxmemory; -nosmooth; -onepass; -os2; -outfile; -pnm; -scale; -targa; -verbose; ", 17},
{ "eg_main_chrono.py", "-help; -hist; -show_valid_opts; -ver; -verb; ", 5},
{ "ent16", "", 0},
{ "fat_lat_csv.py", "", 0},
{ "fat_mat_sel.py", "-A; -B; -C; -E; -F; -H; -L; -M; -O; -P; -S; -T; -c; -d; -l; -m; -o; -s; -t; -w; -x; -y; ", 22},
{ "fat_mvm_gridconv.py", "-l; -m; ", 2},
{ "fat_mvm_prep.py", "", 0},
{ "fat_mvm_review.py", "", 0},
{ "fat_mvm_scripter.py", "", 0},
{ "fat_roi_row.py", "-E; -l; -m; -r; ", 4},
{ "fdrval", "-inverse; -ponly; -pval; -qinput; -qonly; ", 5},
{ "fftest", "", 0},
{ "file_tool", "-debug; -def_ana_hdr; -diff_ana_hdrs; -disp_ana_hdr; -disp_hex; -disp_hex1; -disp_hex2; -disp_hex4; -disp_int2; -disp_int4; -disp_real4; -ge4_all; -ge4_image; -ge4_series; -ge4_study; -ge_all; -ge_extras; -ge_header; -ge_off; -ge_run; -ge_uv17; -help; -hex; -hist; -infiles; -length; -mod_ana_hdr; -mod_data; -mod_field; -mod_type; -offset; -overwrite; -prefix; -quiet; -show_bad_all; -show_bad_backslash; -show_bad_char; -show_file_type; -swap_bytes; -test; -version; ", 41},
{ "fim2", "-clean; -clip; -cnrfile; -coef; -corfile; -corr; -dfspace[:0; -fimfile; -fitfile; -flim; -ideal; -im1; -non; -num; -ort; -pcnt; -pcthresh; -polref; -q; -regbase; -sigfile; -subort; ", 22},
{ "float_scan", "-fix; -skip; -v; ", 3},
{ "from3d", "-float; -input; -nsize; -prefix; -raw; -tfirst; -tlast; -v; -zfirst; -zlast; ", 10},
{ "ftosh", "-base; -nsize; -prefix; -scale; -start; -step; -suffix; -top; ", 8},
{ "ge_header", "-verb; ", 1},
{ "gen_epi_review.py", "-dsets; -gr_size; -gr_xoff; -gr_yoff; -help; -hist; -im_size; -im_xoff; -im_yoff; -script; -show_valid_opts; -ver; -verb; -windows; ", 14},
{ "gen_group_command.py", "-AminusB; -command; -dset_index0_list; -dset_index1_list; -dsets; -factors; -help; -hist; -keep_dirent_pre; -options; -prefix; -set_labels; -show_valid_opts; -subj_prefix; -subj_suffix; -subs_betas; -subs_tstats; -type; -ver; -verb; -write_script; ", 21},
{ "gen_ss_review_scripts.py", "-enorm_dset; -exit0; -final_anat; -final_view; -help; -hist; -mot_limit; -motion_dset; -num_stim; -out_limit; -outlier_dset; -prefix; -rm_trs; -show_uvar_dict; -show_uvar_eg; -show_valid_opts; -stats_dset; -subj; -uvar; -ver; -verb; -xmat_regress; -xmat_uncensored; ", 23},
{ "gen_ss_review_table.py", "-help; -hist; -infiles; -overwrite; -separator; -showlabs; -tablefile; -ver; -verb; ", 9},
{ "gifti_tool", "-1; -DA_index_list; -approx_gifti; -b64_check; -buf_size; -compare_data; -compare_gifti; -compare_verb; -copy_DA_meta; -copy_gifti_meta; -encoding; -gifti_dtd_url; -gifti_hist; -gifti_test; -gifti_ver; -gifti_zlib; -help; -hist; -infile; -mod_DA_atr; -mod_DA_meta; -mod_DAs; -mod_add_data; -mod_gim_atr; -mod_gim_meta; -mod_to_float; -new_data; -new_dims; -new_dset; -new_dtype; -new_intent; -new_ndim; -new_numDA; -no_data; -no_updates; -read_DAs; -set_extern_filelist; -show_gifti; -ver; -verb; -write_1D; -write_asc; -write_gifti; -zlevel; ", 44},
{ "help_format", "", 0},
{ "im2niml", "", 0},
{ "imand", "", 0},
{ "imaver", "", 0},
{ "imcalc", "-a; -datum; -expr; -output; ", 4},
{ "2dcat", "-autocrop; -autocrop_atol; -autocrop_ctol; -crop; -gap; -gap_col; -gray_wrap; -gscale; -image_wrap; -matrix; -matrix_from_scale; -nx; -ny; -pad_val; -prefix; -rand_wrap; -res_in; -respad_in; -rgb_out; -scale_image; -scale_intensity; -scale_pixels; -white_wrap; -zero_wrap; ", 24},
{ "imcutup", "-prefix; -x.ynum; -xynum; -y.xnum; -yxnum; ", 5},
{ "imdump", "", 0},
{ "immask", "", 0},
{ "imreg", "-bilinear; -cmass; -debug; -dfspace[:0; -dprefix; -fine; -flim; -keepsize; -mlcF; -modes; -nofine; -nowrite; -prefix; -quiet; -start; -step; -suffix; -wtim; ", 18},
{ "imrotate", "-Fourier; -linear; ", 2},
{ "imstack", "-datum; -prefix; ", 2},
{ "imstat", "-nolabel; -pixstat; -quiet; ", 3},
{ "imupsam", "", 0},
{ "inspec", "-LRmerge; -detail; -h; -h; -help; -prefix; -remove_state; -spec; ", 8},
{ "lpc_align.py", "", 0},
{ "make_pq_script.py", "", 0},
{ "make_random_timing.py", "--; -across_runs; -help; -hist; -make_3dd_contrasts; -max_consec; -max_rest; -min_rest; -num_reps; -num_runs; -num_stim; -offset; -ordered_stimuli; -post_stim_rest; -pre_stim_rest; -prefix; -run_time; -save_3dd_cmd; -seed; -show_timing_stats; -show_valid_opts; -stim_dur; -stim_labels; -t_digits; -t_gran; -tr; -ver; -verb; ", 28},
{ "make_stim_times.py", "-1.2; -amplitudes; -labels; -no_consec; -nruns; -nt; -offset; -prefix; -run_trs; -show_valid_opts; -tr; -verb; ", 12},
{ "map_TrackID", "-already_inv; -in_map; -in_trk; -line_only_num; -orig_zero; -prefix; -ref; -verb; ", 8},
{ "mayo_analyze", "", 0},
{ "meica.py", "--MNI; --OVERWRITE; --TR=TR; --align_args=ALIGN_ARGS; --align_base=ALIGN_BASE; --coreg_mode=COREG_MODE; --cpus=CPUS; --daw=DAW; --fres=2.5; --fres=FRES; --keep_int; --label=LABEL; --mask_mode=MASK_MODE; --no_axialize; --no_despike; --no_skullstrip; --pp_only; --prefix=PREFIX; --qwarp; --script_only; --skip_check; --smooth; --smooth=FWHM; --space=SPACE; --ted_args=TED_ARGS; --test_proc; --tpattern=TPATTERN; -1; -a; -b; -d; -e; -h; ", 33},
{ "mpeg_encode", "-bit_rate_info; -combine_frames; -combine_gops; -float_dct; -frames; -gop; -max_machines; -mv_histogram; -nice; -no_frame_summary; -quiet; -realquiet; -snr; -stat; ", 14},
{ "mritopgm", "", 0},
{ "mycat", "", 0},
{ "myget", "", 0},
{ "neuro_deconvolve.py", "--; -help; -hist; -input; -kernel; -kernel_file; -mask_dset; -old; -prefix; -script; -show_valid_opts; -tr; -tr_nup; -ver; -verb; ", 15},
{ "nicat", "-R; -r; -reopen; ", 3},
{ "niccc", "-#; -attribute; -dup; -f; -find_nel_with_attr; -match; -nodata; -quiet; -s; -skip_nel_with_attr; -stdout; ", 11},
{ "nifti1_test", "-a2; -n1; -n2; -na; -za2; -zn1; -zn2; ", 7},
{ "nifti_tool", "-add_afni_ext; -add_comment_ext; -cbl; -cci; -check_hdr; -check_nim; -copy_brick_list; -copy_collapsed_image; -copy_im; -debug; -diff_hdr; -diff_nim; -disp_ana; -disp_ci; -disp_collapsed_image; -disp_exts; -disp_hdr; -disp_nim; -disp_ts; -field; -help; -help_ana; -help_datatypes; -help_hdr; -help_nim; -hist; -infiles; -keep_hist; -make_im; -mod_field; -mod_hdr; -mod_nim; -new_datatype; -new_dim; -nifti_hist; -nifti_ver; -overwrite; -prefix; -quiet; -rm_ext; -strip_extras; -swap_as_analyze; -swap_as_nifti; -swap_as_old; -ver; -with_zlib; ", 46},
{ "niml_feedme", "-accum; -drive; -dt; -host; -target; -verb; ", 6},
{ "niprobe", "-#; -No#; -attribute; -dup; -f; -find_nel_named; -find_nel_with_attr; -match; -mw; -nodata; -quiet; -s; -skip_nel_with_attr; -stderr; -stdout; ", 15},
{ "nsize", "", 0},
{ "plugout_drive", "-com; -host; -maxwait; -name; -np; -npb; -npq; -port; -quit; -shm; -v; ", 11},
{ "plugout_ijk", "-host; -max_port_bloc; -max_port_bloc_quiet; -name; -np; -npb; -npq; -num_assigned_ports; -num_assigned_ports_quiet; -port; -v; ", 11},
{ "plugout_tt", "-host; -ijk; -max_port_bloc; -max_port_bloc_quiet; -name; -np; -npb; -npq; -num_assigned_ports; -num_assigned_ports_quiet; -port; -v; ", 12},
{ "plugout_tta", "-host; -max_port_bloc; -max_port_bloc_quiet; -np; -npb; -npq; -num_assigned_ports; -num_assigned_ports_quiet; -port; -v; ", 10},
{ "prompt_user", "-pause; -timeout; -to; ", 3},
{ "python_module_test.py", "-full_test; -help; -hist; -platform_info; -python_ver; -show_valid_opts; -test_defaults; -test_modules; -ver; -verb; ", 10},
{ "qdelaunay", "", 0},
{ "qhull", "", 0},
{ "quick.alpha.vals.py", "-niter; ", 1},
{ "quickspec", "-h; -spec; -tn; -tsn; -tsnad; -tsnadl; -tsnadm; ", 7},
{ "quotize", "", 0},
{ "rPkgsInstall", "-check; -help; -pkgs; -remove; -show_allowed_options; -site; -update; ", 7},
{ "rbox", "", 0},
{ "read_matlab_files.py", "-help; -hist; -infiles; -overwrite; -prefix; -ver; ", 6},
{ "realtime_receiver.py", "-data_choice; -dc_params; -help; -hist; -serial_port; -show_comm_times; -show_data; -show_demo_data; -show_demo_gui; -show_valid_opts; -swap; -tcp_port; -ver; -verb; ", 14},
{ "rmz", "", 0},
{ "rotcom", "-x; -y; -z; ", 3},
{ "rtfeedme", "-3D; -buf; -drive; -dt; -gyr; -host; -note; -nzfake; -swap2; -verbose; ", 10},
{ "serial_helper", "-debug; -disp_all; -help; -hist; -mp_max; -mp_min; -no_serial; -num_extra; -serial_port; -show_times; -sock_num; -version; ", 12},
{ "sfim", "-base; -localbase; -prefix; -sfint; ", 4},
{ "siemens_vision", "-rename; ", 1},
{ "slow_surf_clustsim.py", "-help; -hist; -on_surface; -print_script; -save_script; -show_default_cvars; -show_default_uvars; -show_valid_opts; -uvar; -ver; -verb; ", 11},
{ "sqwave", "-init; ", 1},
{ "strblast", "-help; -new_char; -new_string; -quiet; -unescape; ", 5},
{ "suma", "", 0},
{ "suma_change_spec", "-domainparent; ", 1},
{ "tfim", "-eqcorr; -paired; -prefix; -pthresh; ", 4},
{ "timing_tool.py", "-add_offset; -add_rows; -chrono; -extend; -global_to_local; -help; -help_basis; -hist; -local_to_global; -min_frac; -multi_show_isi_stats; -multi_show_timing_ele; -multi_stim_dur; -multi_timing; -multi_timing_to_event_list; -multi_timing_to_event_pair; -multi_timing_to_events; -nplaces; -part_init; -partition; -per_run; -round_times; -run_len; -scale_data; -show_isi_stats; -show_timing; -show_timing_ele; -show_tr_stats; -show_valid_opts; -sort; -stim_dur; -stim_times; -test_local_timing; -timing; -timing_to_1D; -tr; -transpose; -truncate_times; -ver; -verb; -warn_tr_stats; -write_all_rest_times; -write_timing; ", 43},
{ "to3d", "-'type'; -2swap; -4swap; -8swap; -Torg; -anatparent; -assume_dicom_mosaic; -datum; -gamma; -geomparent; -gsfac; -help; -in:1; -ncolors; -nofloatscan; -nosave; -oblique_origin; -orient; -prefix; -quit_on_err; -reverse_list; -save_outliers; -session; -skip_outliers; -statpar; -t=Hz; -t=ms; -t=s; -text_outliers; -time:zt; -use_last_elem; -use_old_mosaic_code; -ushort2float; -view; -xFOV; -xSLAB; -xtwarns; -zorigin; -zpad; ", 39},
{ "uber_align_test.py", "", 0},
{ "uber_proc.py", "", 0},
{ "uber_skel.py", "", 0},
{ "uber_subject.py", "-align_cost; -align_giant_move; -align_opts_aea; -anal_domain; -anal_type; -anat; -blocks; -blur_size; -compute_fitts; -cvar; -epi; -epi_wildcard; -exec_ap_command; -exec_proc_script; -get_tlrc; -gid; -gltsym; -gltsym_label; -help; -help_gui; -help_howto_program; -help_install; -help_install_nokia; -hist; -motion_limit; -no_gui; -outlier_limit; -print_ap_command; -qt_opts; -regress_GOFORIT; -regress_bandpass; -regress_jobs; -regress_mot_deriv; -regress_opts_3dD; -reml_exec; -run_clustsim; -save_ap_command; -show_default_vars; -show_svar_dict; -show_valid_opts; -sid; -stim; -stim_basis; -stim_label; -stim_type; -stim_wildcard; -svar; -tcat_nfirst; -tlrc_base; -tlrc_ok_maxite; -tlrc_opts_at; -tlrc_ss; -ver; -verb; -volreg_base; ", 55},
{ "uber_ttest.py", "", 0},
{ "waver", "-EXPR; -FILE; -GAM; -TR; -WAV; -delaytime; -dt; -falltime; -gamb; -gamc; -gamd; -inline; -input; -numout; -peak; -restoretime; -risetime; -tstim; -undershoot; -ver; -when; -xyout; ", 22},
{ "whereami", "", 0},
{ "whirlgif", "-i; -loop; -o; -time; -trans; -v; ", 6},
{ "xmat_tool.py", "-choose_cols; -chrono; -cormat_cutoff; -cosmat_cutoff; -cosmat_motion; -gui_plot_xmat_as_one; -help; -help_gui; -hist; -load_1D; -load_xmat; -no_gui; -show_1D; -show_col_types; -show_conds; -show_cormat; -show_cormat_warnings; -show_cosmat; -show_cosmat_warnings; -show_fit_betas; -show_fit_ts; -show_valid_opts; -show_xmat; -test; -test_libs; -ver; -verb; ", 27},
   {  NULL, NULL, 0  }
};

#endif


#endif /* For #ifdef PROG_OPTS_INCLUDED */
