static char * readme_afnigui[] = {
   "================================================================================\n" ,
   "                             Tips for the AFNI GUI\n" ,
   "================================================================================\n" ,
   "(1) On most systems, the X11 cursor used in AFNI is an orange arrow pointing\n" ,
   "    at about '10:30' on the clock face.  However, the arrow becomes yellow\n" ,
   "    and points more steeply, to about '11:00', when it is over a location that\n" ,
   "    has a hidden Right-Click popup menu.  Some of these are\n" ,
   "   (a) Over the logo square just to the right of the 'done' button in an\n" ,
   "       AFNI controller.\n" ,
   "   (b) Over the labels at the top of the threshold slider and color bar in\n" ,
   "       the 'Define Overlay' control panel.\n" ,
   "   (c) On the label to the left of a drop-down 'option menu'; e.g., 'Xhairs'\n" ,
   "       or 'ULay' (for these menus, the cursor will not change shape).\n" ,
   "   (d) Over the color bar itself, when it is in continuous 'colorscale' mode\n" ,
   "       ('**') -- but not when it is in discrete color panel mode.\n" ,
   "   (e) Over the image viewer main sub-window, which holds the image itself.\n" ,
   "   (f) Over the image viewer intensity bar, just to the right of the image.\n" ,
   "   (g) Over the 'Save' button in the image viewer.\n" ,
   "   (h) Over the 'crop' button in the image viewer.\n" ,
   "   (i) Over the sub-graphs in the time series dataset graph viewer.\n" ,
   "   (j) Over the coordinate display in the upper left corner of an AFNI\n" ,
   "       controller.\n" ,
   "   (k) In the 'Render Dataset' plugin, over the 'See Xhairs' and 'Accumulate'\n" ,
   "       toggle buttons.  The 'Accumulate' popup lets you enter a text label\n" ,
   "       to be drawn in the rendered image viewer -- the actual display of labels\n" ,
   "       (size and location) is controlled from the image viewer intensity bar\n" ,
   "       popup menu -- item (e) above.  Right-Click lets you change the label\n" ,
   "       for newly rendered images, whereas Shift+Right-Click lets you change\n" ,
   "       the label for all previously rendered images as well as new images.\n" ,
   "   (l) In the 'Clusters' report panel, right-clicking in the upper part of\n" ,
   "       the window (where the textual summary is), will let you choose how\n" ,
   "       the 'Histog' option will plot the histogram from the 'Aux.Dset'.\n" ,
   "       ('Histog' is selected from the menu whose initial choice is 'Mean'.)\n" ,
   "\n" ,
   "(2) Other 'special' clicks that aren't obvious:\n" ,
   "   (a) Left-clicking on the 'Image' or 'Graph' button for an already open\n" ,
   "       AFNI viewer will bring that viewer's window back up to the top of\n" ,
   "       the X11 window stacking order.\n" ,
   "   (b) Right-clicking on the 'Image' or 'Graph' button for an already open\n" ,
   "       AFNI viewer will bring that viewer's window over to the place where\n" ,
   "       you just clicked -- this is useful for finding lost viewers.\n" ,
   "   (c) Right-clicking on the 'DataDir' button in the AFNI controller will\n" ,
   "       un-hide the obsolescent 'Define Markers' button.\n" ,
   "   (d) Left-clicking on the logo at the lower left of a graph viewer will\n" ,
   "       make the logo and menu buttons disappear -- this is intended to help\n" ,
   "       you make a clean-looking snapshot of the window.  Left-click again\n" ,
   "       in the same region at the lower left to un-hide the logo and buttons.\n" ,
   "   (e) Right-clicking on the graph viewer logo or on the image viewer 'Disp'\n" ,
   "       button (i.e., the things at the lower left of each viewer window) will\n" ,
   "       bring the parent AFNI controller back to the top of the X11 window\n" ,
   "       stacking order.\n" ,
   "   (f) In an image viewer window, if you press-and-hold-down the Left mouse\n" ,
   "       button, then drag the cursor vertically and horizontally (while still\n" ,
   "       holding the Left button down), the contrast and brightness of the\n" ,
   "       grayscale underlay changes as you move.\n" ,
   "   (g) To exit AFNI quickly when multiple controllers are open, hold down the\n" ,
   "       Shift key when you press the 'done' button (in any AFNI controller).\n" ,
   "   (h) Left-clicking in the logo square to the right of the AFNI controller\n" ,
   "       'done' button will cause the AFNI splash screen to popup.  You can\n" ,
   "       close the splash screen window again via the usual X11 controls on\n" ,
   "       the window border, or by left-clicking again in the logo square.\n" ,
   NULL } ;
#define NUM_readme_afnigui 61
