/*! Data for atlases from Eickhoff's SPM toolbox.
Automatically compiled from: AllAreas_v13b_MPM.mat
 located at: /Volumes/elrond0/home4/users/ziad/Programs/matlab/spm2/toolbox/Anatomy_13b
 by function /Users/ziad/AFNI/src/matlab/CA_EZ_Prep.m
Date: 13-Feb-2006*/

/*! Leave the reference string in a separate file
for easy script parsing.*/
#include "thd_ttatlas_CA_EZ-ref.h"

/* ----------- Macro Labels --------------------- */
/* ----------- Based on: Macro.mat -------------*/
ML_EZ_point ML_EZ_list[ML_EZ_COUNT] = {
   { 1   , "Left Precentral Gyrus............................."},
   { 2   , "RightPrecentral Gyrus............................."},
   { 3   , "Left Superior Frontal Gyrus......................."},
   { 4   , "Right Superior Frontal Gyrus......................"},
   { 5   , "Left Superior Orbital Gyrus......................."},
   { 6   , "Right Superior Orbital Gyrus......................"},
   { 7   , "Left Middle Frontal Gyrus........................."},
   { 8   , "Right Middle Frontal Gyrus........................"},
   { 9   , "Left Middle Orbital Gyrus........................."},
   { 10  , "Right Middle Orbital Gyrus........................"},
   { 11  , "Left Inferior Frontal Gyrus (p. Opercularis)......"},
   { 12  , "Right Inferior Frontal Gyrus (p. Opercularis)....."},
   { 13  , "Left Inferior Frontal Gyrus (p. Triangularis)....."},
   { 14  , "Right Inferior Frontal Gyrus (p. Triangularis)...."},
   { 15  , "Left Inferior Frontal Gyrus (p. Orbitalis)........"},
   { 16  , "Right Inferior Frontal Gyrus (p. Orbitalis)......."},
   { 17  , "Left Rolandic Operculum..........................."},
   { 18  , "Right Rolandic Operculum.........................."},
   { 19  , "Left SMA.........................................."},
   { 20  , "Right SMA........................................."},
   { 21  , "Left Olfactory cortex............................."},
   { 22  , "Right Olfactory cortex............................"},
   { 23  , "Left Superior Medial Gyrus........................"},
   { 24  , "Right Superior Medial Gyrus......................."},
   { 25  , "Left Mid Orbital Gyrus............................"},
   { 26  , "Right Mid Orbital Gyrus..........................."},
   { 27  , "Left Rectal Gyrus................................."},
   { 28  , "Right Rectal Gyrus................................"},
   { 29  , "Left Insula Lobe.................................."},
   { 30  , "Right Insula Lobe................................."},
   { 31  , "Left Anterior Cingulate Cortex...................."},
   { 32  , "Right Anterior Cingulate Cortex..................."},
   { 33  , "Left Middle Cingulate Cortex......................"},
   { 34  , "Right Middle Cingulate Cortex....................."},
   { 35  , "Left Posterior Cingulate Cortex..................."},
   { 36  , "Right Posterior Cingulate Cortex.................."},
   { 37  , "Left Hippocampus.................................."},
   { 38  , "Right Hippocampus................................."},
   { 39  , "Left ParaHippocampal GYrus........................"},
   { 40  , "Right ParaHippocampal GYrus......................."},
   { 41  , "Left Amygdala....................................."},
   { 42  , "Right Amygdala...................................."},
   { 43  , "Left Calcarine Gyrus.............................."},
   { 44  , "Right Calcarine Gyrus............................."},
   { 45  , "Left Cuneus......................................."},
   { 46  , "Right Cuneus......................................"},
   { 47  , "Left Linual Gyrus................................."},
   { 48  , "Right Linual Gyrus................................"},
   { 49  , "Left Superior Occipital Gyrus....................."},
   { 50  , "Right Superior Occipital Gyrus...................."},
   { 51  , "Left Middle Occipital Gyrus......................."},
   { 52  , "Right Middle Occipital Gyrus......................"},
   { 53  , "Left Inferior Occipital Gyrus....................."},
   { 54  , "Right Inferior Occipital Gyrus...................."},
   { 55  , "Left Fusiform Gyrus..............................."},
   { 56  , "Right Fusiform Gyrus.............................."},
   { 57  , "Left Postcentral Gyrus............................"},
   { 58  , "Right Postcentral Gyrus..........................."},
   { 59  , "Left Superior Parietal Lobule....................."},
   { 60  , "Right Superior Parietal Lobule...................."},
   { 61  , "Left Inferior Parietal Lobule....................."},
   { 62  , "Right Inferior Parietal Lobule...................."},
   { 63  , "Left SupraMarginal Gyrus.........................."},
   { 64  , "Right SupraMarginal Gyrus........................."},
   { 65  , "Left Angular Gyrus................................"},
   { 66  , "Right Angular Gyrus..............................."},
   { 67  , "Left Precuneus...................................."},
   { 68  , "Right Precuneus..................................."},
   { 69  , "Left Paracentral Lobule..........................."},
   { 70  , "Right Paracentral Lobule.........................."},
   { 71  , "Left Caudate Nucleus.............................."},
   { 72  , "Right Caudate Nucleus............................."},
   { 73  , "Left Putamen......................................"},
   { 74  , "Right Putamen....................................."},
   { 75  , "Left Pallidum....................................."},
   { 76  , "Right Pallidum...................................."},
   { 77  , "Left Thalamus....................................."},
   { 78  , "Right Thalamus...................................."},
   { 79  , "Left Heschls Gyrus................................"},
   { 80  , "Right Heschls Gyrus..............................."},
   { 81  , "Left Superior Temporal Gyrus......................"},
   { 82  , "Right Superior Temporal Gyrus....................."},
   { 83  , "Left Temporal Pole................................"},
   { 84  , "Right Temporal Pole..............................."},
   { 85  , "Left Middle Temporal Gyrus........................"},
   { 86  , "Right Middle Temporal Gyrus......................."},
   { 87  , "Left Medial Temporal Pole........................."},
   { 88  , "Right Medial Temporal Pole........................"},
   { 89  , "Left Inferior Temporal Gyrus......................"},
   { 90  , "Right Inferior Temporal Gyrus....................."},
   { 91  , "Left Cerebelum (Crus 1)..........................."},
   { 92  , "Right Cerebelum (Crus 1).........................."},
   { 93  , "Left Cerebelum (Crus 2)..........................."},
   { 94  , "Right Cerebelum (Crus 2).........................."},
   { 95  , "Left Cerebelum (III).............................."},
   { 96  , "Right Cerebelum (III)............................."},
   { 97  , "Left Cerebelum (IV-V)............................."},
   { 98  , "Right Cerebelum (IV-V)............................"},
   { 99  , "Left Cerebelum (VI)..............................."},
   { 100 , "Right Cerebelum (VI).............................."},
   { 101 , "Left Cerebelum (VII).............................."},
   { 102 , "Right Cerebelum (VII)............................."},
   { 103 , "Left Cerebelum (VIII)............................."},
   { 104 , "Right Cerebelum (VIII)............................"},
   { 105 , "Left Cerebelum (IX)..............................."},
   { 106 , "Right Cerebelum (IX).............................."},
   { 107 , "Left Cerebelum (X)................................"},
   { 108 , "Right Cerebelum (X)..............................."},
   { 109 , "Cerebellar Vermis (1/2)..........................."},
   { 110 , "Cerebellar Vermis (3)............................."},
   { 111 , "Cerebellar Vermis (4/5)..........................."},
   { 112 , "Cerebellar Vermis (6)............................."},
   { 113 , "Cerebellar Vermis (7)............................."},
   { 114 , "Cerebellar Vermis (8)............................."},
   { 115 , "Cerebellar Vermis (9)............................."},
   { 116 , "Cerebellar Vermis (10)............................"},
};

/* -----------     MPM      --------------------- */
/* ----------- Based on: AllAreas_v13b_MPM.mat --------------*/
CA_EZ_point CA_EZ_list[CA_EZ_COUNT] = { 
   { "Hipp. (CA)..............................", 100, "Hippocampus_CA............." },
   { "OP 1....................................", 105, "SII_OP1...................." },
   { "Area 45.................................", 110, "Broca_45..................." },
   { "Amyg. (CM)..............................", 115, "Amygdala_CM................" },
   { "Area 4a.................................", 120, "PMC_4a....................." },
   { "TE 1.0..................................", 125, "PAC_TE10..................." },
   { "Hipp. (EC)..............................", 130, "Hippocampus_EC............." },
   { "Area 3b.................................", 135, "PSC_3b....................." },
   { "hIP1....................................", 140, "AIPS_AIP..................." },
   { "Area 17.................................", 145, "visual_V1.................." },
   { "Amyg. (SF)..............................", 150, "Amygdala_SF................" },
   { "OP 3....................................", 155, "SII_OP3...................." },
   { "Area 44.................................", 160, "Broca_44..................." },
   { "Hipp. (FD)..............................", 165, "Hippocampus_FD............." },
   { "Area 4p.................................", 170, "PMC_4p....................." },
   { "Area 1..................................", 175, "PSC_1......................" },
   { "Area 18.................................", 180, "visual_V2.................." },
   { "TE 1.1..................................", 185, "PAC_TE11..................." },
   { "Hipp. (HATA)............................", 190, "Hippocampus_HATA..........." },
   { "hIP2....................................", 195, "AIPS_VIP..................." },
   { "OP 2....................................", 200, "SII_OP2...................." },
   { "Area 6..................................", 205, "premotor_6................." },
   { "Amyg. (LB)..............................", 210, "Amygdala_LB................" },
   { "Area 3a.................................", 215, "PSC_3a....................." },
   { "Area 2..................................", 220, "PSC_2......................" },
   { "TE 1.2..................................", 225, "PAC_TE12..................." },
   { "OP 4....................................", 230, "SII_OP4...................." },
   { "Hipp. (SUB).............................", 235, "Hippocampus_SUB............" },
};

/* ----------- Left Right   --------------------- */
/* ---- Based on my understanding -------------- */
LR_EZ_point LR_EZ_list[LR_EZ_COUNT] = {
   { 1  , "Non-Brain..." },
   { 2  , "Right Brain." },
   { 3  , "Left Brain.." },
};

