char CA_EZ_REF_STR_HARD[128][256] = {
"ANATOMY TOOLBOX                                             ",
"Version 1.5                                                 ",
"written by:                                                 ",
"   Simon Eickhoff  (s.eickhoff@fz-juelich.de)        ",
"   Institut for Medicine (IME) Research Center Juelich",
"   Phone + 49 2461-61-5219 / Fax + 49 2461-61-2820   ",
"References:",
"   Eickhoff SB et al.: A new SPM toolbox for combining probabilistic",
"    cytoarchitectonic maps and functional imaging data. (2005)",
"    NeuroImage 25 (4): 1325-1335",
"   Eickhoff SB et al.: Testing anatomically specified hypotheses in",
"    functional imaging using cytoarchitectonic maps. (2006)",
"    NeuroImage 32 (2): 570-82",
"   Eickhoff SB et al., Assignment of functional activations to",
"    probabilistic cytoarchitectonic areas revisited. (2007)",
"    NeuroImage 26 (3): 511-521",
"Publications describing the included cytoarchitectonic maps:",
"    Auditory cortex TE 1.0, TE 1.1, TE 1.2--------------->  Morosan et al., NeuroImage 2001",
"    Broca's area BA 44, BA 45---------------------------->  Amunts et al., J Comp Neurol 1999",
"    Motor cortex BA 4a, BA 4p BA 6----------------------->  Geyer et al., Nature 1996",
"                                                        ->  S. Geyer, Springer press 2003",
"    Somatosensory cortex BA 3a, BA 3b, BA 1 BA 2--------->  Geyer et al., NeuroImage, 1999, 2000",
"                                                        ->  Grefkes et al., NeuroImage 2001",
"    Parietal operculum / SII OP 1, OP 2, OP 3, OP 4------>  Eickhoff et al., Cerebral Cortex 2006a,b",
"    Amygdala (CM/LB/SF) Hippocampus (FD/CA /SUB/EC/HATA)->  Amunts et al., Anat Embryol 2005    ",
"    anterior intraparietal sulcus hIP1, hIP2------------->  Choi et al., J Comp Neurol 2006     ",
"    Visual cortex BA 17, BA 18 hOC5---------------------->  Amunts et al., NeuroImage 2000      ",
"                                                        ->  Malikovic et al., Cerebral Cortex 2006",
"    Fiber tracts ar,cb,cing,ct,fom,iof,lgb,mb,mbg,or,slf,sof,uf -> Burgel et al., NeuroImage 1999, 2006",
"All other areas may only be used with authors' permission ! ",
" ",
" ",
"AFNI adaptation by",
" Ziad S. Saad (saadz@mail.nih.gov, SSCC/NIMH/NIH)",
" Info automatically created with CA_EZ_Prep.m based on se_note.m",
""};/* Must be the only empty string in the array*/
char CA_EZ_VERSION_STR_HARD[128] = { "Version 1.5" };

