char CA_EZ_REF_STR[27][141] = {
"ANATOMY TOOLBOX                                             ",
"Version 1.3c                                                ",
"written by:                                                 ",
"   Simon Eickhoff  (s.eickhoff@fz-juelich.de)        ",
"   Institut for Medicine (IME) Research Center J-lich",
"   Phone + 49 2461-61-5219 / Fax + 49 2461-61-2820   ",
"Publications describing the included cytoarchitectonic maps:",
"    Auditory cortex TE 1.0, TE 1.1, TE 1.2--------------->  Morosan et al., NeuroImage 2001                                      ",
"    Broca's area BA 44, BA 45---------------------------->  Amunts et al., J Comp Neurol 1999                                    ",
"    Motor cortex BA 4a, BA 4p BA 6----------------------->  Geyer et al., Nature 1996 S. Geyer, Springer press 2003              ",
"    Somatosensory cortex BA 3a, BA 3b, BA 1 BA 2--------->  Geyer et al., NeuroImage, 1999 + 2000 Grefkes et al., NeuroImage 2001",
"    Parietal operculum / SII OP 1, OP 2, OP 3, OP 4------>  Eickhoff et al., Cerebral Cortex 2006a,b                             ",
"    Amygdala (CM/LB/SF) Hippocampus (FD/CA /SUB/EC/HATA)->  Amunts et al., Anat Embryol 2005                                     ",
"    anterior intraparietal sulcus hIP1, hIP2------------->  Choi et al., J Comp Neurol 2006                                      ",
"    Visual cortex BA 17, BA 18 hOC5---------------------->  Amunts et al., NeuroImage 2000 Malikovic et al., Cerebral Cortex 2006",
"All other areas may only be used with authors' permission ! ",
" ",
" ",
"AFNI adaptation by",
" Ziad S. Saad (ziad@nih.gov, SSCC/NIMH/NIH)",
" Info automatically created with CA_EZ_Prep.m based on se_note.m",
""};/* Must be the only empty string in the array*/
