/* 

ver = 1.0;  date = June 26, 2026
+ [PT] start of this program

*/

#include <stdio.h>
#include <stdlib.h>
#include <math.h>
#include <unistd.h>
#include "debugtrace.h"
#include "mrilib.h"
#include "thd_stcorr2.h"

#ifdef USE_OMP
#include <omp.h>
#endif

// function with OpenMP to do spacetime corr calc
int calc_spacetimecorr(float *DOT, int nmask, float **AZ, int nvalsA, 
                       float **BZ, int nvalsB);

int run_stcorr2( int comline, PARAMS_stcorr2 opts,
                 int argc, char *argv[] );

// --------------------------------------------------------------------------

int usage_3dstcorr2() 
{
   char *author = "PA Taylor (SSCC, NIMH, NIH)";
   PARAMS_stcorr2 opts;

   opts = set_stcorr2_defaults();

   printf(
"\n"
"Overview ~1~ \n"
"\n"
"This program is the MUCH MUCH MUCH faster version of the original\n"
"3dSpaceTimeCorr program.  It uses pre-Z-score-ization (like InstaCorr)\n"
"and OpenMP-based multithreading to achieve such relativistically better\n"
"runtimes.\n"
"\n"
"This program is for calculating something *similar* to the (Pearson)\n"
"correlation coefficient between corresponding voxels between two data\n"
"sets, which is what 3dTcorrelate does.  However, this is program\n"
"operates differently. Here, two data sets are loaded in, and for each\n"
"voxel in the brain:\n"
"   + for each data set, an ijk-th voxel is used as a seed to generate a\n"
"     correlation map within a user-defined mask (e.g., whole brain,\n"
"     excluding the seed location where r==1, by definition);\n"
"   + that correlation map is Fisher Z transformed;\n"
"   + the Z-correlation maps are (Pearson) correlated with each other,\n"
"     generating a single correlation coefficient;\n"
"   + the correlation coefficient is stored at the same ijk-th voxel\n"
"     location in the output data set;\n"
"and the process is repeated.  Thus, the output is a whole brain map\n"
"of r-correlation coefficients for corresponding voxels from the two data\n"
"sets, generated by temporal and spatial patterns (-> space+time \n"
"correlation!).\n"
"\n"
"This could be useful when researchers *wish* that they could use\n"
"3dTcorrelate on something like resting state FMRI data.  Maybe.\n"
"Note that this program could take several minutes or more to run,\n"
"depending on the size of the data set and mask.\n"
"\n"
"written by: PA Taylor (SSCC, NIMH, NIH, USA)\n"
"            with a great deal of input, helpful discussion, beta-testing\n"
"            and patience from Peter Kirk (EDB, NIMH, NIH, USA), who also\n"
"            has the distinction of finding a real _use_ for this program.\n"
"\n"
"==========================================================================\n"
"\n"
"Usage ~1~ \n"
"\n"
"Load in two 4D datasets (e.g., FMRI volumes) and a mask.\n"
"\n"
"This program makes use of multithreading, and it is best to let it use\n"
"many CPUs/threads to calculate, otherwise it can get slow-ish.\n"
"\n"
"    3dSpaceTimeCorr -insetA FILEA -insetB FILEB  -mask MASK \\\n"
"                    -prefix PREFIX {-out_Zcorr}  \n"
"\n"
"    where:\n"
"\n"
"  -insetA FILEA  :one 4D data set.\n"
"  -insetB FILEB  :another 4D data set; must have same spatial dimensions as\n"
"                  FILEA, as well as same number of time points.\n"
"\n"
"  -mask MASK     :optional mask.  Highly recommended to use for speed of\n"
"                  calcs (and probably for interpretability, too).\n"
"\n"
"  -prefix PREFIX :output filename/base.\n"
"\n"
"  -out_Zcorr     :switch to output Fisher Z transform of spatial map\n"
"                  correlation (default is Pearson r values).\n"
"\n"
"==========================================================================\n"
"\n"
"Examples ~1~\n"
"\n"
"    1. Basic usage\n"
"\n"
"       3dSpaceTimeCorr                                  \\\n"
"           -insetA  sub-001_task-rest_bold.nii.gz       \\\n"
"           -insetB  sub-002_task-rest_bold.nii.gz       \\\n"
"           -mask    mask.nii.gz                         \\\n"
"           -prefix  stcorr_001_002\n"
"\n"
"==========================================================================\n"
"\n"
);

	return 0;
}

int main(int argc, char *argv[]) {

   int ii = 0;
   int iarg;
   PARAMS_stcorr2 InOpts;
   float tmp;
   int itmp;
   char *auto_tstring = NULL;

   mainENTRY("3dSpaceTimeCorr2"); machdep(); 
  
   // fill option struct with defaults
   InOpts = set_stcorr2_defaults();

   // ****************************************************************
   //                  parse command line arguments
   // ****************************************************************
	
   if (argc == 1) { usage_3dstcorr2(); exit(0); }

   /* scan through args */
   iarg = 1; 
   while( iarg < argc && argv[iarg][0] == '-' ){

      if( strcmp(argv[iarg],"-help") == 0 || 
          strcmp(argv[iarg],"-h") == 0 ) {
         usage_3dstcorr2();
         exit(0);
      }
			 
      if( strcmp(argv[iarg],"-insetA") == 0 ){
         if( ++iarg >= argc ) 
            ERROR_exit("Need argument after '%s'", argv[iarg-1]);

         InOpts.insetA = strdup(argv[iarg]) ;
         iarg++ ; continue ;
      }

      if( strcmp(argv[iarg],"-insetB") == 0 ){
         if( ++iarg >= argc ) 
            ERROR_exit("Need argument after '%s'", argv[iarg-1]);

         InOpts.insetB = strdup(argv[iarg]) ;
         iarg++ ; continue ;
      }

      if( strcmp(argv[iarg],"-mask") == 0 ){
         if( ++iarg >= argc ) 
            ERROR_exit("Need argument after '%s'", argv[iarg-1]);

         InOpts.mask_name = strdup(argv[iarg]) ;			
         iarg++ ; continue ;
      }

      if( strcmp(argv[iarg],"-prefix") == 0 ){
         if( ++iarg >= argc ) 
            ERROR_exit("Need argument after '%s'", argv[iarg-1]);

         InOpts.prefix = strdup(argv[iarg]) ;

         if( !THD_filename_ok(InOpts.prefix) ) 
            ERROR_exit("Illegal name after '%s'", argv[iarg-1]);
         iarg++ ; continue ;
      }

      if( strcmp(argv[iarg],"-out_Zcorr") == 0 ){
         InOpts.out_Zcorr = 1;
         iarg++ ; continue ;
      }

      if( strcmp(argv[iarg],"-verb") == 0 ){
         if( ++iarg >= argc ) 
            ERROR_exit("Need argument after '%s'", argv[iarg-1]);

         InOpts.verb = atoi(argv[iarg]);
         iarg++ ; continue ;
      }

      ERROR_message("Bad option '%s'\n",argv[iarg]);
      suggest_best_prog_option(argv[0], argv[iarg]);
      exit(1);
   }
	
   // ****************************************************************
   //               verify presence+behavior of inputs
   // **************************************************************** 

   INFO_message("3dSpaceTimeCorr2: verify inputs");

   if ( !InOpts.insetA ) { 
      ERROR_message("You need to provide an input dset with '-insetA ..'");
      exit(1);
   }

   if ( !InOpts.insetB ) { 
      ERROR_message("You need to provide an input dset with '-insetB ..'");
      exit(1);
   }

   if ( !InOpts.prefix )
      ERROR_exit("Need an output name via '-prefix ..'\n");

   if ( !InOpts.mask_name )
      ERROR_exit("You need to provide a mask dset with '-mask ..'");
   
   // DONE FILLING, now do the work
   ii = run_stcorr2(1, InOpts, argc, argv);

   return 0;
}

/* ========================================================================= */

int run_stcorr2( int comline, PARAMS_stcorr2 opts,
                 int argc, char *argv[] )
{
   int i, j, k, idx;
   int nn;
   int tmp;

   int *Dim=NULL;
   int nvox, nvalsA, nvalsB;

	THD_3dim_dataset *dset_insetA = NULL;     // insetA
	THD_3dim_dataset *dset_insetB = NULL;     // insetB
   THD_3dim_dataset *dset_mask   = NULL;     // mask
   THD_3dim_dataset *dset_out    = NULL;     // output dset (to be created)

   char prefix[THD_MAX_PREFIX];

   byte *mask_arr = NULL;                    // what mask becomes
   int nmask = -1;

   float *tsA = NULL;                        // time series, from insetA
   float *tsB = NULL;                        // time series, from insetB
   float **AZ = NULL;                        // insetA -> masked and Zscored
   float **BZ = NULL;                        // insetB -> masked and Zscored

   float *DOT = NULL;                        // dot product array
   float *DOTOUT = NULL;                     // dot product array, to output

   /* ---------------------------------------------------------------------- */

   ENTRY("run_SpaceTimeCorr2");

   /* -------------------------- verify inputs ----------------------------- */

   // insetA
   dset_insetA = THD_open_dataset(opts.insetA);
   if( dset_insetA == NULL )
      ERROR_exit("Can't open dataset '%s'", opts.insetA);
   DSET_load(dset_insetA); CHECK_LOAD_ERROR(dset_insetA);

   // insetB
   dset_insetB = THD_open_dataset(opts.insetB);
   if( dset_insetB == NULL )
      ERROR_exit("Can't open dataset '%s'", opts.insetB);
   DSET_load(dset_insetB); CHECK_LOAD_ERROR(dset_insetB);

   // mask
   dset_mask = THD_open_dataset(opts.mask_name);
   if( dset_mask == NULL )
      ERROR_exit("Can't open dataset '%s'", opts.mask_name);
   DSET_load(dset_mask); CHECK_LOAD_ERROR(dset_mask);

   // check for grid mismatches
   if( THD_dataset_mismatch( dset_insetA, dset_insetB ) )
      ERROR_exit("Mismatch between insetA and insetB dsets!\n");
   if( THD_dataset_mismatch( dset_insetA, dset_mask ) )
      ERROR_exit("Mismatch between insetA and mask dsets!\n");

   /* -------------------------- basic setup ----------------------------- */

   // spatial dim info
   Dim = (int *)calloc(3, sizeof(int));
   Dim[0] = DSET_NX(dset_insetA);
   Dim[1] = DSET_NY(dset_insetA); 
   Dim[2] = DSET_NZ(dset_insetA);
   nvox   = DSET_NVOX(dset_insetA);

   // time dim: need not be equal
   nvalsA = DSET_NVALS(dset_insetA);
   nvalsB = DSET_NVALS(dset_insetB);

   // mask comes from just [0]th vol (NB: mask_arr has len = nvox)
   mask_arr = THD_makemask( dset_mask, 0, 0, -1 );
   // number of nonzero voxels in a mask
   nmask = THD_countmask( nvox, mask_arr );
   if( opts.verb )
      INFO_message("Relative number of voxels in mask = %d / %d", nmask, nvox);
   if( nmask < 1 )
      ERROR_exit("Automask is too small (i.e., empty) to process");

   // allocate 2D arrays to hold each inset, masked and transformed to Z
   AZ = calloc( nmask, sizeof(AZ));
   for( i=0 ; i<nmask ; i++) 
      AZ[i] = calloc( nvalsA, sizeof(float)); 
   BZ = calloc( nmask, sizeof(BZ));
   for( i=0 ; i<nmask ; i++) 
      BZ[i] = calloc( nvalsA, sizeof(float)); 

   if( (AZ == NULL) || (BZ == NULL) ) { 
      ERROR_message("MemAlloc failure for AZ and/or BZ.");
      exit(4);
   } 
   
   // allocate 1D arrays to hold time series from respective insets
   tsA = (float *)calloc(nvalsA, sizeof(float));
   tsB = (float *)calloc(nvalsB, sizeof(float));

   if( (tsA == NULL) || (tsB == NULL) ) { 
      ERROR_message("MemAlloc failure for tsA and/or tsB.");
      exit(4);
   } 

   /* -------------------------- Z-score inputs ---------------------------- */

   /*
     Populate AZ and BZ (Z-scored time series within mask).
     
     Go through all voxels in each inset within mask, make Z-scores
     and save in arrays.
   */
   INFO_message("Z-score-ize the time series");

   idx = 0;
   for( i=0 ; i<nvox ; i++) {
      if( mask_arr[i] ) {

         // extract [i]th insetA time series (from within mask)
         tmp = THD_extract_float_array(i, dset_insetA, tsA); 
         // ... and convert it to Z-scores, and store it in [idx]th location
         tmp = zscore_ts_welford(tsA, AZ[idx], nvalsA, 1);

         // extract [i]th insetB time series (from within mask)
         tmp = THD_extract_float_array(i, dset_insetB, tsB); 
         // ... and convert it to Z-scores, and store it in [idx]th location
         tmp = zscore_ts_welford(tsB, BZ[idx], nvalsB, 1);

         idx++;
      }
   }

   // free some memory space
   if( dset_insetA ){
      DSET_delete(dset_insetA); 
      free(dset_insetA); 
   }

   if( dset_insetB ){
      DSET_delete(dset_insetB); 
      free(dset_insetB); 
   }

   /* -------------------------- SpaceTimeCorr ---------------------------- */

   // allocate 1D array to hold output dot product (the Pearson corr);
   // this has len = nmask
   DOT = (float *)calloc(nmask, sizeof(float));
   // ... and this is the one that gets filled in, to write out
   DOTOUT = (float *)calloc(nvox, sizeof(float));

   if( (DOT == NULL) || (DOTOUT == NULL) ) { 
      ERROR_message("MemAlloc failure for DOT and/or DOTOUT.");
      exit(4);
   }
   
   // do spacetime calc
   tmp = calc_spacetimecorr(DOT, nmask, AZ, nvalsA, BZ, nvalsB);

   // ... and fill those values into an array for output size
   idx = 0;
   for( i=0 ; i<nvox ; i++) {
      if( mask_arr[i] ) {
         // can do Fisher Z-transform of correlation values
         if( opts.out_Zcorr ) 
            DOTOUT[i] = BOBatanhf(DOT[idx]);
         else
            DOTOUT[i] = DOT[idx];
         idx++;
      }
   }
   
   /* ------------------------ write output dset --------------------------- */

   dset_out = EDIT_empty_copy( dset_mask ); 
   EDIT_dset_items(dset_out,
                   ADN_nvals, 1,
                   ADN_datum_all, MRI_float,    
                   ADN_prefix, opts.prefix,
                   ADN_none );

   if( !THD_ok_overwrite() && THD_is_ondisk(DSET_HEADNAME(dset_out)) )
      ERROR_exit("Can't overwrite existing dataset '%s'",
                 DSET_HEADNAME(dset_out));

   EDIT_substitute_brick(dset_out, 0, MRI_float, DOTOUT); 
   DOTOUT=NULL;

   // write out dset
   THD_load_statistics( dset_out );
   tross_Make_History("3dSpaceTimeCorr2", argc, argv, dset_out);
   THD_write_3dim_dataset(NULL, NULL, dset_out, True);

   /* --------------------------- free stuff ------------------------------ */

   if( dset_mask ){
      DSET_delete(dset_mask); 
      free(dset_mask); 
   }

   if( dset_out ){
      DSET_delete(dset_out); 
      free(dset_out); 
   }

   if( Dim )
      free(Dim);

   if( mask_arr )
      free(mask_arr);

   if( AZ ) {
      for( i=0 ; i<nmask ; i++) 
         free(AZ[i]);
      free(AZ);
   }

   if( BZ ) {
      for( i=0 ; i<nmask ; i++) 
         free(BZ[i]);
      free(BZ);
   }

   if( tsA )
      free(tsA);
   
   if (tsB )
      free(tsB);

   if( DOT )
      free(DOT);

   return 0;
}

/* ========================================================================= */

/*
  SpaceTimeCalc, with OpenMP

  Parameters:
  DOT    : 1D arr (float, len: nmask), output to store dot product values
  nmask  : int, number of spatial locations; [0]th dim of AZ and BZ
  AZ     : 2D arr (float, nmask x nvalsA), stack of time series from insetA
  nvalsA : int, number of time pts in AZ; [1]th dim of AZ
  BZ     : 2D arr (float, nmask x nvalsB), stack of time series from insetB
  nvalsB : int, number of time pts in BZ; [1]th dim of BZ

  DOT will be output.
*/
int calc_spacetimecorr(float *DOT, int nmask, float **AZ, int nvalsA, 
                       float **BZ, int nvalsB)
{
   int Nthreads=1;
   int j;

   int ApproxTenPerc=0;

#ifdef USE_OMP
   INFO_message("Start OMPing");
   AFNI_SETUP_OMP(0) ;
   Nthreads = omp_get_max_threads();
   INFO_message("OMP thread count = %d", Nthreads);
#else
   INFO_message("Not using OMP-- will be slow.");
#endif

   ApproxTenPerc = (int) (0.1*nmask)/Nthreads;
   INFO_message("ApproxTenPerc = %d", ApproxTenPerc);

   if( ApproxTenPerc == 0 ) {
      if( nmask < 100 )
         WARNING_message("Very small number of voxels to calculate! "
                         "Only %d??", nmask);
      else
         WARNING_message("Really?  %d voxels to analyze and %d threads??",
                         nmask, Nthreads);
      ApproxTenPerc = 1;
   }
   else if(ApproxTenPerc < 0 ) 
      ERROR_exit("ERROR! %d voxels to analyze and %d threads?? "
                    "This leads to ~10 percent value of %d?!??",
                    nmask, Nthreads, ApproxTenPerc);

   AFNI_OMP_START;
#pragma omp parallel //if(1)
   {
      int pp;
      int i, n;
      int ithr;
      int nprog=0;
      time_t t_start=time(NULL);  /* init to quiet whiny compiler */

      int tmp;
      float sval=0.0;
      float vecA[nmask-1], vecB[nmask-1];
      float vecAZ[nmask-1], vecBZ[nmask-1];

#ifdef USE_OMP
      ithr = omp_get_thread_num();
      if( !ithr ) {
         fprintf(stderr,"++ Nvox progress proxy count on thread[%d]: "
                 "start ...\n", ithr);
         t_start = time(NULL);
      }
#else
      fprintf(stderr,"++ Nvox progress proxy count on (only) thread: "
              "start ...\n", ithr);
      t_start = time(NULL);
#endif

#pragma omp for
      for( pp=0 ; pp<nmask ; pp++ ) {

         /* ----------------------- calc 1: time ----------------------- */
         
         /* vecA and vecB has len=nmask-1, because we don't include
            the i=pp case of the dot product; we therefore loop over
            nmask-1 values to store them easily in the [i]th spot, and
            put the case where i==nmask-1 where i=pp.  It's
            funny-looking, but just reduces need to add another index
         */
         for( i=0 ; i<nmask-1 ; i++ ) {
            vecA[i] = 0.0;
            vecB[i] = 0.0;
            if( i != pp ) {
               // dot product across time for A and B datasets
               for ( n=0 ; n<nvalsA ; n++ )
                  vecA[i]+= AZ[pp][n]*AZ[i][n];
               vecA[i]/= nvalsA;
               for ( n=0 ; n<nvalsB ; n++ ) 
                  vecB[i]+= BZ[pp][n]*BZ[i][n];
               vecB[i]/= nvalsB;
            }
         }
         // final one to put in: the last [i]th value gets stored in
         // the i=pp spot (which was already initialized to zero above)
         i = nmask-1;
         for ( n=0 ; n<nvalsA ; n++ )
            vecA[pp]+= AZ[pp][n]*AZ[i][n];
         vecA[pp]/= nvalsA;
         for ( n=0 ; n<nvalsB ; n++ ) 
            vecB[pp]+= BZ[pp][n]*BZ[i][n];
         vecB[pp]/= nvalsB;

         /* ----------------------- calc 2: space ----------------------- */

         // convert 1D arrays to Zscores, to prep for dot product
         tmp = zscore_ts_welford(vecA, vecAZ, nmask-1, 1);
         tmp = zscore_ts_welford(vecB, vecBZ, nmask-1, 1);

         // do the dot product
         sval = 0.0;
         for ( n=0 ; n<nmask ; n++ )
            sval+= vecAZ[n]*vecBZ[n];
         sval/= nmask-1;

         DOT[pp] = sval;

         /* -------------------- finalize/progress ---------------------- */

#ifdef USE_OMP
         ithr = omp_get_thread_num();
         // counter for user
         if( ithr == 0 ) {
            nprog++;
            if( (nprog % ApproxTenPerc) == 0 ) {
               fprintf(stderr,"\t%s %3.0f%% %s -> %.2f min\n",
                       "[", nprog *10./ApproxTenPerc,"]", 
                       (float) difftime( time(NULL), t_start)/60. );
            }
         }
#else
         nprog++;
         if( (nprog % ApproxTenPerc) == 0 ) {
            fprintf(stderr,"\t%s %3.0f%% %s -> %.2f min\n",
                    "[", nprog *10./ApproxTenPerc,"]", 
                    (float) difftime( time(NULL), t_start)/60. );
         }
#endif

      }

   } // end OMP
   AFNI_OMP_END ;
   
   
   INFO_message("Finished OMPing.  Finalizing...");


   return 0;

}
