#!/bin/tcsh -f
#################################################
## 05/16/2017 Justin Rajendra
## launch shiny plot of FATCAT outputs

if ($#argv == 0) then
   echo "ERROR: Need a path to .netcc or .grid files!"
   exit 0
else
   set arglist = ($*)
endif

## get full path for the input table

cd $arglist
set corr_dir = `pwd`
cd -

R --slave --no-restore \
-e 'shiny::runApp("./FATCAT_heatmap_shiny", launch.browser=TRUE)' \
--args $corr_dir &

