#!/bin/tcsh

set DAT = ../../afni_test_data/data

cp ../../afni_test_data/3dSkullStrip/* .
# clean up the trash

\rm -f SS* runit.out

time 3dSkullStrip -input ${DAT}/anat+orig -prefix ./SSout \
                  -ld 50 -debug 1                                      |& tee runit.out

if ( ! -f Baseline_SSout+orig.HEAD ) then
  \rm -f Baseline_*
  3drename SSout+orig Baseline_SSout                                   |& tee -a runit.out
  gzip -9v Baseline_*.BRIK
else
  echo '===== 3dSkullStrip difference from Baseline ====='             |& tee -a runit.out
  3dinfo -sval_diff SSout+orig Baseline_SSout+orig                     |& tee -a runit.out
endif

if( $#argv == 0 ) then
  echo '..... deleting output files .....'
  \rm -f SS*
  exit 0
else if( $argv[1] != 'KEEP' ) then
  echo '..... deleting output files .....'
  \rm -f SS*
else
  echo '..... keeping output files .....'
endif

exit 0
